In [1]:
import pandas as pd
import numpy as np

#load files
abb = pd.read_csv('../../data_source/state-abbrevs.csv')
areas = pd.read_csv('../../data_source/state-areas.csv')
pops = pd.read_csv('../../data_source/state-population.csv')

#merge population and abbreviations
merged = pd.merge(pops,abb,how='outer',left_on='state/region',right_on='abbreviation')
print(merged)
print(merged.isnull().any())
merged = merged.drop('abbreviation',1)

# print(merged.head())
# print(abb.head())
# print(pops.head())
# print(areas.head())

     state/region     ages  year   population    state abbreviation
0              AL  under18  2012    1117489.0  Alabama           AL
1              AL    total  2012    4817528.0  Alabama           AL
2              AL  under18  2010    1130966.0  Alabama           AL
3              AL    total  2010    4785570.0  Alabama           AL
4              AL  under18  2011    1125763.0  Alabama           AL
...           ...      ...   ...          ...      ...          ...
2539          USA    total  2010  309326295.0      NaN          NaN
2540          USA  under18  2011   73902222.0      NaN          NaN
2541          USA    total  2011  311582564.0      NaN          NaN
2542          USA  under18  2012   73708179.0      NaN          NaN
2543          USA    total  2012  313873685.0      NaN          NaN

[2544 rows x 6 columns]
state/region    False
ages            False
year            False
population       True
state            True
abbreviation     True
dtype: bool

In [2]:
# print(np.invert(merged['population'].isnull()))
# print(merged[np.invert(merged['population'].isnull())].head())
# print(merged[merged['population'].isnull()].head())

#print state 缺失值
print(merged.loc[merged['state'].isnull(),'state/region'].unique())

#填补 state 缺失值
merged.loc[merged['state/region']=='USA','state'] = 'United States'
merged.loc[merged['state/region']=='PR','state'] = 'Puerto Rico'

#确认是否填充
print(merged.isnull().any())

['PR' 'USA']
state/region    False
ages            False
year            False
population       True
state           False
dtype: bool

In [ ]:
final = pd.merge(merged,areas,on='state',how='left')
#final.loc[if this column is empty ,keyword]
print(final.loc[final['area (sq. mi)'].isnull(),'state/region'].unique()) 
print(final['state'][final['area (sq. mi)'].isnull()].unique())
final.dropna(inplace=True)
for i,j in final.iterrows():
    print(j)

['USA']
['United States']
state/region              AL
ages                 under18
year                    2012
population       1.11749e+06
state                Alabama
area (sq. mi)          52423
Name: 0, dtype: object
state/region              AL
ages                   total
year                    2012
population       4.81753e+06
state                Alabama
area (sq. mi)          52423
Name: 1, dtype: object
state/region              AL
ages                 under18
year                    2010
population       1.13097e+06
state                Alabama
area (sq. mi)          52423
Name: 2, dtype: object
state/region              AL
ages                   total
year                    2010
population       4.78557e+06
state                Alabama
area (sq. mi)          52423
Name: 3, dtype: object
state/region              AL
ages                 under18
year                    2011
population       1.12576e+06
state                Alabama
area (sq. mi)          52423
Name: 4, dtype: object
state/region              AL
ages                   total
year                    2011
population       4.80163e+06
state                Alabama
area (sq. mi)          52423
Name: 5, dtype: object
state/region              AL
ages                   total
year                    2009
population       4.75794e+06
state                Alabama
area (sq. mi)          52423
Name: 6, dtype: object
state/region              AL
ages                 under18
year                    2009
population       1.13419e+06
state                Alabama
area (sq. mi)          52423
Name: 7, dtype: object
state/region              AL
ages                 under18
year                    2013
population       1.11148e+06
state                Alabama
area (sq. mi)          52423
Name: 8, dtype: object
state/region              AL
ages                   total
year                    2013
population       4.83372e+06
state                Alabama
area (sq. mi)          52423
Name: 9, dtype: object
state/region              AL
ages                   total
year                    2007
population       4.67284e+06
state                Alabama
area (sq. mi)          52423
Name: 10, dtype: object
state/region             AL
ages                under18
year                   2007
population       1.1323e+06
state               Alabama
area (sq. mi)         52423
Name: 11, dtype: object
state/region              AL
ages                   total
year                    2008
population       4.71821e+06
state                Alabama
area (sq. mi)          52423
Name: 12, dtype: object
state/region              AL
ages                 under18
year                    2008
population       1.13493e+06
state                Alabama
area (sq. mi)          52423
Name: 13, dtype: object
state/region              AL
ages                   total
year                    2005
population       4.56980e+06
state                Alabama
area (sq. mi)          52423
Name: 14, dtype: object
state/region              AL
ages                 under18
year                    2005
population       1.11723e+06
state                Alabama
area (sq. mi)          52423
Name: 15, dtype: object
state/region              AL
ages                   total
year                    2006
population       4.62898e+06
state                Alabama
area (sq. mi)          52423
Name: 16, dtype: object
state/region             AL
ages                under18
year                   2006
population       1.1268e+06
state               Alabama
area (sq. mi)         52423
Name: 17, dtype: object
state/region              AL
ages                   total
year                    2004
population       4.53073e+06
state                Alabama
area (sq. mi)          52423
Name: 18, dtype: object
state/region              AL
ages                 under18
year                    2004
population       1.11366e+06
state                Alabama
area (sq. mi)          52423
Name: 19, dtype: object
state/region              AL
ages                   total
year                    2003
population       4.50349e+06
state                Alabama
area (sq. mi)          52423
Name: 20, dtype: object
state/region              AL
ages                 under18
year                    2003
population       1.11308e+06
state                Alabama
area (sq. mi)          52423
Name: 21, dtype: object
state/region              AL
ages                   total
year                    2001
population       4.46763e+06
state                Alabama
area (sq. mi)          52423
Name: 22, dtype: object
state/region              AL
ages                 under18
year                    2001
population       1.12041e+06
state                Alabama
area (sq. mi)          52423
Name: 23, dtype: object
state/region              AL
ages                   total
year                    2002
population       4.48009e+06
state                Alabama
area (sq. mi)          52423
Name: 24, dtype: object
state/region              AL
ages                 under18
year                    2002
population       1.11659e+06
state                Alabama
area (sq. mi)          52423
Name: 25, dtype: object
state/region              AL
ages                 under18
year                    1999
population       1.12129e+06
state                Alabama
area (sq. mi)          52423
Name: 26, dtype: object
state/region              AL
ages                   total
year                    1999
population       4.43014e+06
state                Alabama
area (sq. mi)          52423
Name: 27, dtype: object
state/region              AL
ages                   total
year                    2000
population       4.45217e+06
state                Alabama
area (sq. mi)          52423
Name: 28, dtype: object
state/region              AL
ages                 under18
year                    2000
population       1.12227e+06
state                Alabama
area (sq. mi)          52423
Name: 29, dtype: object
state/region             AL
ages                  total
year                   1998
population       4.4047e+06
state               Alabama
area (sq. mi)         52423
Name: 30, dtype: object
state/region              AL
ages                 under18
year                    1998
population       1.11825e+06
state                Alabama
area (sq. mi)          52423
Name: 31, dtype: object
state/region              AL
ages                 under18
year                    1997
population       1.12289e+06
state                Alabama
area (sq. mi)          52423
Name: 32, dtype: object
state/region              AL
ages                   total
year                    1997
population       4.36794e+06
state                Alabama
area (sq. mi)          52423
Name: 33, dtype: object
state/region             AL
ages                  total
year                   1996
population       4.3311e+06
state               Alabama
area (sq. mi)         52423
Name: 34, dtype: object
state/region             AL
ages                  total
year                   1995
population       4.2968e+06
state               Alabama
area (sq. mi)         52423
Name: 35, dtype: object
state/region              AL
ages                 under18
year                    1995
population       1.11055e+06
state                Alabama
area (sq. mi)          52423
Name: 36, dtype: object
state/region              AL
ages                 under18
year                    1996
population       1.11209e+06
state                Alabama
area (sq. mi)          52423
Name: 37, dtype: object
state/region              AL
ages                   total
year                    1994
population       4.26023e+06
state                Alabama
area (sq. mi)          52423
Name: 38, dtype: object
state/region             AL
ages                  total
year                   1993
population       4.2142e+06
state               Alabama
area (sq. mi)         52423
Name: 39, dtype: object
state/region              AL
ages                 under18
year                    1993
population       1.08561e+06
state                Alabama
area (sq. mi)          52423
Name: 40, dtype: object
state/region              AL
ages                 under18
year                    1994
population       1.09718e+06
state                Alabama
area (sq. mi)          52423
Name: 41, dtype: object
state/region              AL
ages                 under18
year                    1992
population       1.07287e+06
state                Alabama
area (sq. mi)          52423
Name: 42, dtype: object
state/region              AL
ages                   total
year                    1992
population       4.15401e+06
state                Alabama
area (sq. mi)          52423
Name: 43, dtype: object
state/region              AL
ages                   total
year                    1991
population       4.09916e+06
state                Alabama
area (sq. mi)          52423
Name: 44, dtype: object
state/region              AL
ages                 under18
year                    1991
population       1.06079e+06
state                Alabama
area (sq. mi)          52423
Name: 45, dtype: object
state/region              AL
ages                 under18
year                    1990
population       1.05004e+06
state                Alabama
area (sq. mi)          52423
Name: 46, dtype: object
state/region              AL
ages                   total
year                    1990
population       4.05006e+06
state                Alabama
area (sq. mi)          52423
Name: 47, dtype: object
state/region         AK
ages              total
year               1990
population       553290
state            Alaska
area (sq. mi)    656425
Name: 48, dtype: object
state/region          AK
ages             under18
year                1990
population        177502
state             Alaska
area (sq. mi)     656425
Name: 49, dtype: object
state/region         AK
ages              total
year               1992
population       588736
state            Alaska
area (sq. mi)    656425
Name: 50, dtype: object
state/region          AK
ages             under18
year                1991
population        182180
state             Alaska
area (sq. mi)     656425
Name: 51, dtype: object
state/region          AK
ages             under18
year                1992
population        184878
state             Alaska
area (sq. mi)     656425
Name: 52, dtype: object
state/region         AK
ages              total
year               1994
population       603308
state            Alaska
area (sq. mi)    656425
Name: 53, dtype: object
state/region          AK
ages             under18
year                1994
population        187439
state             Alaska
area (sq. mi)     656425
Name: 54, dtype: object
state/region         AK
ages              total
year               1991
population       570193
state            Alaska
area (sq. mi)    656425
Name: 55, dtype: object
state/region         AK
ages              total
year               1993
population       599434
state            Alaska
area (sq. mi)    656425
Name: 56, dtype: object
state/region          AK
ages             under18
year                1993
population        187190
state             Alaska
area (sq. mi)     656425
Name: 57, dtype: object
state/region         AK
ages              total
year               1995
population       604412
state            Alaska
area (sq. mi)    656425
Name: 58, dtype: object

state/region          AK
ages             under18
year                1995
population        184990
state             Alaska
area (sq. mi)     656425
Name: 59, dtype: object
state/region         AK
ages              total
year               1996
population       608569
state            Alaska
area (sq. mi)    656425
Name: 60, dtype: object
state/region          AK
ages             under18
year                1996
population        185360
state             Alaska
area (sq. mi)     656425
Name: 61, dtype: object
state/region          AK
ages             under18
year                1997
population        188280
state             Alaska
area (sq. mi)     656425
Name: 62, dtype: object
state/region          AK
ages             under18
year                1998
population        192636
state             Alaska
area (sq. mi)     656425
Name: 63, dtype: object
state/region         AK
ages              total
year               1998
population       619933
state            Alaska
area (sq. mi)    656425
Name: 64, dtype: object
state/region         AK
ages              total
year               1997
population       612968
state            Alaska
area (sq. mi)    656425
Name: 65, dtype: object
state/region          AK
ages             under18
year                1999
population        191422
state             Alaska
area (sq. mi)     656425
Name: 66, dtype: object
state/region         AK
ages              total
year               1999
population       624779
state            Alaska
area (sq. mi)    656425
Name: 67, dtype: object
state/region         AK
ages              total
year               2000
population       627963
state            Alaska
area (sq. mi)    656425
Name: 68, dtype: object
state/region          AK
ages             under18
year                2000
population        190615
state             Alaska
area (sq. mi)     656425
Name: 69, dtype: object
state/region         AK
ages              total
year               2001
population       633714
state            Alaska
area (sq. mi)    656425
Name: 70, dtype: object
state/region          AK
ages             under18
year                2001
population        188771
state             Alaska
area (sq. mi)     656425
Name: 71, dtype: object
state/region         AK
ages              total
year               2002
population       642337
state            Alaska
area (sq. mi)    656425
Name: 72, dtype: object
state/region          AK
ages             under18
year                2002
population        188482
state             Alaska
area (sq. mi)     656425
Name: 73, dtype: object
state/region         AK
ages              total
year               2003
population       648414
state            Alaska
area (sq. mi)    656425
Name: 74, dtype: object
state/region          AK
ages             under18
year                2003
population        186843
state             Alaska
area (sq. mi)     656425
Name: 75, dtype: object
state/region         AK
ages              total
year               2004
population       659286
state            Alaska
area (sq. mi)    656425
Name: 76, dtype: object
state/region          AK
ages             under18
year                2004
population        186335
state             Alaska
area (sq. mi)     656425
Name: 77, dtype: object
state/region         AK
ages              total
year               2005
population       666946
state            Alaska
area (sq. mi)    656425
Name: 78, dtype: object
state/region          AK
ages             under18
year                2005
population        185304
state             Alaska
area (sq. mi)     656425
Name: 79, dtype: object
state/region         AK
ages              total
year               2006
population       675302
state            Alaska
area (sq. mi)    656425
Name: 80, dtype: object
state/region          AK
ages             under18
year                2006
population        185580
state             Alaska
area (sq. mi)     656425
Name: 81, dtype: object
state/region         AK
ages              total
year               2007
population       680300
state            Alaska
area (sq. mi)    656425
Name: 82, dtype: object
state/region          AK
ages             under18
year                2007
population        184344
state             Alaska
area (sq. mi)     656425
Name: 83, dtype: object
state/region         AK
ages              total
year               2008
population       687455
state            Alaska
area (sq. mi)    656425
Name: 84, dtype: object
state/region          AK
ages             under18
year                2008
population        183124
state             Alaska
area (sq. mi)     656425
Name: 85, dtype: object
state/region          AK
ages             under18
year                2013
population        188132
state             Alaska
area (sq. mi)     656425
Name: 86, dtype: object
state/region         AK
ages              total
year               2013
population       735132
state            Alaska
area (sq. mi)    656425
Name: 87, dtype: object
state/region         AK
ages              total
year               2009
population       698895
state            Alaska
area (sq. mi)    656425
Name: 88, dtype: object
state/region          AK
ages             under18
year                2009
population        186351
state             Alaska
area (sq. mi)     656425
Name: 89, dtype: object
state/region          AK
ages             under18
year                2010
population        187902
state             Alaska
area (sq. mi)     656425
Name: 90, dtype: object
state/region         AK
ages              total
year               2010
population       713868
state            Alaska
area (sq. mi)    656425
Name: 91, dtype: object
state/region          AK
ages             under18
year                2011
population        188329
state             Alaska
area (sq. mi)     656425
Name: 92, dtype: object
state/region         AK
ages              total
year               2011
population       723375
state            Alaska
area (sq. mi)    656425
Name: 93, dtype: object
state/region          AK
ages             under18
year                2012
population        188162
state             Alaska
area (sq. mi)     656425
Name: 94, dtype: object
state/region         AK
ages              total
year               2012
population       730307
state            Alaska
area (sq. mi)    656425
Name: 95, dtype: object
state/region              AZ
ages                 under18
year                    2012
population       1.61715e+06
state                Arizona
area (sq. mi)         114006
Name: 96, dtype: object
state/region              AZ
ages                   total
year                    2012
population       6.55115e+06
state                Arizona
area (sq. mi)         114006
Name: 97, dtype: object
state/region              AZ
ages                 under18
year                    2011
population       1.61635e+06
state                Arizona
area (sq. mi)         114006
Name: 98, dtype: object
state/region             AZ
ages                  total
year                   2011
population       6.4688e+06
state               Arizona
area (sq. mi)        114006
Name: 99, dtype: object
state/region              AZ
ages                 under18
year                    2010
population       1.62856e+06
state                Arizona
area (sq. mi)         114006
Name: 100, dtype: object
state/region              AZ
ages                   total
year                    2010
population       6.40879e+06
state                Arizona
area (sq. mi)         114006
Name: 101, dtype: object
state/region              AZ
ages                 under18
year                    2013
population       1.61681e+06
state                Arizona
area (sq. mi)         114006
Name: 102, dtype: object
state/region              AZ
ages                   total
year                    2013
population       6.62662e+06
state                Arizona
area (sq. mi)         114006
Name: 103, dtype: object
state/region              AZ
ages                   total
year                    2009
population       6.34315e+06
state                Arizona
area (sq. mi)         114006
Name: 104, dtype: object
state/region              AZ
ages                 under18
year                    2009
population       1.62734e+06
state                Arizona
area (sq. mi)         114006
Name: 105, dtype: object
state/region              AZ
ages                   total
year                    2007
population       6.16768e+06
state                Arizona
area (sq. mi)         114006
Name: 106, dtype: object
state/region             AZ
ages                under18
year                   2007
population       1.6079e+06
state               Arizona
area (sq. mi)        114006
Name: 107, dtype: object
state/region              AZ
ages                   total
year                    2008
population       6.28036e+06
state                Arizona
area (sq. mi)         114006
Name: 108, dtype: object
state/region              AZ
ages                 under18
year                    2008
population       1.62865e+06
state                Arizona
area (sq. mi)         114006
Name: 109, dtype: object
state/region              AZ
ages                   total
year                    2005
population       5.83908e+06
state                Arizona
area (sq. mi)         114006
Name: 110, dtype: object
state/region              AZ
ages                 under18
year                    2005
population       1.52917e+06
state                Arizona
area (sq. mi)         114006
Name: 111, dtype: object
state/region              AZ
ages                   total
year                    2006
population       6.02914e+06
state                Arizona
area (sq. mi)         114006
Name: 112, dtype: object
state/region              AZ
ages                 under18
year                    2006
population       1.57487e+06
state                Arizona
area (sq. mi)         114006
Name: 113, dtype: object
state/region             AZ
ages                  total
year                   2004
population       5.6524e+06
state               Arizona
area (sq. mi)        114006
Name: 114, dtype: object
state/region              AZ
ages                 under18
year                    2004
population       1.48445e+06
state                Arizona
area (sq. mi)         114006
Name: 115, dtype: object
state/region              AZ
ages                   total
year                    2003
population       5.51036e+06
state                Arizona
area (sq. mi)         114006
Name: 116, dtype: object
state/region              AZ
ages                 under18
year                    2003
population       1.45367e+06
state                Arizona
area (sq. mi)         114006
Name: 117, dtype: object
state/region              AZ
ages                   total
year                    2001
population       5.27348e+06
state                Arizona
area (sq. mi)         114006
Name: 118, dtype: object
state/region              AZ
ages                 under18
year                    2001
population       1.39902e+06
state                Arizona
area (sq. mi)         114006
Name: 119, dtype: object
state/region              AZ
ages                   total
year                    2002
population       5.39626e+06
state                Arizona
area (sq. mi)         114006
Name: 120, dtype: object
state/region              AZ
ages                 under18
year                    2002
population       1.42794e+06
state                Arizona
area (sq. mi)         114006
Name: 121, dtype: object
state/region             AZ
ages                under18
year                   1999
population       1.3324e+06
state               Arizona
area (sq. mi)        114006
Name: 122, dtype: object
state/region              AZ
ages                   total
year                    1999
population       5.02382e+06
state                Arizona
area (sq. mi)         114006
Name: 123, dtype: object
state/region              AZ
ages                   total
year                    2000
population       5.16059e+06
state                Arizona
area (sq. mi)         114006
Name: 124, dtype: object
state/region              AZ
ages                 under18
year                    2000
population       1.37341e+06
state                Arizona
area (sq. mi)         114006
Name: 125, dtype: object
state/region              AZ
ages                   total
year                    1998
population       4.88334e+06
state                Arizona
area (sq. mi)         114006
Name: 126, dtype: object
state/region              AZ
ages                 under18
year                    1998
population       1.28579e+06
state                Arizona
area (sq. mi)         114006
Name: 127, dtype: object
state/region              AZ
ages                   total
year                    1997
population       4.73699e+06
state                Arizona
area (sq. mi)         114006
Name: 128, dtype: object
state/region              AZ
ages                 under18
year                    1997
population       1.23716e+06
state                Arizona
area (sq. mi)         114006
Name: 129, dtype: object
state/region              AZ
ages                 under18
year                    1996
population       1.21528e+06
state                Arizona
area (sq. mi)         114006
Name: 130, dtype: object
state/region              AZ
ages                   total
year                    1996
population       4.58694e+06
state                Arizona
area (sq. mi)         114006
Name: 131, dtype: object
state/region             AZ
ages                  total
year                   1995
population       4.4325e+06
state               Arizona
area (sq. mi)        114006
Name: 132, dtype: object
state/region              AZ
ages                 under18
year                    1995
population       1.17339e+06
state                Arizona
area (sq. mi)         114006
Name: 133, dtype: object
state/region              AZ
ages                   total
year                    1993
population       4.06544e+06
state                Arizona
area (sq. mi)         114006
Name: 134, dtype: object
state/region              AZ
ages                 under18
year                    1993
population       1.09423e+06
state                Arizona
area (sq. mi)         114006
Name: 135, dtype: object
state/region              AZ
ages                 under18
year                    1994
population       1.11986e+06
state                Arizona
area (sq. mi)         114006
Name: 136, dtype: object
state/region              AZ
ages                   total
year                    1994
population       4.24509e+06
state                Arizona
area (sq. mi)         114006
Name: 137, dtype: object
state/region              AZ
ages                 under18
year                    1992
population       1.05557e+06
state                Arizona
area (sq. mi)         114006
Name: 138, dtype: object
state/region              AZ
ages                 under18
year                    1991
population       1.02828e+06
state                Arizona
area (sq. mi)         114006
Name: 139, dtype: object
state/region              AZ
ages                   total
year                    1991
population       3.78858e+06
state                Arizona
area (sq. mi)         114006
Name: 140, dtype: object
state/region              AZ
ages                   total
year                    1992
population       3.91574e+06
state                Arizona
area (sq. mi)         114006
Name: 141, dtype: object
state/region              AZ
ages                 under18
year                    1990
population       1.00604e+06
state                Arizona
area (sq. mi)         114006
Name: 142, dtype: object
state/region             AZ
ages                  total
year                   1990
population       3.6841e+06
state               Arizona
area (sq. mi)        114006
Name: 143, dtype: object
state/region           AR
ages              under18
year                 1990
population         620933
state            Arkansas
area (sq. mi)       53182
Name: 144, dtype: object
state/region              AR
ages                   total
year                    1990
population       2.35659e+06
state               Arkansas
area (sq. mi)          53182
Name: 145, dtype: object
state/region              AR
ages                   total
year                    1991
population       2.38314e+06
state               Arkansas
area (sq. mi)          53182
Name: 146, dtype: object
state/region           AR
ages              under18
year                 1991
population         626212
state            Arkansas
area (sq. mi)       53182
Name: 147, dtype: object
state/region           AR
ages              under18
year                 1992
population         638269
state            Arkansas
area (sq. mi)       53182
Name: 148, dtype: object
state/region              AR
ages                   total
year                    1992
population       2.41598e+06
state               Arkansas
area (sq. mi)          53182
Name: 149, dtype: object
state/region           AR
ages              under18
year                 1994
population         653842
state            Arkansas
area (sq. mi)       53182
Name: 150, dtype: object
state/region              AR
ages                   total
year                    1994
population       2.49402e+06
state               Arkansas
area (sq. mi)          53182
Name: 151, dtype: object
state/region             AR
ages                  total
year                   1993
population       2.4563e+06
state              Arkansas
area (sq. mi)         53182
Name: 152, dtype: object
state/region           AR
ages              under18
year                 1993
population         643474
state            Arkansas
area (sq. mi)       53182
Name: 153, dtype: object
state/region           AR
ages              under18
year                 1995
population         667671
state            Arkansas
area (sq. mi)       53182
Name: 154, dtype: object
state/region             AR
ages                  total
year                   1995
population       2.5354e+06
state              Arkansas
area (sq. mi)         53182
Name: 155, dtype: object
state/region           AR
ages              under18
year                 1996
population         677912
state            Arkansas
area (sq. mi)       53182
Name: 156, dtype: object
state/region              AR
ages                   total
year                    1996
population       2.57211e+06
state               Arkansas
area (sq. mi)          53182
Name: 157, dtype: object
state/region           AR
ages              under18
year                 1998
population         683637
state            Arkansas
area (sq. mi)       53182
Name: 158, dtype: object
state/region              AR
ages                   total
year                    1997
population       2.60109e+06
state               Arkansas
area (sq. mi)          53182
Name: 159, dtype: object
state/region           AR
ages              under18
year                 1997
population         680203
state            Arkansas
area (sq. mi)       53182
Name: 160, dtype: object
state/region              AR
ages                   total
year                    1998
population       2.62629e+06
state               Arkansas
area (sq. mi)          53182
Name: 161, dtype: object
state/region              AR
ages                   total
year                    2000
population       2.67859e+06
state               Arkansas
area (sq. mi)          53182
Name: 162, dtype: object
state/region           AR
ages              under18
year                 2000
population         680378
state            Arkansas
area (sq. mi)       53182
Name: 163, dtype: object

state/region           AR
ages              under18
year                 1999
population         681940
state            Arkansas
area (sq. mi)       53182
Name: 164, dtype: object
state/region              AR
ages                   total
year                    1999
population       2.65186e+06
state               Arkansas
area (sq. mi)          53182
Name: 165, dtype: object
state/region              AR
ages                   total
year                    2002
population       2.70593e+06
state               Arkansas
area (sq. mi)          53182
Name: 166, dtype: object
state/region           AR
ages              under18
year                 2002
population         678798
state            Arkansas
area (sq. mi)       53182
Name: 167, dtype: object
state/region              AR
ages                   total
year                    2001
population       2.69157e+06
state               Arkansas
area (sq. mi)          53182
Name: 168, dtype: object
state/region           AR
ages              under18
year                 2001
population         679606
state            Arkansas
area (sq. mi)       53182
Name: 169, dtype: object
state/region              AR
ages                   total
year                    2004
population       2.74969e+06
state               Arkansas
area (sq. mi)          53182
Name: 170, dtype: object
state/region           AR
ages              under18
year                 2004
population         683166
state            Arkansas
area (sq. mi)       53182
Name: 171, dtype: object
state/region              AR
ages                   total
year                    2003
population       2.72482e+06
state               Arkansas
area (sq. mi)          53182
Name: 172, dtype: object
state/region           AR
ages              under18
year                 2003
population         679579
state            Arkansas
area (sq. mi)       53182
Name: 173, dtype: object
state/region              AR
ages                   total
year                    2006
population       2.82176e+06
state               Arkansas
area (sq. mi)          53182
Name: 174, dtype: object
state/region           AR
ages              under18
year                 2006
population         697842
state            Arkansas
area (sq. mi)       53182
Name: 175, dtype: object
state/region             AR
ages                  total
year                   2005
population       2.7811e+06
state              Arkansas
area (sq. mi)         53182
Name: 176, dtype: object
state/region           AR
ages              under18
year                 2005
population         689787
state            Arkansas
area (sq. mi)       53182
Name: 177, dtype: object
state/region              AR
ages                   total
year                    2008
population       2.87455e+06
state               Arkansas
area (sq. mi)          53182
Name: 178, dtype: object
state/region           AR
ages              under18
year                 2008
population         705725
state            Arkansas
area (sq. mi)       53182
Name: 179, dtype: object
state/region              AR
ages                   total
year                    2007
population       2.84865e+06
state               Arkansas
area (sq. mi)          53182
Name: 180, dtype: object
state/region           AR
ages              under18
year                 2007
population         702737
state            Arkansas
area (sq. mi)       53182
Name: 181, dtype: object
state/region              AR
ages                   total
year                    2009
population       2.89684e+06
state               Arkansas
area (sq. mi)          53182
Name: 182, dtype: object
state/region           AR
ages              under18
year                 2009
population         707886
state            Arkansas
area (sq. mi)       53182
Name: 183, dtype: object
state/region           AR
ages              under18
year                 2013
population         709866
state            Arkansas
area (sq. mi)       53182
Name: 184, dtype: object
state/region              AR
ages                   total
year                    2013
population       2.95937e+06
state               Arkansas
area (sq. mi)          53182
Name: 185, dtype: object
state/region           AR
ages              under18
year                 2011
population         710576
state            Arkansas
area (sq. mi)       53182
Name: 186, dtype: object
state/region              AR
ages                   total
year                    2011
population       2.93851e+06
state               Arkansas
area (sq. mi)          53182
Name: 187, dtype: object
state/region           AR
ages              under18
year                 2010
population         711947
state            Arkansas
area (sq. mi)       53182
Name: 188, dtype: object
state/region              AR
ages                   total
year                    2010
population       2.92228e+06
state               Arkansas
area (sq. mi)          53182
Name: 189, dtype: object
state/region           AR
ages              under18
year                 2012
population         710471
state            Arkansas
area (sq. mi)       53182
Name: 190, dtype: object
state/region              AR
ages                   total
year                    2012
population       2.94983e+06
state               Arkansas
area (sq. mi)          53182
Name: 191, dtype: object
state/region              CA
ages                 under18
year                    2012
population       9.20901e+06
state             California
area (sq. mi)         163707
Name: 192, dtype: object
state/region              CA
ages                   total
year                    2012
population       3.79999e+07
state             California
area (sq. mi)         163707
Name: 193, dtype: object
state/region              CA
ages                 under18
year                    2011
population       9.25234e+06
state             California
area (sq. mi)         163707
Name: 194, dtype: object
state/region              CA
ages                   total
year                    2011
population       3.76687e+07
state             California
area (sq. mi)         163707
Name: 195, dtype: object
state/region              CA
ages                 under18
year                    2010
population       9.28409e+06
state             California
area (sq. mi)         163707
Name: 196, dtype: object
state/region              CA
ages                   total
year                    2010
population       3.73336e+07
state             California
area (sq. mi)         163707
Name: 197, dtype: object
state/region              CA
ages                 under18
year                    2013
population       9.17488e+06
state             California
area (sq. mi)         163707
Name: 198, dtype: object
state/region              CA
ages                   total
year                    2013
population       3.83325e+07
state             California
area (sq. mi)         163707
Name: 199, dtype: object
state/region              CA
ages                   total
year                    2009
population       3.69612e+07
state             California
area (sq. mi)         163707
Name: 200, dtype: object
state/region             CA
ages                under18
year                   2009
population       9.2945e+06
state            California
area (sq. mi)        163707
Name: 201, dtype: object
state/region              CA
ages                   total
year                    2007
population       3.62503e+07
state             California
area (sq. mi)         163707
Name: 202, dtype: object
state/region              CA
ages                 under18
year                    2007
population       9.33562e+06
state             California
area (sq. mi)         163707
Name: 203, dtype: object
state/region              CA
ages                   total
year                    2008
population       3.66043e+07
state             California
area (sq. mi)         163707
Name: 204, dtype: object
state/region              CA
ages                 under18
year                    2008
population       9.32162e+06
state             California
area (sq. mi)         163707
Name: 205, dtype: object
state/region              CA
ages                   total
year                    2005
population       3.58279e+07
state             California
area (sq. mi)         163707
Name: 206, dtype: object
state/region              CA
ages                 under18
year                    2005
population       9.40556e+06
state             California
area (sq. mi)         163707
Name: 207, dtype: object
state/region              CA
ages                   total
year                    2006
population       3.60212e+07
state             California
area (sq. mi)         163707
Name: 208, dtype: object
state/region              CA
ages                 under18
year                    2006
population       9.37088e+06
state             California
area (sq. mi)         163707
Name: 209, dtype: object
state/region              CA
ages                   total
year                    2003
population       3.52532e+07
state             California
area (sq. mi)         163707

Name: 210, dtype: object
state/region              CA
ages                 under18
year                    2003
population       9.40459e+06
state             California
area (sq. mi)         163707
Name: 211, dtype: object
state/region              CA
ages                   total
year                    2004
population       3.55746e+07
state             California
area (sq. mi)         163707
Name: 212, dtype: object
state/region             CA
ages                under18
year                   2004
population       9.4185e+06
state            California
area (sq. mi)        163707
Name: 213, dtype: object
state/region              CA
ages                   total
year                    2001
population       3.44795e+07
state             California
area (sq. mi)         163707
Name: 214, dtype: object
state/region              CA
ages                 under18
year                    2001
population       9.32547e+06
state             California
area (sq. mi)         163707
Name: 215, dtype: object
state/region              CA
ages                   total
year                    2002
population       3.48718e+07
state             California
area (sq. mi)         163707
Name: 216, dtype: object
state/region              CA
ages                 under18
year                    2002
population       9.36514e+06
state             California
area (sq. mi)         163707
Name: 217, dtype: object
state/region              CA
ages                 under18
year                    1999
population       9.20788e+06
state             California
area (sq. mi)         163707
Name: 218, dtype: object
state/region              CA
ages                   total
year                    1999
population       3.34992e+07
state             California
area (sq. mi)         163707
Name: 219, dtype: object
state/region             CA
ages                  total
year                   2000
population       3.3988e+07
state            California
area (sq. mi)        163707
Name: 220, dtype: object
state/region              CA
ages                 under18
year                    2000
population       9.26709e+06
state             California
area (sq. mi)         163707
Name: 221, dtype: object
state/region              CA
ages                 under18
year                    1998
population       9.16324e+06
state             California
area (sq. mi)         163707
Name: 222, dtype: object
state/region              CA
ages                   total
year                    1998
population       3.29877e+07
state             California
area (sq. mi)         163707
Name: 223, dtype: object
state/region              CA
ages                 under18
year                    1997
population       9.13536e+06
state             California
area (sq. mi)         163707
Name: 224, dtype: object
state/region             CA
ages                  total
year                   1997
population       3.2486e+07
state            California
area (sq. mi)        163707
Name: 225, dtype: object
state/region              CA
ages                 under18
year                    1996
population       9.07952e+06
state             California
area (sq. mi)         163707
Name: 226, dtype: object
state/region              CA
ages                   total
year                    1996
population       3.20188e+07
state             California
area (sq. mi)         163707
Name: 227, dtype: object
state/region              CA
ages                   total
year                    1995
population       3.16966e+07
state             California
area (sq. mi)         163707
Name: 228, dtype: object
state/region              CA
ages                 under18
year                    1995
population       8.92058e+06
state             California
area (sq. mi)         163707
Name: 229, dtype: object
state/region              CA
ages                   total
year                    1993
population       3.12749e+07
state             California
area (sq. mi)         163707
Name: 230, dtype: object
state/region              CA
ages                 under18
year                    1993
population       8.62481e+06
state             California
area (sq. mi)         163707
Name: 231, dtype: object
state/region              CA
ages                 under18
year                    1994
population       8.79006e+06
state             California
area (sq. mi)         163707
Name: 232, dtype: object
state/region              CA
ages                   total
year                    1994
population       3.14844e+07
state             California
area (sq. mi)         163707
Name: 233, dtype: object
state/region              CA
ages                   total
year                    1991
population       3.04707e+07
state             California
area (sq. mi)         163707
Name: 234, dtype: object
state/region              CA
ages                 under18
year                    1991
population       8.24560e+06
state             California
area (sq. mi)         163707
Name: 235, dtype: object
state/region              CA
ages                 under18
year                    1992
population       8.43965e+06
state             California
area (sq. mi)         163707
Name: 236, dtype: object
state/region              CA
ages                   total
year                    1992
population       3.09747e+07
state             California
area (sq. mi)         163707
Name: 237, dtype: object
state/region             CA
ages                under18
year                   1990
population       7.9805e+06
state            California
area (sq. mi)        163707
Name: 238, dtype: object
state/region              CA
ages                   total
year                    1990
population       2.99595e+07
state             California
area (sq. mi)         163707
Name: 239, dtype: object
state/region              CO
ages                   total
year                    1990
population       3.30762e+06
state               Colorado
area (sq. mi)         104100
Name: 240, dtype: object
state/region           CO
ages              under18
year                 1990
population         881640
state            Colorado
area (sq. mi)      104100
Name: 241, dtype: object
state/region              CO
ages                   total
year                    1992
population       3.49594e+06
state               Colorado
area (sq. mi)         104100
Name: 242, dtype: object
state/region           CO
ages              under18
year                 1992
population         925577
state            Colorado
area (sq. mi)      104100
Name: 243, dtype: object
state/region           CO
ages              under18
year                 1991
population         896537
state            Colorado
area (sq. mi)      104100
Name: 244, dtype: object
state/region              CO
ages                   total
year                    1991
population       3.38712e+06
state               Colorado
area (sq. mi)         104100
Name: 245, dtype: object
state/region              CO
ages                   total
year                    1994
population       3.72417e+06
state               Colorado
area (sq. mi)         104100
Name: 246, dtype: object
state/region           CO
ages              under18
year                 1994
population         966412
state            Colorado
area (sq. mi)      104100
Name: 247, dtype: object
state/region           CO
ages              under18
year                 1993
population         947806
state            Colorado
area (sq. mi)      104100
Name: 248, dtype: object
state/region              CO
ages                   total
year                    1993
population       3.61373e+06
state               Colorado
area (sq. mi)         104100
Name: 249, dtype: object
state/region           CO
ages              under18
year                 1995
population         984310
state            Colorado
area (sq. mi)      104100
Name: 250, dtype: object
state/region              CO
ages                   total
year                    1995
population       3.82665e+06
state               Colorado
area (sq. mi)         104100
Name: 251, dtype: object
state/region              CO
ages                   total
year                    1996
population       3.91997e+06
state               Colorado
area (sq. mi)         104100
Name: 252, dtype: object
state/region              CO
ages                 under18
year                    1996
population       1.00395e+06
state               Colorado
area (sq. mi)         104100
Name: 253, dtype: object
state/region              CO
ages                 under18
year                    1997
population       1.03056e+06
state               Colorado
area (sq. mi)         104100
Name: 254, dtype: object
state/region              CO
ages                   total
year                    1997
population       4.01829e+06
state               Colorado
area (sq. mi)         104100
Name: 255, dtype: object
state/region              CO
ages                   total
year                    1998
population       4.11664e+06
state               Colorado
area (sq. mi)         104100
Name: 256, dtype: object
state/region              CO
ages                 under18
year                    1998
population       1.06007e+06
state               Colorado
area (sq. mi)         104100
Name: 257, dtype: object
state/region              CO
ages                   total
year                    2000
population       4.32692e+06
state               Colorado
area (sq. mi)         104100
Name: 258, dtype: object
state/region              CO
ages                 under18
year                    2000
population       1.10668e+06
state               Colorado
area (sq. mi)         104100
Name: 259, dtype: object
state/region              CO
ages                   total
year                    1999
population       4.22602e+06
state               Colorado
area (sq. mi)         104100
Name: 260, dtype: object
state/region              CO
ages                 under18
year                    1999
population       1.08394e+06
state               Colorado
area (sq. mi)         104100
Name: 261, dtype: object
state/region              CO
ages                   total
year                    2002
population       4.49041e+06
state               Colorado
area (sq. mi)         104100
Name: 262, dtype: object
state/region              CO
ages                 under18
year                    2002
population       1.13827e+06
state               Colorado
area (sq. mi)         104100
Name: 263, dtype: object
state/region              CO
ages                   total
year                    2001
population       4.42569e+06
state               Colorado
area (sq. mi)         104100
Name: 264, dtype: object
state/region              CO
ages                 under18
year                    2001
population       1.12665e+06
state               Colorado
area (sq. mi)         104100
Name: 265, dtype: object
state/region              CO
ages                   total
year                    2004
population       4.57501e+06
state               Colorado
area (sq. mi)         104100
Name: 266, dtype: object
state/region              CO
ages                 under18
year                    2004
population       1.14637e+06
state               Colorado
area (sq. mi)         104100
Name: 267, dtype: object
state/region              CO
ages                   total
year                    2003
population       4.52873e+06
state               Colorado
area (sq. mi)         104100
Name: 268, dtype: object
state/region             CO
ages                under18
year                   2003
population       1.1446e+06
state              Colorado
area (sq. mi)        104100
Name: 269, dtype: object
state/region              CO
ages                   total
year                    2006
population       4.72042e+06
state               Colorado
area (sq. mi)         104100
Name: 270, dtype: object
state/region              CO
ages                 under18
year                    2006
population       1.17183e+06
state               Colorado
area (sq. mi)         104100
Name: 271, dtype: object
state/region              CO
ages                   total
year                    2005
population       4.63189e+06
state               Colorado
area (sq. mi)         104100
Name: 272, dtype: object
state/region             CO
ages                under18
year                   2005
population       1.1564e+06
state              Colorado
area (sq. mi)        104100
Name: 273, dtype: object
state/region              CO
ages                   total
year                    2008
population       4.88973e+06
state               Colorado
area (sq. mi)         104100
Name: 274, dtype: object
state/region              CO
ages                 under18
year                    2008
population       1.20329e+06
state               Colorado
area (sq. mi)         104100
Name: 275, dtype: object
state/region              CO
ages                   total
year                    2007
population       4.80387e+06
state               Colorado
area (sq. mi)         104100
Name: 276, dtype: object
state/region              CO
ages                 under18
year                    2007
population       1.18943e+06
state               Colorado
area (sq. mi)         104100
Name: 277, dtype: object
state/region             CO
ages                  total
year                   2009
population       4.9722e+06
state              Colorado
area (sq. mi)        104100
Name: 278, dtype: object
state/region              CO
ages                 under18
year                    2009
population       1.21721e+06
state               Colorado
area (sq. mi)         104100
Name: 279, dtype: object
state/region              CO
ages                 under18
year                    2013
population       1.23793e+06
state               Colorado
area (sq. mi)         104100
Name: 280, dtype: object
state/region              CO
ages                   total
year                    2013
population       5.26837e+06
state               Colorado
area (sq. mi)         104100
Name: 281, dtype: object
state/region              CO
ages                 under18
year                    2010
population       1.22662e+06
state               Colorado
area (sq. mi)         104100
Name: 282, dtype: object
state/region             CO
ages                  total
year                   2010
population       5.0482e+06
state              Colorado
area (sq. mi)        104100
Name: 283, dtype: object
state/region              CO
ages                 under18
year                    2011
population       1.23018e+06
state               Colorado
area (sq. mi)         104100
Name: 284, dtype: object
state/region             CO
ages                  total
year                   2011
population       5.1184e+06
state              Colorado
area (sq. mi)        104100
Name: 285, dtype: object
state/region              CO
ages                 under18
year                    2012
population       1.23286e+06
state               Colorado
area (sq. mi)         104100
Name: 286, dtype: object
state/region              CO
ages                   total
year                    2012
population       5.18946e+06
state               Colorado
area (sq. mi)         104100

Name: 287, dtype: object
state/region              CT
ages                 under18
year                    2012
population            794959
state            Connecticut
area (sq. mi)           5544
Name: 288, dtype: object
state/region              CT
ages                   total
year                    2012
population       3.59176e+06
state            Connecticut
area (sq. mi)           5544
Name: 289, dtype: object
state/region              CT
ages                 under18
year                    2011
population            805109
state            Connecticut
area (sq. mi)           5544
Name: 290, dtype: object
state/region              CT
ages                   total
year                    2011
population       3.58895e+06
state            Connecticut
area (sq. mi)           5544
Name: 291, dtype: object
state/region              CT
ages                 under18
year                    2010
population            814187
state            Connecticut
area (sq. mi)           5544
Name: 292, dtype: object
state/region              CT
ages                   total
year                    2010
population       3.57921e+06
state            Connecticut
area (sq. mi)           5544
Name: 293, dtype: object
state/region              CT
ages                 under18
year                    2013
population            785566
state            Connecticut
area (sq. mi)           5544
Name: 294, dtype: object
state/region              CT
ages                   total
year                    2013
population       3.59608e+06
state            Connecticut
area (sq. mi)           5544
Name: 295, dtype: object
state/region              CT
ages                   total
year                    2009
population       3.56181e+06
state            Connecticut
area (sq. mi)           5544
Name: 296, dtype: object
state/region              CT
ages                 under18
year                    2009
population            820839
state            Connecticut
area (sq. mi)           5544
Name: 297, dtype: object
state/region              CT
ages                   total
year                    2007
population       3.52727e+06
state            Connecticut
area (sq. mi)           5544
Name: 298, dtype: object
state/region              CT
ages                 under18
year                    2007
population            833484
state            Connecticut
area (sq. mi)           5544
Name: 299, dtype: object
state/region              CT
ages                   total
year                    2008
population       3.54558e+06
state            Connecticut
area (sq. mi)           5544
Name: 300, dtype: object
state/region              CT
ages                 under18
year                    2008
population            826626
state            Connecticut
area (sq. mi)           5544
Name: 301, dtype: object
state/region              CT
ages                   total
year                    2005
population       3.50696e+06
state            Connecticut
area (sq. mi)           5544
Name: 302, dtype: object
state/region              CT
ages                 under18
year                    2005
population            844034
state            Connecticut
area (sq. mi)           5544
Name: 303, dtype: object
state/region              CT
ages                   total
year                    2006
population       3.51746e+06
state            Connecticut
area (sq. mi)           5544
Name: 304, dtype: object
state/region              CT
ages                 under18
year                    2006
population            839372
state            Connecticut
area (sq. mi)           5544
Name: 305, dtype: object
state/region              CT
ages                   total
year                    2003
population       3.48434e+06
state            Connecticut
area (sq. mi)           5544
Name: 306, dtype: object
state/region              CT
ages                 under18
year                    2003
population            851115
state            Connecticut
area (sq. mi)           5544
Name: 307, dtype: object
state/region              CT
ages                   total
year                    2004
population       3.49609e+06
state            Connecticut
area (sq. mi)           5544
Name: 308, dtype: object
state/region              CT
ages                 under18
year                    2004
population            848979
state            Connecticut
area (sq. mi)           5544
Name: 309, dtype: object
state/region              CT
ages                   total
year                    2001
population       3.43284e+06
state            Connecticut
area (sq. mi)           5544
Name: 310, dtype: object
state/region              CT
ages                 under18
year                    2001
population            845850
state            Connecticut
area (sq. mi)           5544
Name: 311, dtype: object
state/region              CT
ages                   total
year                    2002
population       3.45875e+06
state            Connecticut
area (sq. mi)           5544
Name: 312, dtype: object
state/region              CT
ages                 under18
year                    2002
population            848877
state            Connecticut
area (sq. mi)           5544
Name: 313, dtype: object
state/region              CT
ages                   total
year                    1999
population        3.3864e+06
state            Connecticut
area (sq. mi)           5544
Name: 314, dtype: object
state/region              CT
ages                 under18
year                    1999
population            834654
state            Connecticut
area (sq. mi)           5544
Name: 315, dtype: object
state/region              CT
ages                   total
year                    2000
population       3.41178e+06
state            Connecticut
area (sq. mi)           5544
Name: 316, dtype: object
state/region              CT
ages                 under18
year                    2000
population            842242
state            Connecticut
area (sq. mi)           5544
Name: 317, dtype: object
state/region              CT
ages                 under18
year                    1998
population            824600
state            Connecticut
area (sq. mi)           5544
Name: 318, dtype: object
state/region              CT
ages                   total
year                    1998
population       3.36535e+06
state            Connecticut
area (sq. mi)           5544
Name: 319, dtype: object
state/region              CT
ages                   total
year                    1997
population       3.34935e+06
state            Connecticut
area (sq. mi)           5544
Name: 320, dtype: object
state/region              CT
ages                 under18
year                    1997
population            814373
state            Connecticut
area (sq. mi)           5544
Name: 321, dtype: object
state/region              CT
ages                 under18
year                    1996
population            811855
state            Connecticut
area (sq. mi)           5544
Name: 322, dtype: object
state/region              CT
ages                   total
year                    1996
population       3.33668e+06
state            Connecticut
area (sq. mi)           5544
Name: 323, dtype: object
state/region              CT
ages                   total
year                    1995
population       3.32414e+06
state            Connecticut
area (sq. mi)           5544
Name: 324, dtype: object
state/region              CT
ages                 under18
year                    1995
population            808623
state            Connecticut
area (sq. mi)           5544
Name: 325, dtype: object
state/region              CT
ages                   total
year                    1993
population       3.30918e+06
state            Connecticut
area (sq. mi)           5544
Name: 326, dtype: object
state/region              CT
ages                 under18
year                    1993
population            790749
state            Connecticut
area (sq. mi)           5544
Name: 327, dtype: object
state/region              CT
ages                 under18
year                    1994
population            801231
state            Connecticut
area (sq. mi)           5544
Name: 328, dtype: object
state/region              CT
ages                   total
year                    1994
population       3.31612e+06
state            Connecticut
area (sq. mi)           5544
Name: 329, dtype: object
state/region              CT
ages                 under18
year                    1991
population            766304
state            Connecticut
area (sq. mi)           5544
Name: 330, dtype: object
state/region              CT
ages                   total
year                    1991
population        3.3029e+06
state            Connecticut
area (sq. mi)           5544
Name: 331, dtype: object
state/region              CT
ages                 under18
year                    1992
population            777264
state            Connecticut
area (sq. mi)           5544
Name: 332, dtype: object
state/region              CT
ages                   total
year                    1992
population       3.30071e+06
state            Connecticut
area (sq. mi)           5544
Name: 333, dtype: object
state/region              CT
ages                   total
year                    1990
population       3.29197e+06
state            Connecticut
area (sq. mi)           5544
Name: 334, dtype: object
state/region              CT
ages                 under18
year                    1990
population            752666
state            Connecticut
area (sq. mi)           5544
Name: 335, dtype: object
state/region           DE
ages              under18
year                 1990
population         165628
state            Delaware
area (sq. mi)        1954
Name: 336, dtype: object
state/region           DE
ages                total
year                 1990
population         669567
state            Delaware
area (sq. mi)        1954
Name: 337, dtype: object
state/region           DE
ages              under18
year                 1992
population         174166
state            Delaware
area (sq. mi)        1954
Name: 338, dtype: object
state/region           DE
ages                total
year                 1992
population         694927
state            Delaware
area (sq. mi)        1954
Name: 339, dtype: object
state/region           DE
ages                total
year                 1991
population         683080
state            Delaware
area (sq. mi)        1954
Name: 340, dtype: object
state/region           DE
ages              under18
year                 1991
population         169910
state            Delaware
area (sq. mi)        1954
Name: 341, dtype: object
state/region           DE
ages                total
year                 1994
population         717545
state            Delaware
area (sq. mi)        1954
Name: 342, dtype: object
state/region           DE
ages              under18
year                 1994
population         180833
state            Delaware
area (sq. mi)        1954
Name: 343, dtype: object
state/region           DE
ages                total
year                 1993
population         706378
state            Delaware
area (sq. mi)        1954
Name: 344, dtype: object
state/region           DE
ages              under18
year                 1993
population         176916
state            Delaware
area (sq. mi)        1954
Name: 345, dtype: object
state/region           DE
ages              under18
year                 1995
population         181736
state            Delaware
area (sq. mi)        1954
Name: 346, dtype: object
state/region           DE
ages                total
year                 1995
population         729735
state            Delaware
area (sq. mi)        1954
Name: 347, dtype: object
state/region           DE
ages                total
year                 1996
population         740978
state            Delaware
area (sq. mi)        1954
Name: 348, dtype: object
state/region           DE
ages              under18
year                 1996
population         184021
state            Delaware
area (sq. mi)        1954
Name: 349, dtype: object
state/region           DE
ages              under18
year                 1997
population         186607
state            Delaware
area (sq. mi)        1954
Name: 350, dtype: object
state/region           DE
ages                total
year                 1997
population         751487
state            Delaware
area (sq. mi)        1954
Name: 351, dtype: object
state/region           DE
ages                total
year                 1998
population         763335
state            Delaware
area (sq. mi)        1954
Name: 352, dtype: object
state/region           DE
ages              under18
year                 1998
population         189302
state            Delaware
area (sq. mi)        1954
Name: 353, dtype: object
state/region           DE
ages                total
year                 2000
population         786373
state            Delaware
area (sq. mi)        1954
Name: 354, dtype: object
state/region           DE
ages              under18
year                 2000
population         194914
state            Delaware
area (sq. mi)        1954
Name: 355, dtype: object
state/region           DE
ages                total
year                 1999
population         774990
state            Delaware
area (sq. mi)        1954
Name: 356, dtype: object
state/region           DE
ages              under18
year                 1999
population         192510
state            Delaware
area (sq. mi)        1954

Name: 357, dtype: object
state/region           DE
ages                total
year                 2002
population         806169
state            Delaware
area (sq. mi)        1954
Name: 358, dtype: object
state/region           DE
ages              under18
year                 2002
population         196946
state            Delaware
area (sq. mi)        1954
Name: 359, dtype: object
state/region           DE
ages                total
year                 2001
population         795699
state            Delaware
area (sq. mi)        1954
Name: 360, dtype: object
state/region           DE
ages              under18
year                 2001
population         196038
state            Delaware
area (sq. mi)        1954
Name: 361, dtype: object
state/region           DE
ages                total
year                 2004
population         830803
state            Delaware
area (sq. mi)        1954
Name: 362, dtype: object
state/region           DE
ages              under18
year                 2004
population         199631
state            Delaware
area (sq. mi)        1954
Name: 363, dtype: object
state/region           DE
ages                total
year                 2003
population         818003
state            Delaware
area (sq. mi)        1954
Name: 364, dtype: object
state/region           DE
ages              under18
year                 2003
population         198045
state            Delaware
area (sq. mi)        1954
Name: 365, dtype: object
state/region           DE
ages                total
year                 2006
population         859268
state            Delaware
area (sq. mi)        1954
Name: 366, dtype: object
state/region           DE
ages              under18
year                 2006
population         203729
state            Delaware
area (sq. mi)        1954
Name: 367, dtype: object
state/region           DE
ages                total
year                 2005
population         845150
state            Delaware
area (sq. mi)        1954
Name: 368, dtype: object
state/region           DE
ages              under18
year                 2005
population         201988
state            Delaware
area (sq. mi)        1954
Name: 369, dtype: object
state/region           DE
ages                total
year                 2008
population         883874
state            Delaware
area (sq. mi)        1954
Name: 370, dtype: object
state/region           DE
ages              under18
year                 2008
population         206116
state            Delaware
area (sq. mi)        1954
Name: 371, dtype: object
state/region           DE
ages                total
year                 2007
population         871749
state            Delaware
area (sq. mi)        1954
Name: 372, dtype: object
state/region           DE
ages              under18
year                 2007
population         205155
state            Delaware
area (sq. mi)        1954
Name: 373, dtype: object
state/region           DE
ages              under18
year                 2013
population         203558
state            Delaware
area (sq. mi)        1954
Name: 374, dtype: object
state/region           DE
ages                total
year                 2013
population         925749
state            Delaware
area (sq. mi)        1954
Name: 375, dtype: object
state/region           DE
ages                total
year                 2009
population         891730
state            Delaware
area (sq. mi)        1954
Name: 376, dtype: object
state/region           DE
ages              under18
year                 2009
population         206213
state            Delaware
area (sq. mi)        1954
Name: 377, dtype: object
state/region           DE
ages              under18
year                 2010
population         205478
state            Delaware
area (sq. mi)        1954
Name: 378, dtype: object
state/region           DE
ages                total
year                 2010
population         899711
state            Delaware
area (sq. mi)        1954
Name: 379, dtype: object
state/region           DE
ages              under18
year                 2011
population         204801
state            Delaware
area (sq. mi)        1954
Name: 380, dtype: object
state/region           DE
ages                total
year                 2011
population         907985
state            Delaware
area (sq. mi)        1954
Name: 381, dtype: object
state/region           DE
ages              under18
year                 2012
population         204586
state            Delaware
area (sq. mi)        1954
Name: 382, dtype: object
state/region           DE
ages                total
year                 2012
population         917053
state            Delaware
area (sq. mi)        1954
Name: 383, dtype: object
state/region                       DC
ages                          under18
year                             2012
population                     107642
state            District of Columbia
area (sq. mi)                      68
Name: 384, dtype: object
state/region                       DC
ages                            total
year                             2012
population                     633427
state            District of Columbia
area (sq. mi)                      68
Name: 385, dtype: object
state/region                       DC
ages                          under18
year                             2011
population                     103906
state            District of Columbia
area (sq. mi)                      68
Name: 386, dtype: object
state/region                       DC
ages                            total
year                             2011
population                     619624
state            District of Columbia
area (sq. mi)                      68
Name: 387, dtype: object
state/region                       DC
ages                          under18
year                             2010
population                     101309
state            District of Columbia
area (sq. mi)                      68
Name: 388, dtype: object
state/region                       DC
ages                            total
year                             2010
population                     605125
state            District of Columbia
area (sq. mi)                      68
Name: 389, dtype: object
state/region                       DC
ages                          under18
year                             2013
population                     111474
state            District of Columbia
area (sq. mi)                      68
Name: 390, dtype: object
state/region                       DC
ages                            total
year                             2013
population                     646449
state            District of Columbia
area (sq. mi)                      68
Name: 391, dtype: object
state/region                       DC
ages                            total
year                             2009
population                     592228
state            District of Columbia
area (sq. mi)                      68
Name: 392, dtype: object
state/region                       DC
ages                          under18
year                             2009
population                     102098
state            District of Columbia
area (sq. mi)                      68
Name: 393, dtype: object
state/region                       DC
ages                            total
year                             2007
population                     574404
state            District of Columbia
area (sq. mi)                      68
Name: 394, dtype: object
state/region                       DC
ages                          under18
year                             2007
population                     104126
state            District of Columbia
area (sq. mi)                      68
Name: 395, dtype: object
state/region                       DC
ages                            total
year                             2008
population                     580236
state            District of Columbia
area (sq. mi)                      68
Name: 396, dtype: object
state/region                       DC
ages                          under18
year                             2008
population                     102257
state            District of Columbia
area (sq. mi)                      68
Name: 397, dtype: object
state/region                       DC
ages                            total
year                             2005
population                     567136
state            District of Columbia
area (sq. mi)                      68

Name: 398, dtype: object
state/region                       DC
ages                          under18
year                             2005
population                     107187
state            District of Columbia
area (sq. mi)                      68
Name: 399, dtype: object
state/region                       DC
ages                            total
year                             2006
population                     570681
state            District of Columbia
area (sq. mi)                      68
Name: 400, dtype: object
state/region                       DC
ages                          under18
year                             2006
population                     105651
state            District of Columbia
area (sq. mi)                      68
Name: 401, dtype: object
state/region                       DC
ages                            total
year                             2003
population                     568502
state            District of Columbia
area (sq. mi)                      68
Name: 402, dtype: object
state/region                       DC
ages                          under18
year                             2003
population                     111403
state            District of Columbia
area (sq. mi)                      68
Name: 403, dtype: object
state/region                       DC
ages                            total
year                             2004
population                     567754
state            District of Columbia
area (sq. mi)                      68
Name: 404, dtype: object
state/region                       DC
ages                          under18
year                             2004
population                     109756
state            District of Columbia
area (sq. mi)                      68
Name: 405, dtype: object
state/region                       DC
ages                            total
year                             2001
population                     574504
state            District of Columbia
area (sq. mi)                      68
Name: 406, dtype: object
state/region                       DC
ages                          under18
year                             2001
population                     114625
state            District of Columbia
area (sq. mi)                      68
Name: 407, dtype: object
state/region                       DC
ages                            total
year                             2002
population                     573158
state            District of Columbia
area (sq. mi)                      68
Name: 408, dtype: object
state/region                       DC
ages                          under18
year                             2002
population                     113822
state            District of Columbia
area (sq. mi)                      68
Name: 409, dtype: object
state/region                       DC
ages                            total
year                             1999
population                     570220
state            District of Columbia
area (sq. mi)                      68
Name: 410, dtype: object
state/region                       DC
ages                          under18
year                             1999
population                     115003
state            District of Columbia
area (sq. mi)                      68
Name: 411, dtype: object
state/region                       DC
ages                            total
year                             2000
population                     572046
state            District of Columbia
area (sq. mi)                      68
Name: 412, dtype: object
state/region                       DC
ages                          under18
year                             2000
population                     114503
state            District of Columbia
area (sq. mi)                      68
Name: 413, dtype: object
state/region                       DC
ages                          under18
year                             1998
population                     113839
state            District of Columbia
area (sq. mi)                      68
Name: 414, dtype: object
state/region                       DC
ages                            total
year                             1998
population                     565232
state            District of Columbia
area (sq. mi)                      68
Name: 415, dtype: object
state/region                       DC
ages                          under18
year                             1997
population                     119531
state            District of Columbia
area (sq. mi)                      68
Name: 416, dtype: object
state/region                       DC
ages                            total
year                             1997
population                     567739
state            District of Columbia
area (sq. mi)                      68
Name: 417, dtype: object
state/region                       DC
ages                          under18
year                             1996
population                     121210
state            District of Columbia
area (sq. mi)                      68
Name: 418, dtype: object
state/region                       DC
ages                            total
year                             1996
population                     572379
state            District of Columbia
area (sq. mi)                      68
Name: 419, dtype: object
state/region                       DC
ages                            total
year                             1995
population                     580519
state            District of Columbia
area (sq. mi)                      68
Name: 420, dtype: object
state/region                       DC
ages                          under18
year                             1995
population                     123620
state            District of Columbia
area (sq. mi)                      68
Name: 421, dtype: object
state/region                       DC
ages                            total
year                             1993
population                     595302
state            District of Columbia
area (sq. mi)                      68
Name: 422, dtype: object
state/region                       DC
ages                          under18
year                             1993
population                     120471
state            District of Columbia
area (sq. mi)                      68
Name: 423, dtype: object
state/region                       DC
ages                          under18
year                             1994
population                     122170
state            District of Columbia
area (sq. mi)                      68
Name: 424, dtype: object
state/region                       DC
ages                            total
year                             1994
population                     589240
state            District of Columbia
area (sq. mi)                      68
Name: 425, dtype: object
state/region                       DC
ages                            total
year                             1991
population                     600870
state            District of Columbia
area (sq. mi)                      68
Name: 426, dtype: object
state/region                       DC
ages                          under18
year                             1991
population                     116825
state            District of Columbia
area (sq. mi)                      68
Name: 427, dtype: object
state/region                       DC
ages                          under18
year                             1992
population                     118636
state            District of Columbia
area (sq. mi)                      68
Name: 428, dtype: object
state/region                       DC
ages                            total
year                             1992
population                     597567
state            District of Columbia
area (sq. mi)                      68
Name: 429, dtype: object
state/region                       DC
ages                          under18
year                             1990
population                     112632
state            District of Columbia
area (sq. mi)                      68
Name: 430, dtype: object
state/region                       DC
ages                            total
year                             1990
population                     605321
state            District of Columbia
area (sq. mi)                      68
Name: 431, dtype: object
state/region              FL
ages                   total
year                    1990
population       1.30333e+07
state                Florida
area (sq. mi)          65758
Name: 432, dtype: object
state/region              FL
ages                 under18
year                    1990
population       2.98881e+06
state                Florida
area (sq. mi)          65758
Name: 433, dtype: object
state/region              FL
ages                 under18
year                    1991
population       3.04564e+06
state                Florida
area (sq. mi)          65758
Name: 434, dtype: object
state/region              FL
ages                   total
year                    1991
population       1.33698e+07
state                Florida
area (sq. mi)          65758
Name: 435, dtype: object
state/region              FL
ages                   total
year                    1994
population       1.42394e+07
state                Florida
area (sq. mi)          65758
Name: 436, dtype: object
state/region              FL
ages                 under18
year                    1994
population       3.29989e+06
state                Florida
area (sq. mi)          65758
Name: 437, dtype: object
state/region              FL
ages                 under18
year                    1993
population       3.21407e+06
state                Florida
area (sq. mi)          65758
Name: 438, dtype: object

state/region              FL
ages                   total
year                    1993
population       1.39272e+07
state                Florida
area (sq. mi)          65758
Name: 439, dtype: object
state/region              FL
ages                   total
year                    1992
population       1.36506e+07
state                Florida
area (sq. mi)          65758
Name: 440, dtype: object
state/region              FL
ages                 under18
year                    1992
population       3.12044e+06
state                Florida
area (sq. mi)          65758
Name: 441, dtype: object
state/region              FL
ages                 under18
year                    1995
population       3.36647e+06
state                Florida
area (sq. mi)          65758
Name: 442, dtype: object
state/region              FL
ages                   total
year                    1995
population       1.45379e+07
state                Florida
area (sq. mi)          65758
Name: 443, dtype: object
state/region              FL
ages                   total
year                    1996
population       1.48534e+07
state                Florida
area (sq. mi)          65758
Name: 444, dtype: object
state/region             FL
ages                under18
year                   1996
population       3.4317e+06
state               Florida
area (sq. mi)         65758
Name: 445, dtype: object
state/region              FL
ages                 under18
year                    1998
population       3.55756e+06
state                Florida
area (sq. mi)          65758
Name: 446, dtype: object
state/region              FL
ages                 under18
year                    1997
population       3.50227e+06
state                Florida
area (sq. mi)          65758
Name: 447, dtype: object
state/region              FL
ages                   total
year                    1997
population       1.51863e+07
state                Florida
area (sq. mi)          65758
Name: 448, dtype: object
state/region              FL
ages                   total
year                    1998
population       1.54866e+07
state                Florida
area (sq. mi)          65758
Name: 449, dtype: object
state/region              FL
ages                   total
year                    1999
population       1.57594e+07
state                Florida
area (sq. mi)          65758
Name: 450, dtype: object
state/region              FL
ages                 under18
year                    1999
population       3.61171e+06
state                Florida
area (sq. mi)          65758
Name: 451, dtype: object
state/region              FL
ages                   total
year                    2000
population       1.60475e+07
state                Florida
area (sq. mi)          65758
Name: 452, dtype: object
state/region              FL
ages                 under18
year                    2000
population       3.65488e+06
state                Florida
area (sq. mi)          65758
Name: 453, dtype: object
state/region             FL
ages                  total
year                   2001
population       1.6357e+07
state               Florida
area (sq. mi)         65758
Name: 454, dtype: object
state/region              FL
ages                 under18
year                    2001
population       3.71444e+06
state                Florida
area (sq. mi)          65758
Name: 455, dtype: object
state/region              FL
ages                   total
year                    2002
population       1.66894e+07
state                Florida
area (sq. mi)          65758
Name: 456, dtype: object
state/region              FL
ages                 under18
year                    2002
population       3.77462e+06
state                Florida
area (sq. mi)          65758
Name: 457, dtype: object
state/region              FL
ages                   total
year                    2003
population       1.70041e+07
state                Florida
area (sq. mi)          65758
Name: 458, dtype: object
state/region              FL
ages                 under18
year                    2003
population       3.82088e+06
state                Florida
area (sq. mi)          65758
Name: 459, dtype: object
state/region              FL
ages                   total
year                    2004
population       1.74153e+07
state                Florida
area (sq. mi)          65758
Name: 460, dtype: object
state/region              FL
ages                 under18
year                    2004
population       3.89073e+06
state                Florida
area (sq. mi)          65758
Name: 461, dtype: object
state/region             FL
ages                  total
year                   2005
population       1.7842e+07
state               Florida
area (sq. mi)         65758
Name: 462, dtype: object
state/region              FL
ages                 under18
year                    2005
population       3.96818e+06
state                Florida
area (sq. mi)          65758
Name: 463, dtype: object
state/region             FL
ages                  total
year                   2006
population       1.8167e+07
state               Florida
area (sq. mi)         65758
Name: 464, dtype: object
state/region              FL
ages                 under18
year                    2006
population       4.02291e+06
state                Florida
area (sq. mi)          65758
Name: 465, dtype: object
state/region              FL
ages                   total
year                    2007
population       1.83678e+07
state                Florida
area (sq. mi)          65758
Name: 466, dtype: object
state/region             FL
ages                under18
year                   2007
population       4.0311e+06
state               Florida
area (sq. mi)         65758
Name: 467, dtype: object
state/region              FL
ages                   total
year                    2008
population       1.85273e+07
state                Florida
area (sq. mi)          65758
Name: 468, dtype: object
state/region              FL
ages                 under18
year                    2008
population       4.01837e+06
state                Florida
area (sq. mi)          65758
Name: 469, dtype: object
state/region              FL
ages                   total
year                    2009
population       1.86526e+07
state                Florida
area (sq. mi)          65758
Name: 470, dtype: object
state/region              FL
ages                 under18
year                    2009
population       3.99728e+06
state                Florida
area (sq. mi)          65758
Name: 471, dtype: object
state/region              FL
ages                 under18
year                    2013
population       4.02667e+06
state                Florida
area (sq. mi)          65758
Name: 472, dtype: object
state/region              FL
ages                   total
year                    2013
population       1.95529e+07
state                Florida
area (sq. mi)          65758
Name: 473, dtype: object
state/region              FL
ages                 under18
year                    2010
population       3.99953e+06
state                Florida
area (sq. mi)          65758
Name: 474, dtype: object
state/region              FL
ages                   total
year                    2010
population       1.88461e+07
state                Florida
area (sq. mi)          65758
Name: 475, dtype: object
state/region              FL
ages                 under18
year                    2011
population       4.00255e+06
state                Florida
area (sq. mi)          65758
Name: 476, dtype: object
state/region              FL
ages                   total
year                    2011
population       1.90835e+07
state                Florida
area (sq. mi)          65758
Name: 477, dtype: object
state/region              FL
ages                 under18
year                    2012
population       4.01242e+06
state                Florida
area (sq. mi)          65758
Name: 478, dtype: object
state/region              FL
ages                   total
year                    2012
population       1.93207e+07
state                Florida
area (sq. mi)          65758
Name: 479, dtype: object
state/region              GA
ages                   total
year                    2012
population       9.91565e+06
state                Georgia
area (sq. mi)          59441
Name: 480, dtype: object
state/region              GA
ages                 under18
year                    2012
population       2.48783e+06
state                Georgia
area (sq. mi)          59441
Name: 481, dtype: object
state/region             GA
ages                under18
year                   2011
population       2.4889e+06
state               Georgia
area (sq. mi)         59441
Name: 482, dtype: object
state/region              GA
ages                   total
year                    2011
population       9.81018e+06
state                Georgia
area (sq. mi)          59441
Name: 483, dtype: object
state/region              GA
ages                 under18
year                    2010
population       2.49088e+06
state                Georgia
area (sq. mi)          59441
Name: 484, dtype: object
state/region              GA
ages                   total
year                    2010
population       9.71325e+06
state                Georgia
area (sq. mi)          59441
Name: 485, dtype: object
state/region              GA
ages                   total
year                    2013
population       9.99217e+06
state                Georgia
area (sq. mi)          59441
Name: 486, dtype: object
state/region              GA
ages                   total
year                    2009
population       9.62085e+06
state                Georgia
area (sq. mi)          59441

Name: 487, dtype: object
state/region              GA
ages                 under18
year                    2009
population       2.48578e+06
state                Georgia
area (sq. mi)          59441
Name: 488, dtype: object
state/region              GA
ages                 under18
year                    2013
population       2.48971e+06
state                Georgia
area (sq. mi)          59441
Name: 489, dtype: object
state/region              GA
ages                   total
year                    2007
population       9.34999e+06
state                Georgia
area (sq. mi)          59441
Name: 490, dtype: object
state/region              GA
ages                 under18
year                    2007
population       2.45625e+06
state                Georgia
area (sq. mi)          59441
Name: 491, dtype: object
state/region              GA
ages                   total
year                    2008
population       9.50484e+06
state                Georgia
area (sq. mi)          59441
Name: 492, dtype: object
state/region             GA
ages                under18
year                   2008
population       2.4791e+06
state               Georgia
area (sq. mi)         59441
Name: 493, dtype: object
state/region              GA
ages                   total
year                    2005
population       8.92592e+06
state                Georgia
area (sq. mi)          59441
Name: 494, dtype: object
state/region             GA
ages                under18
year                   2005
population       2.3536e+06
state               Georgia
area (sq. mi)         59441
Name: 495, dtype: object
state/region              GA
ages                   total
year                    2006
population       9.15581e+06
state                Georgia
area (sq. mi)          59441
Name: 496, dtype: object
state/region              GA
ages                 under18
year                    2006
population       2.40601e+06
state                Georgia
area (sq. mi)          59441
Name: 497, dtype: object
state/region              GA
ages                   total
year                    2003
population       8.62279e+06
state                Georgia
area (sq. mi)          59441
Name: 498, dtype: object
state/region              GA
ages                 under18
year                    2003
population       2.27871e+06
state                Georgia
area (sq. mi)          59441
Name: 499, dtype: object
state/region              GA
ages                   total
year                    2004
population       8.76925e+06
state                Georgia
area (sq. mi)          59441
Name: 500, dtype: object
state/region              GA
ages                 under18
year                    2004
population       2.30886e+06
state                Georgia
area (sq. mi)          59441
Name: 501, dtype: object
state/region              GA
ages                   total
year                    2001
population       8.37704e+06
state                Georgia
area (sq. mi)          59441
Name: 502, dtype: object
state/region              GA
ages                 under18
year                    2001
population       2.21539e+06
state                Georgia
area (sq. mi)          59441
Name: 503, dtype: object
state/region              GA
ages                   total
year                    2002
population       8.50826e+06
state                Georgia
area (sq. mi)          59441
Name: 504, dtype: object
state/region              GA
ages                 under18
year                    2002
population       2.24978e+06
state                Georgia
area (sq. mi)          59441
Name: 505, dtype: object
state/region              GA
ages                   total
year                    1999
population       8.04596e+06
state                Georgia
area (sq. mi)          59441
Name: 506, dtype: object
state/region             GA
ages                under18
year                   1999
population       2.1307e+06
state               Georgia
area (sq. mi)         59441
Name: 507, dtype: object
state/region             GA
ages                  total
year                   2000
population       8.2273e+06
state               Georgia
area (sq. mi)         59441
Name: 508, dtype: object
state/region              GA
ages                 under18
year                    2000
population       2.17658e+06
state                Georgia
area (sq. mi)          59441
Name: 509, dtype: object
state/region             GA
ages                  total
year                   1997
population       7.6851e+06
state               Georgia
area (sq. mi)         59441
Name: 510, dtype: object
state/region              GA
ages                 under18
year                    1997
population       2.03416e+06
state                Georgia
area (sq. mi)          59441
Name: 511, dtype: object
state/region            GA
ages               under18
year                  1998
population       2.079e+06
state              Georgia
area (sq. mi)        59441
Name: 512, dtype: object
state/region              GA
ages                   total
year                    1998
population       7.86354e+06
state                Georgia
area (sq. mi)          59441
Name: 513, dtype: object
state/region              GA
ages                 under18
year                    1996
population       1.99317e+06
state                Georgia
area (sq. mi)          59441
Name: 514, dtype: object
state/region              GA
ages                   total
year                    1996
population       7.50107e+06
state                Georgia
area (sq. mi)          59441
Name: 515, dtype: object
state/region              GA
ages                   total
year                    1995
population       7.32841e+06
state                Georgia
area (sq. mi)          59441
Name: 516, dtype: object
state/region              GA
ages                 under18
year                    1995
population       1.94982e+06
state                Georgia
area (sq. mi)          59441
Name: 517, dtype: object
state/region              GA
ages                 under18
year                    1992
population       1.81778e+06
state                Georgia
area (sq. mi)          59441
Name: 518, dtype: object
state/region             GA
ages                  total
year                   1992
population       6.8172e+06
state               Georgia
area (sq. mi)         59441
Name: 519, dtype: object
state/region              GA
ages                   total
year                    1993
population       6.97824e+06
state                Georgia
area (sq. mi)          59441
Name: 520, dtype: object
state/region              GA
ages                 under18
year                    1993
population       1.86502e+06
state                Georgia
area (sq. mi)          59441
Name: 521, dtype: object
state/region              GA
ages                 under18
year                    1994
population       1.90654e+06
state                Georgia
area (sq. mi)          59441
Name: 522, dtype: object
state/region              GA
ages                   total
year                    1994
population       7.15716e+06
state                Georgia
area (sq. mi)          59441
Name: 523, dtype: object
state/region              GA
ages                   total
year                    1991
population       6.65300e+06
state                Georgia
area (sq. mi)          59441
Name: 524, dtype: object
state/region              GA
ages                 under18
year                    1991
population       1.77368e+06
state                Georgia
area (sq. mi)          59441
Name: 525, dtype: object
state/region              GA
ages                 under18
year                    1990
population       1.74736e+06
state                Georgia
area (sq. mi)          59441
Name: 526, dtype: object
state/region             GA
ages                  total
year                   1990
population       6.5126e+06
state               Georgia
area (sq. mi)         59441
Name: 527, dtype: object
state/region          HI
ages             under18
year                1990
population        279983
state             Hawaii
area (sq. mi)      10932
Name: 528, dtype: object
state/region              HI
ages                   total
year                    1990
population       1.11349e+06
state                 Hawaii
area (sq. mi)          10932
Name: 529, dtype: object
state/region              HI
ages                   total
year                    1991
population       1.13675e+06
state                 Hawaii
area (sq. mi)          10932
Name: 530, dtype: object
state/region          HI
ages             under18
year                1991
population        287871
state             Hawaii
area (sq. mi)      10932
Name: 531, dtype: object
state/region          HI
ages             under18
year                1994
population        307517
state             Hawaii
area (sq. mi)      10932
Name: 532, dtype: object
state/region              HI
ages                   total
year                    1994
population       1.18754e+06
state                 Hawaii
area (sq. mi)          10932
Name: 533, dtype: object
state/region              HI
ages                   total
year                    1993
population       1.17284e+06
state                 Hawaii
area (sq. mi)          10932
Name: 534, dtype: object
state/region          HI
ages             under18
year                1993
population        301473
state             Hawaii
area (sq. mi)      10932
Name: 535, dtype: object
state/region          HI
ages             under18
year                1992
population        295124
state             Hawaii
area (sq. mi)      10932
Name: 536, dtype: object
state/region              HI
ages                   total
year                    1992
population       1.15861e+06
state                 Hawaii
area (sq. mi)          10932
Name: 537, dtype: object
state/region              HI
ages                   total
year                    1995
population       1.19685e+06
state                 Hawaii
area (sq. mi)          10932
Name: 538, dtype: object
state/region          HI
ages             under18
year                1995
population        310325
state             Hawaii
area (sq. mi)      10932
Name: 539, dtype: object
state/region          HI
ages             under18
year                1996
population        311213
state             Hawaii
area (sq. mi)      10932
Name: 540, dtype: object
state/region              HI
ages                   total
year                    1996
population       1.20376e+06
state                 Hawaii
area (sq. mi)          10932
Name: 541, dtype: object
state/region          HI
ages             under18
year                1998
population        304576
state             Hawaii
area (sq. mi)      10932
Name: 542, dtype: object
state/region              HI
ages                   total
year                    1998
population       1.21523e+06
state                 Hawaii
area (sq. mi)          10932
Name: 543, dtype: object
state/region              HI
ages                   total
year                    1997
population       1.21164e+06
state                 Hawaii
area (sq. mi)          10932
Name: 544, dtype: object
state/region          HI
ages             under18
year                1997
population        309465
state             Hawaii
area (sq. mi)      10932
Name: 545, dtype: object
state/region              HI
ages                   total
year                    2000
population       1.21352e+06
state                 Hawaii
area (sq. mi)          10932
Name: 546, dtype: object
state/region          HI
ages             under18
year                2000
population        295352
state             Hawaii
area (sq. mi)      10932
Name: 547, dtype: object
state/region             HI
ages                  total
year                   1999
population       1.2103e+06
state                Hawaii
area (sq. mi)         10932
Name: 548, dtype: object
state/region          HI
ages             under18
year                1999
population        299680
state             Hawaii
area (sq. mi)      10932
Name: 549, dtype: object
state/region              HI
ages                   total
year                    2002
population       1.23961e+06
state                 Hawaii
area (sq. mi)          10932
Name: 550, dtype: object
state/region          HI
ages             under18
year                2002
population        293600
state             Hawaii
area (sq. mi)      10932
Name: 551, dtype: object
state/region              HI
ages                   total
year                    2001
population       1.22595e+06
state                 Hawaii
area (sq. mi)          10932
Name: 552, dtype: object
state/region          HI
ages             under18
year                2001
population        294133
state             Hawaii
area (sq. mi)      10932

Name: 553, dtype: object
state/region              HI
ages                   total
year                    2004
population       1.27357e+06
state                 Hawaii
area (sq. mi)          10932
Name: 554, dtype: object
state/region          HI
ages             under18
year                2004
population        298103
state             Hawaii
area (sq. mi)      10932
Name: 555, dtype: object
state/region              HI
ages                   total
year                    2003
population       1.25115e+06
state                 Hawaii
area (sq. mi)          10932
Name: 556, dtype: object
state/region          HI
ages             under18
year                2003
population        294519
state             Hawaii
area (sq. mi)      10932
Name: 557, dtype: object
state/region              HI
ages                   total
year                    2006
population       1.30973e+06
state                 Hawaii
area (sq. mi)          10932
Name: 558, dtype: object
state/region          HI
ages             under18
year                2006
population        299313
state             Hawaii
area (sq. mi)      10932
Name: 559, dtype: object
state/region              HI
ages                   total
year                    2005
population       1.29273e+06
state                 Hawaii
area (sq. mi)          10932
Name: 560, dtype: object
state/region          HI
ages             under18
year                2005
population        298497
state             Hawaii
area (sq. mi)      10932
Name: 561, dtype: object
state/region              HI
ages                   total
year                    2008
population       1.33221e+06
state                 Hawaii
area (sq. mi)          10932
Name: 562, dtype: object
state/region          HI
ages             under18
year                2008
population        301094
state             Hawaii
area (sq. mi)      10932
Name: 563, dtype: object
state/region              HI
ages                   total
year                    2007
population       1.31568e+06
state                 Hawaii
area (sq. mi)          10932
Name: 564, dtype: object
state/region          HI
ages             under18
year                2007
population        300207
state             Hawaii
area (sq. mi)      10932
Name: 565, dtype: object
state/region          HI
ages             under18
year                2013
population        307266
state             Hawaii
area (sq. mi)      10932
Name: 566, dtype: object
state/region              HI
ages                   total
year                    2009
population       1.34672e+06
state                 Hawaii
area (sq. mi)          10932
Name: 567, dtype: object
state/region          HI
ages             under18
year                2009
population        302796
state             Hawaii
area (sq. mi)      10932
Name: 568, dtype: object
state/region              HI
ages                   total
year                    2013
population       1.40405e+06
state                 Hawaii
area (sq. mi)          10932
Name: 569, dtype: object
state/region              HI
ages                   total
year                    2010
population       1.36373e+06
state                 Hawaii
area (sq. mi)          10932
Name: 570, dtype: object
state/region          HI
ages             under18
year                2010
population        303812
state             Hawaii
area (sq. mi)      10932
Name: 571, dtype: object
state/region             HI
ages                  total
year                   2011
population       1.3769e+06
state                Hawaii
area (sq. mi)         10932
Name: 572, dtype: object
state/region          HI
ages             under18
year                2011
population        305396
state             Hawaii
area (sq. mi)      10932
Name: 573, dtype: object
state/region          HI
ages             under18
year                2012
population        305981
state             Hawaii
area (sq. mi)      10932
Name: 574, dtype: object
state/region              HI
ages                   total
year                    2012
population       1.39009e+06
state                 Hawaii
area (sq. mi)          10932
Name: 575, dtype: object
state/region              ID
ages                   total
year                    2012
population       1.59559e+06
state                  Idaho
area (sq. mi)          83574
Name: 576, dtype: object
state/region          ID
ages             under18
year                2012
population        427177
state              Idaho
area (sq. mi)      83574
Name: 577, dtype: object
state/region          ID
ages             under18
year                2011
population        428535
state              Idaho
area (sq. mi)      83574
Name: 578, dtype: object
state/region              ID
ages                   total
year                    2011
population       1.58393e+06
state                  Idaho
area (sq. mi)          83574
Name: 579, dtype: object
state/region          ID
ages             under18
year                2010
population        428961
state              Idaho
area (sq. mi)      83574
Name: 580, dtype: object
state/region              ID
ages                   total
year                    2010
population       1.57072e+06
state                  Idaho
area (sq. mi)          83574
Name: 581, dtype: object
state/region              ID
ages                   total
year                    2013
population       1.61214e+06
state                  Idaho
area (sq. mi)          83574
Name: 582, dtype: object
state/region              ID
ages                   total
year                    2009
population       1.55444e+06
state                  Idaho
area (sq. mi)          83574
Name: 583, dtype: object
state/region          ID
ages             under18
year                2009
population        426076
state              Idaho
area (sq. mi)      83574
Name: 584, dtype: object
state/region          ID
ages             under18
year                2013
population        427781
state              Idaho
area (sq. mi)      83574
Name: 585, dtype: object
state/region              ID
ages                   total
year                    2007
population       1.50510e+06
state                  Idaho
area (sq. mi)          83574
Name: 586, dtype: object
state/region          ID
ages             under18
year                2007
population        415024
state              Idaho
area (sq. mi)      83574
Name: 587, dtype: object
state/region              ID
ages                   total
year                    2008
population       1.53432e+06
state                  Idaho
area (sq. mi)          83574
Name: 588, dtype: object
state/region          ID
ages             under18
year                2008
population        422347
state              Idaho
area (sq. mi)      83574
Name: 589, dtype: object
state/region              ID
ages                   total
year                    2005
population       1.42824e+06
state                  Idaho
area (sq. mi)          83574
Name: 590, dtype: object
state/region          ID
ages             under18
year                2005
population        394651
state              Idaho
area (sq. mi)      83574
Name: 591, dtype: object
state/region              ID
ages                   total
year                    2006
population       1.46867e+06
state                  Idaho
area (sq. mi)          83574
Name: 592, dtype: object
state/region          ID
ages             under18
year                2006
population        404753
state              Idaho
area (sq. mi)      83574
Name: 593, dtype: object
state/region              ID
ages                   total
year                    2003
population       1.36338e+06
state                  Idaho
area (sq. mi)          83574
Name: 594, dtype: object
state/region          ID
ages             under18
year                2003
population        379241
state              Idaho
area (sq. mi)      83574
Name: 595, dtype: object
state/region             ID
ages                  total
year                   2004
population       1.3918e+06
state                 Idaho
area (sq. mi)         83574
Name: 596, dtype: object
state/region          ID
ages             under18
year                2004
population        384692
state              Idaho
area (sq. mi)      83574
Name: 597, dtype: object
state/region              ID
ages                   total
year                    2001
population       1.31996e+06
state                  Idaho
area (sq. mi)          83574
Name: 598, dtype: object
state/region          ID
ages             under18
year                2001
population        373145
state              Idaho
area (sq. mi)      83574
Name: 599, dtype: object
state/region              ID
ages                   total
year                    2002
population       1.34037e+06
state                  Idaho
area (sq. mi)          83574
Name: 600, dtype: object
state/region          ID
ages             under18
year                2002
population        375986
state              Idaho
area (sq. mi)      83574
Name: 601, dtype: object
state/region              ID
ages                   total
year                    1999
population       1.27567e+06
state                  Idaho
area (sq. mi)          83574
Name: 602, dtype: object
state/region          ID
ages             under18
year                1999
population        366689
state              Idaho
area (sq. mi)      83574
Name: 603, dtype: object
state/region              ID
ages                   total
year                    2000
population       1.29943e+06
state                  Idaho
area (sq. mi)          83574
Name: 604, dtype: object
state/region          ID
ages             under18
year                2000
population        370430
state              Idaho
area (sq. mi)      83574
Name: 605, dtype: object
state/region              ID
ages                   total
year                    1997
population       1.22852e+06
state                  Idaho
area (sq. mi)          83574
Name: 606, dtype: object
state/region          ID
ages             under18
year                1997
population        357779
state              Idaho
area (sq. mi)      83574
Name: 607, dtype: object
state/region          ID
ages             under18
year                1998
population        362189
state              Idaho
area (sq. mi)      83574
Name: 608, dtype: object
state/region              ID
ages                   total
year                    1998
population       1.25233e+06
state                  Idaho
area (sq. mi)          83574
Name: 609, dtype: object
state/region          ID
ages             under18
year                1996
population        353824
state              Idaho
area (sq. mi)      83574
Name: 610, dtype: object
state/region              ID
ages                   total
year                    1996
population       1.20308e+06
state                  Idaho
area (sq. mi)          83574
Name: 611, dtype: object

state/region              ID
ages                   total
year                    1995
population       1.17732e+06
state                  Idaho
area (sq. mi)          83574
Name: 612, dtype: object
state/region          ID
ages             under18
year                1995
population        349248
state              Idaho
area (sq. mi)      83574
Name: 613, dtype: object
state/region          ID
ages             under18
year                1992
population        324972
state              Idaho
area (sq. mi)      83574
Name: 614, dtype: object
state/region              ID
ages                   total
year                    1992
population       1.07168e+06
state                  Idaho
area (sq. mi)          83574
Name: 615, dtype: object
state/region              ID
ages                   total
year                    1993
population       1.10877e+06
state                  Idaho
area (sq. mi)          83574
Name: 616, dtype: object
state/region          ID
ages             under18
year                1993
population        333838
state              Idaho
area (sq. mi)      83574
Name: 617, dtype: object
state/region          ID
ages             under18
year                1994
population        344242
state              Idaho
area (sq. mi)      83574
Name: 618, dtype: object
state/region              ID
ages                   total
year                    1994
population       1.14514e+06
state                  Idaho
area (sq. mi)          83574
Name: 619, dtype: object
state/region              ID
ages                   total
year                    1991
population       1.04132e+06
state                  Idaho
area (sq. mi)          83574
Name: 620, dtype: object
state/region          ID
ages             under18
year                1991
population        316732
state              Idaho
area (sq. mi)      83574
Name: 621, dtype: object
state/region          ID
ages             under18
year                1990
population        313373
state              Idaho
area (sq. mi)      83574
Name: 622, dtype: object
state/region              ID
ages                   total
year                    1990
population       1.01238e+06
state                  Idaho
area (sq. mi)          83574
Name: 623, dtype: object
state/region              IL
ages                 under18
year                    1990
population       2.94084e+06
state               Illinois
area (sq. mi)          57918
Name: 624, dtype: object
state/region              IL
ages                   total
year                    1990
population       1.14533e+07
state               Illinois
area (sq. mi)          57918
Name: 625, dtype: object
state/region             IL
ages                  total
year                   1991
population       1.1569e+07
state              Illinois
area (sq. mi)         57918
Name: 626, dtype: object
state/region              IL
ages                 under18
year                    1991
population       2.98872e+06
state               Illinois
area (sq. mi)          57918
Name: 627, dtype: object
state/region              IL
ages                 under18
year                    1994
population       3.11094e+06
state               Illinois
area (sq. mi)          57918
Name: 628, dtype: object
state/region              IL
ages                   total
year                    1994
population       1.19126e+07
state               Illinois
area (sq. mi)          57918
Name: 629, dtype: object
state/region              IL
ages                   total
year                    1993
population       1.18096e+07
state               Illinois
area (sq. mi)          57918
Name: 630, dtype: object
state/region              IL
ages                 under18
year                    1993
population       3.06654e+06
state               Illinois
area (sq. mi)          57918
Name: 631, dtype: object
state/region              IL
ages                 under18
year                    1992
population       3.03343e+06
state               Illinois
area (sq. mi)          57918
Name: 632, dtype: object
state/region              IL
ages                   total
year                    1992
population       1.16942e+07
state               Illinois
area (sq. mi)          57918
Name: 633, dtype: object
state/region              IL
ages                   total
year                    1995
population       1.20084e+07
state               Illinois
area (sq. mi)          57918
Name: 634, dtype: object
state/region              IL
ages                 under18
year                    1995
population       3.15298e+06
state               Illinois
area (sq. mi)          57918
Name: 635, dtype: object
state/region              IL
ages                 under18
year                    1996
population       3.19292e+06
state               Illinois
area (sq. mi)          57918
Name: 636, dtype: object
state/region             IL
ages                  total
year                   1996
population       1.2102e+07
state              Illinois
area (sq. mi)         57918
Name: 637, dtype: object
state/region              IL
ages                 under18
year                    1998
population       3.22525e+06
state               Illinois
area (sq. mi)          57918
Name: 638, dtype: object
state/region              IL
ages                   total
year                    1998
population       1.22718e+07
state               Illinois
area (sq. mi)          57918
Name: 639, dtype: object
state/region              IL
ages                   total
year                    1997
population       1.21857e+07
state               Illinois
area (sq. mi)          57918
Name: 640, dtype: object
state/region              IL
ages                 under18
year                    1997
population       3.22211e+06
state               Illinois
area (sq. mi)          57918
Name: 641, dtype: object
state/region              IL
ages                   total
year                    2000
population       1.24342e+07
state               Illinois
area (sq. mi)          57918
Name: 642, dtype: object
state/region              IL
ages                 under18
year                    2000
population       3.24494e+06
state               Illinois
area (sq. mi)          57918
Name: 643, dtype: object
state/region             IL
ages                  total
year                   1999
population       1.2359e+07
state              Illinois
area (sq. mi)         57918
Name: 644, dtype: object
state/region              IL
ages                 under18
year                    1999
population       3.24003e+06
state               Illinois
area (sq. mi)          57918
Name: 645, dtype: object
state/region              IL
ages                   total
year                    2002
population       1.25256e+07
state               Illinois
area (sq. mi)          57918
Name: 646, dtype: object
state/region              IL
ages                 under18
year                    2002
population       3.23836e+06
state               Illinois
area (sq. mi)          57918
Name: 647, dtype: object
state/region              IL
ages                   total
year                    2001
population       1.24884e+07
state               Illinois
area (sq. mi)          57918
Name: 648, dtype: object
state/region              IL
ages                 under18
year                    2001
population       3.24362e+06
state               Illinois
area (sq. mi)          57918
Name: 649, dtype: object
state/region              IL
ages                   total
year                    2004
population       1.25898e+07
state               Illinois
area (sq. mi)          57918
Name: 650, dtype: object
state/region             IL
ages                under18
year                   2004
population       3.2116e+06
state              Illinois
area (sq. mi)         57918
Name: 651, dtype: object
state/region             IL
ages                  total
year                   2003
population       1.2556e+07
state              Illinois
area (sq. mi)         57918
Name: 652, dtype: object
state/region              IL
ages                 under18
year                    2003
population       3.22555e+06
state               Illinois
area (sq. mi)          57918
Name: 653, dtype: object
state/region             IL
ages                  total
year                   2006
population       1.2644e+07
state              Illinois
area (sq. mi)         57918
Name: 654, dtype: object
state/region              IL
ages                 under18
year                    2006
population       3.18125e+06
state               Illinois
area (sq. mi)          57918
Name: 655, dtype: object
state/region              IL
ages                   total
year                    2005
population       1.26099e+07
state               Illinois
area (sq. mi)          57918
Name: 656, dtype: object
state/region              IL
ages                 under18
year                    2005
population       3.19732e+06
state               Illinois
area (sq. mi)          57918
Name: 657, dtype: object
state/region             IL
ages                  total
year                   2008
population       1.2747e+07
state              Illinois
area (sq. mi)         57918
Name: 658, dtype: object
state/region             IL
ages                under18
year                   2008
population       3.1534e+06
state              Illinois
area (sq. mi)         57918
Name: 659, dtype: object
state/region              IL
ages                   total
year                    2007
population       1.26959e+07
state               Illinois
area (sq. mi)          57918
Name: 660, dtype: object
state/region              IL
ages                 under18
year                    2007
population       3.17013e+06
state               Illinois
area (sq. mi)          57918
Name: 661, dtype: object
state/region              IL
ages                 under18
year                    2013
population       3.02331e+06
state               Illinois
area (sq. mi)          57918
Name: 662, dtype: object
state/region              IL
ages                   total
year                    2009
population       1.27968e+07
state               Illinois
area (sq. mi)          57918
Name: 663, dtype: object
state/region              IL
ages                 under18
year                    2009
population       3.13841e+06
state               Illinois
area (sq. mi)          57918
Name: 664, dtype: object
state/region              IL
ages                   total
year                    2013
population       1.28821e+07
state               Illinois
area (sq. mi)          57918
Name: 665, dtype: object
state/region              IL
ages                   total
year                    2010
population       1.28397e+07
state               Illinois
area (sq. mi)          57918
Name: 666, dtype: object
state/region              IL
ages                 under18
year                    2010
population       3.12209e+06
state               Illinois
area (sq. mi)          57918
Name: 667, dtype: object
state/region             IL
ages                  total
year                   2011
population       1.2856e+07
state              Illinois
area (sq. mi)         57918
Name: 668, dtype: object
state/region              IL
ages                 under18
year                    2011
population       3.08983e+06
state               Illinois
area (sq. mi)          57918
Name: 669, dtype: object
state/region              IL
ages                 under18
year                    2012
population       3.05704e+06
state               Illinois
area (sq. mi)          57918
Name: 670, dtype: object
state/region              IL
ages                   total
year                    2012
population       1.28682e+07
state               Illinois
area (sq. mi)          57918
Name: 671, dtype: object
state/region              IN
ages                   total
year                    2012
population       6.53778e+06
state                Indiana
area (sq. mi)          36420
Name: 672, dtype: object
state/region              IN
ages                 under18
year                    2012
population       1.58966e+06
state                Indiana
area (sq. mi)          36420
Name: 673, dtype: object
state/region              IN
ages                 under18
year                    2011
population       1.59809e+06
state                Indiana
area (sq. mi)          36420
Name: 674, dtype: object
state/region              IN
ages                   total
year                    2011
population       6.51634e+06
state                Indiana
area (sq. mi)          36420
Name: 675, dtype: object
state/region              IN
ages                 under18
year                    2010
population       1.60588e+06
state                Indiana
area (sq. mi)          36420
Name: 676, dtype: object
state/region              IN
ages                   total
year                    2010
population       6.48996e+06
state                Indiana
area (sq. mi)          36420
Name: 677, dtype: object
state/region             IN
ages                  total
year                   2013
population       6.5709e+06
state               Indiana
area (sq. mi)         36420
Name: 678, dtype: object
state/region              IN
ages                   total
year                    2009
population       6.45932e+06
state                Indiana
area (sq. mi)          36420
Name: 679, dtype: object
state/region             IN
ages                under18
year                   2009
population       1.6097e+06
state               Indiana
area (sq. mi)         36420
Name: 680, dtype: object
state/region              IN
ages                 under18
year                    2013
population       1.58603e+06
state                Indiana
area (sq. mi)          36420
Name: 681, dtype: object
state/region             IN
ages                  total
year                   2007
population       6.3796e+06
state               Indiana
area (sq. mi)         36420
Name: 682, dtype: object
state/region              IN
ages                 under18
year                    2007
population       1.60949e+06
state                Indiana
area (sq. mi)          36420
Name: 683, dtype: object
state/region              IN
ages                   total
year                    2008
population       6.42481e+06
state                Indiana
area (sq. mi)          36420
Name: 684, dtype: object
state/region              IN
ages                 under18
year                    2008
population       1.61149e+06
state                Indiana
area (sq. mi)          36420
Name: 685, dtype: object
state/region              IN
ages                   total
year                    2005
population       6.27862e+06
state                Indiana
area (sq. mi)          36420
Name: 686, dtype: object
state/region             IN
ages                under18
year                   2005
population       1.5939e+06
state               Indiana
area (sq. mi)         36420
Name: 687, dtype: object
state/region              IN
ages                   total
year                    2006
population       6.33267e+06
state                Indiana
area (sq. mi)          36420
Name: 688, dtype: object
state/region              IN
ages                 under18
year                    2006
population       1.60311e+06
state                Indiana
area (sq. mi)          36420
Name: 689, dtype: object
state/region              IN
ages                   total
year                    2003
population       6.19664e+06
state                Indiana
area (sq. mi)          36420
Name: 690, dtype: object
state/region              IN
ages                 under18
year                    2003
population       1.58256e+06
state                Indiana
area (sq. mi)          36420
Name: 691, dtype: object
state/region              IN
ages                   total
year                    2004
population       6.23301e+06
state                Indiana
area (sq. mi)          36420
Name: 692, dtype: object
state/region              IN
ages                 under18
year                    2004
population       1.58628e+06
state                Indiana
area (sq. mi)          36420
Name: 693, dtype: object
state/region              IN
ages                   total
year                    2001
population       6.12776e+06
state                Indiana
area (sq. mi)          36420
Name: 694, dtype: object
state/region              IN
ages                 under18
year                    2001
population       1.57953e+06
state                Indiana
area (sq. mi)          36420
Name: 695, dtype: object
state/region              IN
ages                   total
year                    2002
population       6.15597e+06
state                Indiana
area (sq. mi)          36420
Name: 696, dtype: object
state/region              IN
ages                 under18
year                    2002
population       1.58081e+06
state                Indiana
area (sq. mi)          36420
Name: 697, dtype: object
state/region              IN
ages                   total
year                    1999
population       6.04497e+06
state                Indiana
area (sq. mi)          36420
Name: 698, dtype: object
state/region              IN
ages                 under18
year                    1999
population       1.56608e+06
state                Indiana
area (sq. mi)          36420
Name: 699, dtype: object
state/region              IN
ages                   total
year                    2000
population       6.09187e+06
state                Indiana
area (sq. mi)          36420
Name: 700, dtype: object
state/region              IN
ages                 under18
year                    2000
population       1.57499e+06
state                Indiana
area (sq. mi)          36420
Name: 701, dtype: object
state/region              IN
ages                   total
year                    1997
population       5.95527e+06
state                Indiana
area (sq. mi)          36420
Name: 702, dtype: object
state/region              IN
ages                 under18
year                    1997
population       1.53927e+06
state                Indiana
area (sq. mi)          36420
Name: 703, dtype: object
state/region              IN
ages                 under18
year                    1998
population       1.55196e+06
state                Indiana
area (sq. mi)          36420
Name: 704, dtype: object
state/region              IN
ages                   total
year                    1998
population       5.99888e+06
state                Indiana
area (sq. mi)          36420
Name: 705, dtype: object
state/region              IN
ages                 under18
year                    1996
population       1.51796e+06
state                Indiana
area (sq. mi)          36420
Name: 706, dtype: object
state/region              IN
ages                   total
year                    1996
population       5.90601e+06
state                Indiana
area (sq. mi)          36420
Name: 707, dtype: object
state/region              IN
ages                   total
year                    1995
population       5.85146e+06
state                Indiana
area (sq. mi)          36420
Name: 708, dtype: object
state/region              IN
ages                 under18
year                    1995
population       1.50792e+06
state                Indiana
area (sq. mi)          36420
Name: 709, dtype: object
state/region              IN
ages                 under18
year                    1992
population       1.46165e+06
state                Indiana
area (sq. mi)          36420
Name: 710, dtype: object
state/region              IN
ages                   total
year                    1992
population       5.67455e+06
state                Indiana
area (sq. mi)          36420
Name: 711, dtype: object
state/region              IN
ages                   total
year                    1993
population       5.73902e+06
state                Indiana
area (sq. mi)          36420
Name: 712, dtype: object
state/region              IN
ages                 under18
year                    1993
population       1.47301e+06

Name: 732, dtype: object
state/region           IA
ages                total
year                 1996
population       2.88e+06
state                Iowa
area (sq. mi)       56276
Name: 733, dtype: object
state/region          IA
ages             under18
year                1998
population        729943
state               Iowa
area (sq. mi)      56276
Name: 734, dtype: object
state/region              IA
ages                   total
year                    1998
population       2.90287e+06
state                   Iowa
area (sq. mi)          56276
Name: 735, dtype: object
state/region              IA
ages                   total
year                    1997
population       2.89112e+06
state                   Iowa
area (sq. mi)          56276
Name: 736, dtype: object
state/region          IA
ages             under18
year                1997
population        729806
state               Iowa
area (sq. mi)      56276
Name: 737, dtype: object
state/region              IA
ages                   total
year                    2000
population       2.92907e+06
state                   Iowa
area (sq. mi)          56276
Name: 738, dtype: object
state/region          IA
ages             under18
year                2000
population        733337
state               Iowa
area (sq. mi)      56276
Name: 739, dtype: object
state/region              IA
ages                   total
year                    1999
population       2.91763e+06
state                   Iowa
area (sq. mi)          56276
Name: 740, dtype: object
state/region          IA
ages             under18
year                1999
population        732671
state               Iowa
area (sq. mi)      56276
Name: 741, dtype: object
state/region              IA
ages                   total
year                    2002
population       2.93423e+06
state                   Iowa
area (sq. mi)          56276
Name: 742, dtype: object
state/region          IA
ages             under18
year                2002
population        723685
state               Iowa
area (sq. mi)      56276
Name: 743, dtype: object
state/region            IA
ages                 total
year                  2001
population       2.932e+06
state                 Iowa
area (sq. mi)        56276
Name: 744, dtype: object
state/region          IA
ages             under18
year                2001
population        728601
state               Iowa
area (sq. mi)      56276
Name: 745, dtype: object
state/region              IA
ages                   total
year                    2004
population       2.95364e+06
state                   Iowa
area (sq. mi)          56276
Name: 746, dtype: object
state/region          IA
ages             under18
year                2004
population        718708
state               Iowa
area (sq. mi)      56276
Name: 747, dtype: object
state/region            IA
ages                 total
year                  2003
population       2.942e+06
state                 Iowa
area (sq. mi)        56276
Name: 748, dtype: object
state/region          IA
ages             under18
year                2003
population        720102
state               Iowa
area (sq. mi)      56276
Name: 749, dtype: object
state/region              IA
ages                   total
year                    2006
population       2.98264e+06
state                   Iowa
area (sq. mi)          56276
Name: 750, dtype: object
state/region          IA
ages             under18
year                2006
population        721703
state               Iowa
area (sq. mi)      56276
Name: 751, dtype: object
state/region              IA
ages                   total
year                    2005
population       2.96445e+06
state                   Iowa
area (sq. mi)          56276
Name: 752, dtype: object
state/region          IA
ages             under18
year                2005
population        718488
state               Iowa
area (sq. mi)      56276
Name: 753, dtype: object
state/region              IA
ages                   total
year                    2008
population       3.01673e+06
state                   Iowa
area (sq. mi)          56276
Name: 754, dtype: object
state/region          IA
ages             under18
year                2008
population        725658
state               Iowa
area (sq. mi)      56276
Name: 755, dtype: object
state/region              IA
ages                   total
year                    2007
population       2.99921e+06
state                   Iowa
area (sq. mi)          56276
Name: 756, dtype: object
state/region          IA
ages             under18
year                2007
population        723632
state               Iowa
area (sq. mi)      56276
Name: 757, dtype: object
state/region          IA
ages             under18
year                2013
population        724032
state               Iowa
area (sq. mi)      56276
Name: 758, dtype: object
state/region              IA
ages                   total
year                    2009
population       3.03287e+06
state                   Iowa
area (sq. mi)          56276
Name: 759, dtype: object
state/region          IA
ages             under18
year                2009
population        726969
state               Iowa
area (sq. mi)      56276
Name: 760, dtype: object
state/region              IA
ages                   total
year                    2013
population       3.09042e+06
state                   Iowa
area (sq. mi)          56276
Name: 761, dtype: object
state/region              IA
ages                   total
year                    2010
population       3.05031e+06
state                   Iowa
area (sq. mi)          56276
Name: 762, dtype: object
state/region          IA
ages             under18
year                2010
population        727717
state               Iowa
area (sq. mi)      56276
Name: 763, dtype: object
state/region             IA
ages                  total
year                   2011
population       3.0641e+06
state                  Iowa
area (sq. mi)         56276
Name: 764, dtype: object
state/region          IA
ages             under18
year                2011
population        725522
state               Iowa
area (sq. mi)      56276
Name: 765, dtype: object
state/region          IA
ages             under18
year                2012
population        723917
state               Iowa
area (sq. mi)      56276
Name: 766, dtype: object
state/region              IA
ages                   total
year                    2012
population       3.07504e+06
state                   Iowa
area (sq. mi)          56276
Name: 767, dtype: object
state/region             KS
ages                  total
year                   2012
population       2.8854e+06
state                Kansas
area (sq. mi)         82282
Name: 768, dtype: object
state/region          KS
ages             under18
year                2012
population        726668
state             Kansas
area (sq. mi)      82282
Name: 769, dtype: object
state/region          KS
ages             under18
year                2011
population        726787
state             Kansas
area (sq. mi)      82282
Name: 770, dtype: object
state/region              KS
ages                   total
year                    2011
population       2.86955e+06
state                 Kansas
area (sq. mi)          82282
Name: 771, dtype: object
state/region          KS
ages             under18
year                2010
population        727729
state             Kansas
area (sq. mi)      82282
Name: 772, dtype: object
state/region              KS
ages                   total
year                    2010
population       2.85891e+06
state                 Kansas
area (sq. mi)          82282
Name: 773, dtype: object
state/region              KS
ages                   total
year                    2013
population       2.89396e+06
state                 Kansas
area (sq. mi)          82282
Name: 774, dtype: object
state/region             KS
ages                  total
year                   2009
population       2.8327e+06
state                Kansas
area (sq. mi)         82282
Name: 775, dtype: object
state/region          KS
ages             under18
year                2009
population        721841
state             Kansas
area (sq. mi)      82282
Name: 776, dtype: object
state/region          KS
ages             under18
year                2013
population        724092
state             Kansas
area (sq. mi)      82282
Name: 777, dtype: object
state/region              KS
ages                   total
year                    2007
population       2.78378e+06
state                 Kansas
area (sq. mi)          82282
Name: 778, dtype: object
state/region          KS
ages             under18
year                2007
population        711005
state             Kansas
area (sq. mi)      82282
Name: 779, dtype: object
state/region              KS
ages                   total
year                    2008
population       2.80808e+06
state                 Kansas
area (sq. mi)          82282
Name: 780, dtype: object
state/region          KS
ages             under18
year                2008
population        714689
state             Kansas
area (sq. mi)      82282
Name: 781, dtype: object
state/region             KS
ages                  total
year                   2005
population       2.7453e+06
state                Kansas
area (sq. mi)         82282
Name: 782, dtype: object
state/region          KS
ages             under18
year                2005
population        704689
state             Kansas
area (sq. mi)      82282
Name: 783, dtype: object
state/region              KS
ages                   total
year                    2006
population       2.76293e+06
state                 Kansas
area (sq. mi)          82282
Name: 784, dtype: object
state/region          KS
ages             under18
year                2006
population        705277
state             Kansas
area (sq. mi)      82282
Name: 785, dtype: object
state/region            KS
ages                 total
year                  2003
population       2.723e+06
state               Kansas
area (sq. mi)        82282
Name: 786, dtype: object
state/region          KS
ages             under18
year                2003
population        707847
state             Kansas
area (sq. mi)      82282
Name: 787, dtype: object
state/region              KS
ages                   total
year                    2004
population       2.73437e+06
state                 Kansas
area (sq. mi)          82282
Name: 788, dtype: object
state/region          KS
ages             under18
year                2004
population        705456
state             Kansas
area (sq. mi)      82282
Name: 789, dtype: object
state/region              KS
ages                   total
year                    2001
population       2.70216e+06
state                 Kansas
area (sq. mi)          82282
Name: 790, dtype: object
state/region          KS
ages             under18
year                2001
population        710923
state             Kansas
area (sq. mi)      82282
Name: 791, dtype: object
state/region              KS
ages                   total
year                    2002
population       2.71354e+06
state                 Kansas
area (sq. mi)          82282
Name: 792, dtype: object
state/region          KS
ages             under18
year                2002
population        709416
state             Kansas
area (sq. mi)      82282
Name: 793, dtype: object
state/region              KS
ages                   total
year                    1999
population       2.67834e+06
state                 Kansas
area (sq. mi)          82282
Name: 794, dtype: object
state/region          KS
ages             under18
year                1999
population        713022
state             Kansas
area (sq. mi)      82282
Name: 795, dtype: object
state/region              KS
ages                   total
year                    2000
population       2.69368e+06
state                 Kansas
area (sq. mi)          82282
Name: 796, dtype: object
state/region          KS
ages             under18
year                2000
population        713887
state             Kansas
area (sq. mi)      82282
Name: 797, dtype: object
state/region              KS
ages                   total
year                    1997
population       2.63529e+06
state                 Kansas
area (sq. mi)          82282
Name: 798, dtype: object
state/region          KS
ages             under18
year                1997
population        704001
state             Kansas
area (sq. mi)      82282
Name: 799, dtype: object
state/region          KS
ages             under18
year                1998
population        710402
state             Kansas
area (sq. mi)      82282
Name: 800, dtype: object
state/region             KS
ages                  total
year                   1998
population       2.6606e+06
state                Kansas
area (sq. mi)         82282
Name: 801, dtype: object
state/region          KS
ages             under18
year                1996
population        696298
state             Kansas
area (sq. mi)      82282
Name: 802, dtype: object
state/region              KS
ages                   total
year                    1996
population       2.61455e+06
state                 Kansas
area (sq. mi)          82282
Name: 803, dtype: object
state/region              KS
ages                   total
year                    1995
population       2.60101e+06
state                 Kansas
area (sq. mi)          82282
Name: 804, dtype: object
state/region          KS
ages             under18
year                1995
population        694124
state             Kansas
area (sq. mi)      82282
Name: 805, dtype: object
state/region          KS
ages             under18
year                1992
population        680871
state             Kansas
area (sq. mi)      82282
Name: 806, dtype: object
state/region             KS
ages                  total
year                   1992
population       2.5324e+06
state                Kansas
area (sq. mi)         82282
Name: 807, dtype: object
state/region              KS
ages                   total
year                    1993
population       2.55655e+06
state                 Kansas
area (sq. mi)          82282
Name: 808, dtype: object
state/region          KS
ages             under18
year                1993
population        687262
state             Kansas
area (sq. mi)      82282
Name: 809, dtype: object
state/region          KS
ages             under18
year                1994
population        693673
state             Kansas
area (sq. mi)      82282
Name: 810, dtype: object
state/region              KS
ages                   total
year                    1994
population       2.58051e+06
state                 Kansas
area (sq. mi)          82282
Name: 811, dtype: object
state/region              KS
ages                   total
year                    1991
population       2.49872e+06
state                 Kansas
area (sq. mi)          82282
Name: 812, dtype: object
state/region          KS
ages             under18
year                1991
population        672033
state             Kansas
area (sq. mi)      82282
Name: 813, dtype: object
state/region          KS
ages             under18
year                1990
population        662641
state             Kansas
area (sq. mi)      82282
Name: 814, dtype: object
state/region              KS
ages                   total
year                    1990
population       2.48135e+06
state                 Kansas
area (sq. mi)          82282
Name: 815, dtype: object
state/region           KY
ages              under18
year                 1990
population         945951
state            Kentucky
area (sq. mi)       40411
Name: 816, dtype: object
state/region              KY
ages                   total
year                    1990
population       3.69405e+06
state               Kentucky
area (sq. mi)          40411
Name: 817, dtype: object
state/region              KY
ages                   total
year                    1991
population       3.72233e+06
state               Kentucky
area (sq. mi)          40411
Name: 818, dtype: object
state/region           KY
ages              under18
year                 1991
population         951512
state            Kentucky
area (sq. mi)       40411
Name: 819, dtype: object
state/region           KY
ages              under18
year                 1994
population         981439
state            Kentucky
area (sq. mi)       40411
Name: 820, dtype: object
state/region              KY
ages                   total
year                    1994
population       3.84909e+06
state               Kentucky
area (sq. mi)          40411
Name: 821, dtype: object
state/region              KY
ages                   total
year                    1993
population       3.81221e+06
state               Kentucky
area (sq. mi)          40411
Name: 822, dtype: object
state/region           KY
ages              under18
year                 1993
population         971134
state            Kentucky
area (sq. mi)       40411
Name: 823, dtype: object
state/region           KY
ages              under18
year                 1992
population         963861
state            Kentucky
area (sq. mi)       40411
Name: 824, dtype: object
state/region              KY
ages                   total
year                    1992
population       3.76547e+06
state               Kentucky
area (sq. mi)          40411
Name: 825, dtype: object
state/region              KY
ages                   total
year                    1995
population       3.88743e+06
state               Kentucky
area (sq. mi)          40411
Name: 826, dtype: object
state/region           KY
ages              under18
year                 1995
population         984486
state            Kentucky
area (sq. mi)       40411
Name: 827, dtype: object
state/region           KY
ages              under18
year                 1996
population         987062
state            Kentucky
area (sq. mi)       40411
Name: 828, dtype: object
state/region              KY
ages                   total
year                    1996
population       3.91954e+06
state               Kentucky
area (sq. mi)          40411
Name: 829, dtype: object
state/region           KY
ages              under18
year                 1998
population         997296
state            Kentucky
area (sq. mi)       40411
Name: 830, dtype: object
state/region              KY
ages                   total
year                    1998
population       3.98539e+06
state               Kentucky
area (sq. mi)          40411
Name: 831, dtype: object
state/region              KY
ages                   total
year                    1997
population       3.95275e+06
state               Kentucky
area (sq. mi)          40411
Name: 832, dtype: object
state/region              KY
ages                 under18
year                    1997
population       1.00261e+06
state               Kentucky
area (sq. mi)          40411
Name: 833, dtype: object
state/region              KY
ages                   total
year                    2000
population       4.04902e+06
state               Kentucky
area (sq. mi)          40411
Name: 834, dtype: object
state/region           KY
ages              under18
year                 2000
population         994984
state            Kentucky
area (sq. mi)       40411
Name: 835, dtype: object
state/region              KY
ages                   total
year                    1999
population       4.01805e+06
state               Kentucky
area (sq. mi)          40411
Name: 836, dtype: object
state/region           KY
ages              under18
year                 1999
population         996382
state            Kentucky
area (sq. mi)       40411
Name: 837, dtype: object
state/region              KY
ages                   total
year                    2002
population       4.08988e+06
state               Kentucky
area (sq. mi)          40411
Name: 838, dtype: object
state/region           KY
ages              under18
year                 2002
population         995251
state            Kentucky

Name: 846, dtype: object
state/region             KY
ages                under18
year                   2006
population       1.0113e+06
state              Kentucky
area (sq. mi)         40411
Name: 847, dtype: object
state/region              KY
ages                   total
year                    2005
population       4.18274e+06
state               Kentucky
area (sq. mi)          40411
Name: 848, dtype: object
state/region              KY
ages                 under18
year                    2005
population       1.00402e+06
state               Kentucky
area (sq. mi)          40411
Name: 849, dtype: object
state/region              KY
ages                   total
year                    2008
population       4.28988e+06
state               Kentucky
area (sq. mi)          40411
Name: 850, dtype: object
state/region            KY
ages               under18
year                  2008
population       1.022e+06
state             Kentucky
area (sq. mi)        40411
Name: 851, dtype: object
state/region              KY
ages                   total
year                    2007
population       4.25667e+06
state               Kentucky
area (sq. mi)          40411
Name: 852, dtype: object
state/region              KY
ages                 under18
year                    2007
population       1.01629e+06
state               Kentucky
area (sq. mi)          40411
Name: 853, dtype: object
state/region            KY
ages               under18
year                  2013
population       1.014e+06
state             Kentucky
area (sq. mi)        40411
Name: 854, dtype: object
state/region              KY
ages                   total
year                    2009
population       4.31707e+06
state               Kentucky
area (sq. mi)          40411
Name: 855, dtype: object
state/region              KY
ages                 under18
year                    2009
population       1.02171e+06
state               Kentucky
area (sq. mi)          40411
Name: 856, dtype: object
state/region             KY
ages                  total
year                   2013
population       4.3953e+06
state              Kentucky
area (sq. mi)         40411
Name: 857, dtype: object
state/region             KY
ages                  total
year                   2010
population       4.3477e+06
state              Kentucky
area (sq. mi)         40411
Name: 858, dtype: object
state/region              KY
ages                 under18
year                    2010
population       1.02368e+06
state               Kentucky
area (sq. mi)          40411
Name: 859, dtype: object
state/region              KY
ages                   total
year                    2011
population       4.36687e+06
state               Kentucky
area (sq. mi)          40411
Name: 860, dtype: object
state/region              KY
ages                 under18
year                    2011
population       1.02193e+06
state               Kentucky
area (sq. mi)          40411
Name: 861, dtype: object
state/region              KY
ages                 under18
year                    2012
population       1.01735e+06
state               Kentucky
area (sq. mi)          40411
Name: 862, dtype: object
state/region              KY
ages                   total
year                    2012
population       4.37973e+06
state               Kentucky
area (sq. mi)          40411
Name: 863, dtype: object
state/region              LA
ages                   total
year                    2012
population       4.60213e+06
state              Louisiana
area (sq. mi)          51843
Name: 864, dtype: object
state/region              LA
ages                 under18
year                    2012
population       1.11462e+06
state              Louisiana
area (sq. mi)          51843
Name: 865, dtype: object
state/region              LA
ages                 under18
year                    2011
population       1.11658e+06
state              Louisiana
area (sq. mi)          51843
Name: 866, dtype: object
state/region             LA
ages                  total
year                   2011
population       4.5752e+06
state             Louisiana
area (sq. mi)         51843
Name: 867, dtype: object
state/region              LA
ages                 under18
year                    2010
population       1.11858e+06
state              Louisiana
area (sq. mi)          51843
Name: 868, dtype: object
state/region              LA
ages                   total
year                    2010
population       4.54539e+06
state              Louisiana
area (sq. mi)          51843
Name: 869, dtype: object
state/region              LA
ages                   total
year                    2013
population       4.62547e+06
state              Louisiana
area (sq. mi)          51843
Name: 870, dtype: object
state/region              LA
ages                   total
year                    2009
population       4.49165e+06
state              Louisiana
area (sq. mi)          51843
Name: 871, dtype: object
state/region              LA
ages                 under18
year                    2009
population       1.11423e+06
state              Louisiana
area (sq. mi)          51843
Name: 872, dtype: object
state/region              LA
ages                 under18
year                    2013
population       1.11296e+06
state              Louisiana
area (sq. mi)          51843
Name: 873, dtype: object
state/region              LA
ages                   total
year                    2007
population       4.37558e+06
state              Louisiana
area (sq. mi)          51843
Name: 874, dtype: object
state/region              LA
ages                 under18
year                    2007
population       1.09664e+06
state              Louisiana
area (sq. mi)          51843
Name: 875, dtype: object
state/region              LA
ages                   total
year                    2008
population       4.43559e+06
state              Louisiana
area (sq. mi)          51843
Name: 876, dtype: object
state/region              LA
ages                 under18
year                    2008
population       1.10873e+06
state              Louisiana
area (sq. mi)          51843
Name: 877, dtype: object
state/region              LA
ages                   total
year                    2005
population       4.57663e+06
state              Louisiana
area (sq. mi)          51843
Name: 878, dtype: object
state/region              LA
ages                 under18
year                    2005
population       1.17795e+06
state              Louisiana
area (sq. mi)          51843
Name: 879, dtype: object
state/region              LA
ages                   total
year                    2006
population       4.30266e+06
state              Louisiana
area (sq. mi)          51843
Name: 880, dtype: object
state/region              LA
ages                 under18
year                    2006
population       1.07878e+06
state              Louisiana
area (sq. mi)          51843
Name: 881, dtype: object
state/region              LA
ages                   total
year                    2003
population       4.52104e+06
state              Louisiana
area (sq. mi)          51843
Name: 882, dtype: object
state/region              LA
ages                 under18
year                    2003
population       1.18807e+06
state              Louisiana
area (sq. mi)          51843
Name: 883, dtype: object
state/region              LA
ages                   total
year                    2004
population       4.55224e+06
state              Louisiana
area (sq. mi)          51843
Name: 884, dtype: object
state/region              LA
ages                 under18
year                    2004
population       1.18273e+06
state              Louisiana
area (sq. mi)          51843
Name: 885, dtype: object
state/region              LA
ages                   total
year                    2001
population       4.47788e+06
state              Louisiana
area (sq. mi)          51843
Name: 886, dtype: object
state/region              LA
ages                 under18
year                    2001
population       1.20419e+06
state              Louisiana
area (sq. mi)          51843
Name: 887, dtype: object
state/region              LA
ages                   total
year                    2002
population       4.49727e+06
state              Louisiana
area (sq. mi)          51843
Name: 888, dtype: object
state/region              LA
ages                 under18
year                    2002
population       1.19482e+06
state              Louisiana
area (sq. mi)          51843
Name: 889, dtype: object
state/region              LA
ages                   total
year                    2000
population       4.47188e+06
state              Louisiana
area (sq. mi)          51843
Name: 890, dtype: object
state/region              LA
ages                 under18
year                    2000
population       1.21767e+06
state              Louisiana
area (sq. mi)          51843
Name: 891, dtype: object
state/region              LA
ages                   total
year                    1999
population       4.46081e+06
state              Louisiana
area (sq. mi)          51843
Name: 892, dtype: object
state/region              LA
ages                 under18
year                    1999
population       1.22717e+06
state              Louisiana
area (sq. mi)          51843
Name: 893, dtype: object
state/region              LA
ages                   total
year                    1997
population       4.42107e+06
state              Louisiana
area (sq. mi)          51843
Name: 894, dtype: object
state/region              LA
ages                 under18
year                    1997
population       1.23966e+06
state              Louisiana
area (sq. mi)          51843
Name: 895, dtype: object
state/region              LA
ages                 under18
year                    1998
population       1.23298e+06
state              Louisiana
area (sq. mi)          51843
Name: 896, dtype: object
state/region              LA
ages                   total
year                    1998
population       4.44034e+06
state              Louisiana
area (sq. mi)          51843
Name: 897, dtype: object
state/region              LA
ages                 under18
year                    1996
population       1.24463e+06
state              Louisiana
area (sq. mi)          51843
Name: 898, dtype: object
state/region              LA
ages                   total
year                    1996
population       4.39888e+06
state              Louisiana
area (sq. mi)          51843
Name: 899, dtype: object
state/region              LA
ages                   total
year                    1995
population       4.37878e+06
state              Louisiana
area (sq. mi)          51843
Name: 900, dtype: object
state/region              LA
ages                 under18
year                    1995
population       1.25011e+06
state              Louisiana
area (sq. mi)          51843
Name: 901, dtype: object
state/region              LA
ages                 under18
year                    1992
population       1.23703e+06
state              Louisiana
area (sq. mi)          51843
Name: 902, dtype: object
state/region            LA
ages                 total
year                  1992
population       4.293e+06
state            Louisiana
area (sq. mi)        51843
Name: 903, dtype: object

state/region              LA
ages                   total
year                    1993
population       4.31643e+06
state              Louisiana
area (sq. mi)          51843
Name: 904, dtype: object
state/region              LA
ages                 under18
year                    1993
population       1.23916e+06
state              Louisiana
area (sq. mi)          51843
Name: 905, dtype: object
state/region              LA
ages                 under18
year                    1994
population       1.24763e+06
state              Louisiana
area (sq. mi)          51843
Name: 906, dtype: object
state/region              LA
ages                   total
year                    1994
population       4.34748e+06
state              Louisiana
area (sq. mi)          51843
Name: 907, dtype: object
state/region              LA
ages                   total
year                    1991
population       4.25328e+06
state              Louisiana
area (sq. mi)          51843
Name: 908, dtype: object
state/region              LA
ages                 under18
year                    1991
population       1.22233e+06
state              Louisiana
area (sq. mi)          51843
Name: 909, dtype: object
state/region              LA
ages                 under18
year                    1990
population       1.20598e+06
state              Louisiana
area (sq. mi)          51843
Name: 910, dtype: object
state/region              LA
ages                   total
year                    1990
population       4.22153e+06
state              Louisiana
area (sq. mi)          51843
Name: 911, dtype: object
state/region          ME
ages             under18
year                1990
population        308066
state              Maine
area (sq. mi)      35387
Name: 912, dtype: object
state/region              ME
ages                   total
year                    1990
population       1.23172e+06
state                  Maine
area (sq. mi)          35387
Name: 913, dtype: object
state/region              ME
ages                   total
year                    1991
population       1.23708e+06
state                  Maine
area (sq. mi)          35387
Name: 914, dtype: object
state/region          ME
ages             under18
year                1991
population        309871
state              Maine
area (sq. mi)      35387
Name: 915, dtype: object
state/region          ME
ages             under18
year                1994
population        311570
state              Maine
area (sq. mi)      35387
Name: 916, dtype: object
state/region              ME
ages                   total
year                    1994
population       1.24266e+06
state                  Maine
area (sq. mi)          35387
Name: 917, dtype: object
state/region             ME
ages                  total
year                   1993
population       1.2423e+06
state                 Maine
area (sq. mi)         35387
Name: 918, dtype: object
state/region          ME
ages             under18
year                1993
population        310966
state              Maine
area (sq. mi)      35387
Name: 919, dtype: object
state/region          ME
ages             under18
year                1992
population        310679
state              Maine
area (sq. mi)      35387
Name: 920, dtype: object
state/region              ME
ages                   total
year                    1992
population       1.23851e+06
state                  Maine
area (sq. mi)          35387
Name: 921, dtype: object
state/region              ME
ages                   total
year                    1995
population       1.24348e+06
state                  Maine
area (sq. mi)          35387
Name: 922, dtype: object
state/region          ME
ages             under18
year                1995
population        309173
state              Maine
area (sq. mi)      35387
Name: 923, dtype: object
state/region          ME
ages             under18
year                1996
population        307740
state              Maine
area (sq. mi)      35387
Name: 924, dtype: object
state/region              ME
ages                   total
year                    1996
population       1.24906e+06
state                  Maine
area (sq. mi)          35387
Name: 925, dtype: object
state/region          ME
ages             under18
year                1998
population        304496
state              Maine
area (sq. mi)      35387
Name: 926, dtype: object
state/region              ME
ages                   total
year                    1998
population       1.25913e+06
state                  Maine
area (sq. mi)          35387
Name: 927, dtype: object
state/region              ME
ages                   total
year                    1997
population       1.25477e+06
state                  Maine
area (sq. mi)          35387
Name: 928, dtype: object
state/region          ME
ages             under18
year                1997
population        305097
state              Maine
area (sq. mi)      35387
Name: 929, dtype: object
state/region              ME
ages                   total
year                    1999
population       1.26681e+06
state                  Maine
area (sq. mi)          35387
Name: 930, dtype: object
state/region          ME
ages             under18
year                1999
population        302321
state              Maine
area (sq. mi)      35387
Name: 931, dtype: object
state/region              ME
ages                   total
year                    2000
population       1.27707e+06
state                  Maine
area (sq. mi)          35387
Name: 932, dtype: object
state/region          ME
ages             under18
year                2000
population        301407
state              Maine
area (sq. mi)      35387
Name: 933, dtype: object
state/region              ME
ages                   total
year                    2002
population       1.29596e+06
state                  Maine
area (sq. mi)          35387
Name: 934, dtype: object
state/region          ME
ages             under18
year                2002
population        298595
state              Maine
area (sq. mi)      35387
Name: 935, dtype: object
state/region              ME
ages                   total
year                    2001
population       1.28569e+06
state                  Maine
area (sq. mi)          35387
Name: 936, dtype: object
state/region          ME
ages             under18
year                2001
population        300088
state              Maine
area (sq. mi)      35387
Name: 937, dtype: object
state/region              ME
ages                   total
year                    2004
population       1.31369e+06
state                  Maine
area (sq. mi)          35387
Name: 938, dtype: object
state/region          ME
ages             under18
year                2004
population        294791
state              Maine
area (sq. mi)      35387
Name: 939, dtype: object
state/region              ME
ages                   total
year                    2003
population       1.30651e+06
state                  Maine
area (sq. mi)          35387
Name: 940, dtype: object
state/region          ME
ages             under18
year                2003
population        296786
state              Maine
area (sq. mi)      35387
Name: 941, dtype: object
state/region              ME
ages                   total
year                    2006
population       1.32362e+06
state                  Maine
area (sq. mi)          35387
Name: 942, dtype: object
state/region          ME
ages             under18
year                2006
population        288945
state              Maine
area (sq. mi)      35387
Name: 943, dtype: object
state/region              ME
ages                   total
year                    2005
population       1.31879e+06
state                  Maine
area (sq. mi)          35387
Name: 944, dtype: object
state/region          ME
ages             under18
year                2005
population        292039
state              Maine
area (sq. mi)      35387
Name: 945, dtype: object
state/region              ME
ages                   total
year                    2008
population       1.33051e+06
state                  Maine
area (sq. mi)          35387
Name: 946, dtype: object
state/region          ME
ages             under18
year                2008
population        282204
state              Maine
area (sq. mi)      35387
Name: 947, dtype: object
state/region              ME
ages                   total
year                    2007
population       1.32704e+06
state                  Maine
area (sq. mi)          35387
Name: 948, dtype: object
state/region          ME
ages             under18
year                2007
population        286185
state              Maine
area (sq. mi)      35387
Name: 949, dtype: object
state/region          ME
ages             under18
year                2013
population        261276
state              Maine
area (sq. mi)      35387
Name: 950, dtype: object
state/region              ME
ages                   total
year                    2009
population       1.32959e+06
state                  Maine
area (sq. mi)          35387
Name: 951, dtype: object
state/region          ME
ages             under18
year                2009
population        277946
state              Maine
area (sq. mi)      35387
Name: 952, dtype: object
state/region             ME
ages                  total
year                   2013
population       1.3283e+06
state                 Maine
area (sq. mi)         35387
Name: 953, dtype: object
state/region              ME
ages                   total
year                    2010
population       1.32737e+06
state                  Maine
area (sq. mi)          35387
Name: 954, dtype: object
state/region          ME
ages             under18
year                2010
population        273061
state              Maine
area (sq. mi)      35387
Name: 955, dtype: object
state/region              ME
ages                   total
year                    2011
population       1.32784e+06
state                  Maine
area (sq. mi)          35387
Name: 956, dtype: object
state/region          ME
ages             under18
year                2011
population        268737
state              Maine
area (sq. mi)      35387
Name: 957, dtype: object
state/region          ME
ages             under18
year                2012
population        264846
state              Maine
area (sq. mi)      35387
Name: 958, dtype: object
state/region             ME
ages                  total
year                   2012
population       1.3285e+06
state                 Maine
area (sq. mi)         35387
Name: 959, dtype: object
state/region              MD
ages                   total
year                    2012
population       5.88487e+06
state               Maryland
area (sq. mi)          12407
Name: 960, dtype: object
state/region              MD
ages                 under18
year                    2012
population       1.34624e+06
state               Maryland
area (sq. mi)          12407
Name: 961, dtype: object
state/region              MD
ages                 under18
year                    2011
population       1.34877e+06
state               Maryland
area (sq. mi)          12407
Name: 962, dtype: object
state/region              MD
ages                   total
year                    2011
population       5.84024e+06
state               Maryland
area (sq. mi)          12407
Name: 963, dtype: object
state/region              MD
ages                 under18
year                    2010
population       1.35198e+06
state               Maryland
area (sq. mi)          12407
Name: 964, dtype: object
state/region              MD
ages                   total
year                    2010
population       5.78719e+06
state               Maryland
area (sq. mi)          12407
Name: 965, dtype: object
state/region              MD
ages                   total
year                    2013
population       5.92881e+06
state               Maryland
area (sq. mi)          12407
Name: 966, dtype: object
state/region              MD
ages                   total
year                    2009
population       5.73039e+06
state               Maryland
area (sq. mi)          12407
Name: 967, dtype: object
state/region              MD
ages                 under18
year                    2009
population       1.35363e+06
state               Maryland
area (sq. mi)          12407
Name: 968, dtype: object
state/region              MD
ages                 under18
year                    2013
population       1.34452e+06
state               Maryland
area (sq. mi)          12407
Name: 969, dtype: object
state/region              MD
ages                   total
year                    2007
population       5.65341e+06
state               Maryland
area (sq. mi)          12407
Name: 970, dtype: object
state/region              MD
ages                 under18
year                    2007
population       1.36956e+06
state               Maryland
area (sq. mi)          12407
Name: 971, dtype: object
state/region              MD
ages                   total
year                    2008
population       5.68496e+06
state               Maryland
area (sq. mi)          12407
Name: 972, dtype: object
state/region              MD
ages                 under18
year                    2008
population       1.35921e+06
state               Maryland
area (sq. mi)          12407
Name: 973, dtype: object
state/region              MD
ages                   total
year                    2005
population       5.59238e+06
state               Maryland
area (sq. mi)          12407
Name: 974, dtype: object
state/region              MD
ages                 under18
year                    2005
population       1.38297e+06
state               Maryland
area (sq. mi)          12407
Name: 975, dtype: object
state/region              MD
ages                   total
year                    2006
population       5.62737e+06
state               Maryland
area (sq. mi)          12407
Name: 976, dtype: object
state/region              MD
ages                 under18
year                    2006
population       1.37776e+06
state               Maryland
area (sq. mi)          12407
Name: 977, dtype: object
state/region              MD
ages                   total
year                    2003
population       5.49627e+06
state               Maryland
area (sq. mi)          12407
Name: 978, dtype: object
state/region              MD
ages                 under18
year                    2003
population       1.37964e+06
state               Maryland
area (sq. mi)          12407
Name: 979, dtype: object
state/region              MD
ages                   total
year                    2004
population       5.54694e+06
state               Maryland
area (sq. mi)          12407
Name: 980, dtype: object
state/region              MD
ages                 under18
year                    2004
population       1.38345e+06
state               Maryland
area (sq. mi)          12407
Name: 981, dtype: object
state/region              MD
ages                   total
year                    2001
population       5.37469e+06
state               Maryland
area (sq. mi)          12407
Name: 982, dtype: object
state/region              MD
ages                 under18
year                    2001
population       1.36655e+06
state               Maryland
area (sq. mi)          12407
Name: 983, dtype: object
state/region              MD
ages                   total
year                    2002
population       5.44039e+06
state               Maryland
area (sq. mi)          12407
Name: 984, dtype: object
state/region              MD
ages                 under18
year                    2002
population       1.37535e+06
state               Maryland
area (sq. mi)          12407
Name: 985, dtype: object
state/region              MD
ages                   total
year                    2000
population       5.31103e+06
state               Maryland
area (sq. mi)          12407
Name: 986, dtype: object
state/region              MD
ages                 under18
year                    2000
population       1.35696e+06
state               Maryland
area (sq. mi)          12407
Name: 987, dtype: object
state/region              MD
ages                   total
year                    1999
population       5.25451e+06
state               Maryland
area (sq. mi)          12407
Name: 988, dtype: object
state/region              MD
ages                 under18
year                    1999
population       1.34866e+06
state               Maryland
area (sq. mi)          12407
Name: 989, dtype: object
state/region              MD
ages                   total
year                    1997
population       5.15733e+06
state               Maryland
area (sq. mi)          12407
Name: 990, dtype: object
state/region              MD
ages                 under18
year                    1997
population       1.32131e+06
state               Maryland
area (sq. mi)          12407
Name: 991, dtype: object
state/region              MD
ages                 under18
year                    1998
population       1.33873e+06
state               Maryland
area (sq. mi)          12407
Name: 992, dtype: object
state/region              MD
ages                   total
year                    1998
population       5.20446e+06
state               Maryland
area (sq. mi)          12407
Name: 993, dtype: object
state/region              MD
ages                 under18
year                    1996
population       1.30382e+06
state               Maryland
area (sq. mi)          12407
Name: 994, dtype: object
state/region              MD
ages                   total
year                    1996
population       5.11199e+06
state               Maryland
area (sq. mi)          12407
Name: 995, dtype: object
state/region              MD
ages                   total
year                    1995
population       5.07003e+06
state               Maryland
area (sq. mi)          12407
Name: 996, dtype: object
state/region             MD
ages                under18
year                   1995
population       1.3007e+06
state              Maryland
area (sq. mi)         12407
Name: 997, dtype: object
state/region             MD
ages                under18
year                   1992
population       1.2355e+06
state              Maryland
area (sq. mi)         12407
Name: 998, dtype: object
state/region              MD
ages                   total
year                    1992
population       4.92337e+06
state               Maryland
area (sq. mi)          12407
Name: 999, dtype: object
state/region              MD
ages                   total
year                    1993
population       4.97189e+06
state               Maryland
area (sq. mi)          12407
Name: 1000, dtype: object
state/region              MD
ages                 under18
year                    1993
population       1.26174e+06
state               Maryland
area (sq. mi)          12407
Name: 1001, dtype: object
state/region              MD
ages                 under18
year                    1994
population       1.28077e+06
state               Maryland
area (sq. mi)          12407
Name: 1002, dtype: object
state/region              MD
ages                   total
year                    1994
population       5.02306e+06
state               Maryland
area (sq. mi)          12407
Name: 1003, dtype: object
state/region              MD
ages                   total
year                    1991
population       4.86764e+06
state               Maryland
area (sq. mi)          12407
Name: 1004, dtype: object
state/region             MD
ages                under18
year                   1991
population       1.2089e+06
state              Maryland
area (sq. mi)         12407
Name: 1005, dtype: object
state/region              MD
ages                 under18
year                    1990
population       1.18043e+06
state               Maryland
area (sq. mi)          12407
Name: 1006, dtype: object
state/region              MD
ages                   total
year                    1990

Name: 1017, dtype: object
state/region                MA
ages                     total
year                      1995
population         6.14144e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1018, dtype: object
state/region                MA
ages                   under18
year                      1995
population         1.45349e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1019, dtype: object
state/region                MA
ages                   under18
year                      1996
population         1.46861e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1020, dtype: object
state/region                MA
ages                     total
year                      1996
population         6.17976e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1021, dtype: object
state/region                MA
ages                   under18
year                      1998
population         1.49165e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1022, dtype: object
state/region                MA
ages                     total
year                      1998
population         6.27184e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1023, dtype: object
state/region                MA
ages                     total
year                      1997
population         6.22606e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1024, dtype: object
state/region                MA
ages                   under18
year                      1997
population          1.4782e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1025, dtype: object
state/region                MA
ages                     total
year                      1999
population         6.31734e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1026, dtype: object
state/region                MA
ages                   under18
year                      1999
population         1.49582e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1027, dtype: object
state/region                MA
ages                     total
year                      2000
population          6.3611e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1028, dtype: object
state/region                MA
ages                   under18
year                      2000
population         1.50133e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1029, dtype: object
state/region                MA
ages                     total
year                      2001
population         6.39763e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1030, dtype: object
state/region                MA
ages                   under18
year                      2001
population         1.50503e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1031, dtype: object
state/region                MA
ages                     total
year                      2002
population         6.41721e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1032, dtype: object
state/region                MA
ages                   under18
year                      2002
population         1.50265e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1033, dtype: object
state/region                MA
ages                     total
year                      2004
population         6.41228e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1034, dtype: object
state/region                MA
ages                   under18
year                      2004
population         1.47954e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1035, dtype: object
state/region                MA
ages                     total
year                      2003
population         6.42256e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1036, dtype: object
state/region                MA
ages                   under18
year                      2003
population         1.49337e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1037, dtype: object
state/region                MA
ages                     total
year                      2006
population         6.41008e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1038, dtype: object
state/region                MA
ages                   under18
year                      2006
population          1.4502e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1039, dtype: object
state/region                MA
ages                     total
year                      2005
population         6.40329e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1040, dtype: object
state/region                MA
ages                   under18
year                      2005
population         1.46414e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1041, dtype: object
state/region                MA
ages                     total
year                      2008
population         6.46897e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1042, dtype: object
state/region                MA
ages                   under18
year                      2008
population         1.42973e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1043, dtype: object
state/region                MA
ages                     total
year                      2007
population         6.43156e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1044, dtype: object
state/region                MA
ages                   under18
year                      2007
population         1.43976e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1045, dtype: object
state/region                MA
ages                   under18
year                      2013
population         1.39395e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1046, dtype: object
state/region                MA
ages                     total
year                      2009
population         6.51761e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1047, dtype: object
state/region                MA
ages                   under18
year                      2009
population         1.42294e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1048, dtype: object
state/region                MA
ages                     total
year                      2013
population         6.69282e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1049, dtype: object
state/region                MA
ages                     total
year                      2010
population         6.56326e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1050, dtype: object
state/region                MA
ages                   under18
year                      2010
population         1.41596e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1051, dtype: object
state/region                MA
ages                     total
year                      2011
population         6.60628e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1052, dtype: object
state/region                MA
ages                   under18
year                      2011
population         1.40724e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1053, dtype: object
state/region                MA
ages                   under18
year                      2012
population         1.39942e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1054, dtype: object
state/region                MA
ages                     total
year                      2012
population          6.6453e+06
state            Massachusetts
area (sq. mi)            10555
Name: 1055, dtype: object
state/region              MI
ages                   total
year                    2012
population       9.88252e+06
state               Michigan
area (sq. mi)          96810
Name: 1056, dtype: object
state/region              MI
ages                 under18
year                    2012
population       2.26936e+06
state               Michigan
area (sq. mi)          96810
Name: 1057, dtype: object
state/region              MI
ages                 under18
year                    2011
population       2.29912e+06
state               Michigan
area (sq. mi)          96810
Name: 1058, dtype: object
state/region              MI
ages                   total
year                    2011
population       9.87459e+06
state               Michigan
area (sq. mi)          96810
Name: 1059, dtype: object
state/region              MI
ages                 under18
year                    2010
population       2.33312e+06
state               Michigan
area (sq. mi)          96810
Name: 1060, dtype: object
state/region              MI
ages                   total
year                    2010
population       9.87615e+06
state               Michigan
area (sq. mi)          96810
Name: 1061, dtype: object
state/region              MI
ages                   total
year                    2013
population       9.89562e+06
state               Michigan
area (sq. mi)          96810
Name: 1062, dtype: object
state/region              MI
ages                   total
year                    2009
population       9.90159e+06
state               Michigan
area (sq. mi)          96810
Name: 1063, dtype: object
state/region             MI
ages                under18
year                   2009
population       2.3726e+06
state              Michigan
area (sq. mi)         96810
Name: 1064, dtype: object
state/region             MI
ages                under18
year                   2013
population       2.2452e+06
state              Michigan
area (sq. mi)         96810
Name: 1065, dtype: object
state/region              MI
ages                   total
year                    2007
population       1.00013e+07
state               Michigan
area (sq. mi)          96810
Name: 1066, dtype: object
state/region              MI
ages                 under18
year                    2007
population       2.47006e+06
state               Michigan
area (sq. mi)          96810
Name: 1067, dtype: object
state/region              MI
ages                   total
year                    2008
population       9.94689e+06
state               Michigan
area (sq. mi)          96810
Name: 1068, dtype: object
state/region              MI
ages                 under18
year                    2008
population       2.41888e+06
state               Michigan
area (sq. mi)          96810
Name: 1069, dtype: object
state/region              MI
ages                   total
year                    2005
population       1.00511e+07
state               Michigan
area (sq. mi)          96810
Name: 1070, dtype: object
state/region              MI
ages                 under18
year                    2005
population       2.53184e+06
state               Michigan
area (sq. mi)          96810
Name: 1071, dtype: object
state/region              MI
ages                   total
year                    2006
population       1.00361e+07
state               Michigan
area (sq. mi)          96810
Name: 1072, dtype: object
state/region              MI
ages                 under18
year                    2006
population       2.50355e+06
state               Michigan
area (sq. mi)          96810
Name: 1073, dtype: object
state/region              MI
ages                   total
year                    2003
population       1.00412e+07
state               Michigan
area (sq. mi)          96810
Name: 1074, dtype: object
state/region              MI
ages                 under18
year                    2003
population       2.56908e+06
state               Michigan
area (sq. mi)          96810
Name: 1075, dtype: object
state/region              MI
ages                   total
year                    2004
population       1.00553e+07
state               Michigan
area (sq. mi)          96810
Name: 1076, dtype: object
state/region              MI
ages                 under18
year                    2004
population       2.55331e+06
state               Michigan
area (sq. mi)          96810
Name: 1077, dtype: object
state/region              MI
ages                   total
year                    2002
population       1.00157e+07
state               Michigan
area (sq. mi)          96810
Name: 1078, dtype: object
state/region              MI
ages                 under18
year                    2002
population       2.58431e+06
state               Michigan
area (sq. mi)          96810
Name: 1079, dtype: object
state/region              MI
ages                   total
year                    2001
population       9.99112e+06
state               Michigan
area (sq. mi)          96810
Name: 1080, dtype: object
state/region              MI
ages                 under18
year                    2001
population       2.59331e+06
state               Michigan
area (sq. mi)          96810
Name: 1081, dtype: object
state/region              MI
ages                   total
year                    2000
population       9.95245e+06
state               Michigan
area (sq. mi)          96810
Name: 1082, dtype: object
state/region              MI
ages                 under18
year                    2000
population       2.59611e+06
state               Michigan
area (sq. mi)          96810
Name: 1083, dtype: object
state/region              MI
ages                   total
year                    1999
population       9.89712e+06
state               Michigan
area (sq. mi)          96810
Name: 1084, dtype: object
state/region              MI
ages                 under18
year                    1999
population       2.59194e+06
state               Michigan
area (sq. mi)          96810
Name: 1085, dtype: object
state/region              MI
ages                   total
year                    1997
population       9.80905e+06
state               Michigan
area (sq. mi)          96810
Name: 1086, dtype: object
state/region              MI
ages                 under18
year                    1997
population       2.58227e+06
state               Michigan
area (sq. mi)          96810

Name: 1087, dtype: object
state/region              MI
ages                 under18
year                    1998
population       2.58634e+06
state               Michigan
area (sq. mi)          96810
Name: 1088, dtype: object
state/region              MI
ages                   total
year                    1998
population       9.84794e+06
state               Michigan
area (sq. mi)          96810
Name: 1089, dtype: object
state/region              MI
ages                 under18
year                    1996
population       2.56974e+06
state               Michigan
area (sq. mi)          96810
Name: 1090, dtype: object
state/region              MI
ages                   total
year                    1996
population       9.75864e+06
state               Michigan
area (sq. mi)          96810
Name: 1091, dtype: object
state/region              MI
ages                   total
year                    1995
population       9.67621e+06
state               Michigan
area (sq. mi)          96810
Name: 1092, dtype: object
state/region             MI
ages                under18
year                   1995
population       2.5568e+06
state              Michigan
area (sq. mi)         96810
Name: 1093, dtype: object
state/region              MI
ages                 under18
year                    1992
population       2.50176e+06
state               Michigan
area (sq. mi)          96810
Name: 1094, dtype: object
state/region              MI
ages                   total
year                    1992
population       9.47906e+06
state               Michigan
area (sq. mi)          96810
Name: 1095, dtype: object
state/region              MI
ages                   total
year                    1993
population       9.54011e+06
state               Michigan
area (sq. mi)          96810
Name: 1096, dtype: object
state/region              MI
ages                 under18
year                    1993
population       2.52225e+06
state               Michigan
area (sq. mi)          96810
Name: 1097, dtype: object
state/region             MI
ages                under18
year                   1994
population       2.5352e+06
state              Michigan
area (sq. mi)         96810
Name: 1098, dtype: object
state/region              MI
ages                   total
year                    1994
population       9.59774e+06
state               Michigan
area (sq. mi)          96810
Name: 1099, dtype: object
state/region              MI
ages                   total
year                    1991
population       9.40045e+06
state               Michigan
area (sq. mi)          96810
Name: 1100, dtype: object
state/region              MI
ages                 under18
year                    1991
population       2.48496e+06
state               Michigan
area (sq. mi)          96810
Name: 1101, dtype: object
state/region              MI
ages                 under18
year                    1990
population       2.45963e+06
state               Michigan
area (sq. mi)          96810
Name: 1102, dtype: object
state/region              MI
ages                   total
year                    1990
population       9.31132e+06
state               Michigan
area (sq. mi)          96810
Name: 1103, dtype: object
state/region              MN
ages                 under18
year                    1990
population       1.17668e+06
state              Minnesota
area (sq. mi)          86943
Name: 1104, dtype: object
state/region              MN
ages                   total
year                    1990
population       4.38986e+06
state              Minnesota
area (sq. mi)          86943
Name: 1105, dtype: object
state/region              MN
ages                   total
year                    1991
population       4.44086e+06
state              Minnesota
area (sq. mi)          86943
Name: 1106, dtype: object
state/region              MN
ages                 under18
year                    1991
population       1.19121e+06
state              Minnesota
area (sq. mi)          86943
Name: 1107, dtype: object
state/region              MN
ages                 under18
year                    1994
population       1.23895e+06
state              Minnesota
area (sq. mi)          86943
Name: 1108, dtype: object
state/region              MN
ages                   total
year                    1994
population       4.61036e+06
state              Minnesota
area (sq. mi)          86943
Name: 1109, dtype: object
state/region              MN
ages                   total
year                    1993
population       4.55596e+06
state              Minnesota
area (sq. mi)          86943
Name: 1110, dtype: object
state/region              MN
ages                 under18
year                    1993
population       1.22672e+06
state              Minnesota
area (sq. mi)          86943
Name: 1111, dtype: object
state/region              MN
ages                 under18
year                    1992
population       1.21307e+06
state              Minnesota
area (sq. mi)          86943
Name: 1112, dtype: object
state/region              MN
ages                   total
year                    1992
population       4.49557e+06
state              Minnesota
area (sq. mi)          86943
Name: 1113, dtype: object
state/region              MN
ages                   total
year                    1995
population       4.66018e+06
state              Minnesota
area (sq. mi)          86943
Name: 1114, dtype: object
state/region              MN
ages                 under18
year                    1995
population       1.24593e+06
state              Minnesota
area (sq. mi)          86943
Name: 1115, dtype: object
state/region              MN
ages                 under18
year                    1996
population       1.25272e+06
state              Minnesota
area (sq. mi)          86943
Name: 1116, dtype: object
state/region              MN
ages                   total
year                    1996
population       4.71283e+06
state              Minnesota
area (sq. mi)          86943
Name: 1117, dtype: object
state/region              MN
ages                 under18
year                    1998
population       1.27594e+06
state              Minnesota
area (sq. mi)          86943
Name: 1118, dtype: object
state/region              MN
ages                   total
year                    1998
population       4.81341e+06
state              Minnesota
area (sq. mi)          86943
Name: 1119, dtype: object
state/region              MN
ages                   total
year                    1997
population       4.76339e+06
state              Minnesota
area (sq. mi)          86943
Name: 1120, dtype: object
state/region              MN
ages                 under18
year                    1997
population       1.26425e+06
state              Minnesota
area (sq. mi)          86943
Name: 1121, dtype: object
state/region              MN
ages                   total
year                    1999
population       4.87348e+06
state              Minnesota
area (sq. mi)          86943
Name: 1122, dtype: object
state/region             MN
ages                under18
year                   1999
population       1.2831e+06
state             Minnesota
area (sq. mi)         86943
Name: 1123, dtype: object
state/region              MN
ages                   total
year                    2000
population       4.93369e+06
state              Minnesota
area (sq. mi)          86943
Name: 1124, dtype: object
state/region              MN
ages                 under18
year                    2000
population       1.28972e+06
state              Minnesota
area (sq. mi)          86943
Name: 1125, dtype: object
state/region             MN
ages                  total
year                   2001
population       4.9828e+06
state             Minnesota
area (sq. mi)         86943
Name: 1126, dtype: object
state/region              MN
ages                 under18
year                    2001
population       1.29126e+06
state              Minnesota
area (sq. mi)          86943
Name: 1127, dtype: object
state/region              MN
ages                   total
year                    2002
population       5.01894e+06
state              Minnesota
area (sq. mi)          86943
Name: 1128, dtype: object
state/region             MN
ages                under18
year                   2002
population       1.2888e+06
state             Minnesota
area (sq. mi)         86943
Name: 1129, dtype: object
state/region              MN
ages                   total
year                    2004
population       5.08771e+06
state              Minnesota
area (sq. mi)          86943
Name: 1130, dtype: object
state/region              MN
ages                 under18
year                    2004
population       1.28195e+06
state              Minnesota
area (sq. mi)          86943
Name: 1131, dtype: object
state/region              MN
ages                   total
year                    2003
population       5.05357e+06
state              Minnesota
area (sq. mi)          86943
Name: 1132, dtype: object
state/region              MN
ages                 under18
year                    2003
population       1.28369e+06
state              Minnesota
area (sq. mi)          86943
Name: 1133, dtype: object
state/region              MN
ages                   total
year                    2006
population       5.16356e+06
state              Minnesota
area (sq. mi)          86943
Name: 1134, dtype: object
state/region              MN
ages                 under18
year                    2006
population       1.28238e+06
state              Minnesota
area (sq. mi)          86943
Name: 1135, dtype: object
state/region             MN
ages                  total
year                   2005
population       5.1196e+06
state             Minnesota
area (sq. mi)         86943
Name: 1136, dtype: object
state/region              MN
ages                 under18
year                    2005
population       1.28056e+06
state              Minnesota
area (sq. mi)          86943
Name: 1137, dtype: object
state/region              MN
ages                   total
year                    2008
population       5.24702e+06
state              Minnesota
area (sq. mi)          86943
Name: 1138, dtype: object
state/region              MN
ages                 under18
year                    2008
population       1.28418e+06
state              Minnesota
area (sq. mi)          86943
Name: 1139, dtype: object
state/region             MN
ages                  total
year                   2007
population       5.2072e+06
state             Minnesota
area (sq. mi)         86943
Name: 1140, dtype: object
state/region              MN
ages                 under18
year                    2007
population       1.28507e+06
state              Minnesota
area (sq. mi)          86943
Name: 1141, dtype: object
state/region              MN
ages                 under18
year                    2013
population       1.27911e+06
state              Minnesota
area (sq. mi)          86943
Name: 1142, dtype: object
state/region             MN
ages                  total
year                   2009
population       5.2812e+06
state             Minnesota
area (sq. mi)         86943
Name: 1143, dtype: object
state/region             MN
ages                under18
year                   2009
population       1.2841e+06
state             Minnesota
area (sq. mi)         86943
Name: 1144, dtype: object
state/region              MN
ages                   total
year                    2013
population       5.42038e+06
state              Minnesota
area (sq. mi)          86943
Name: 1145, dtype: object
state/region              MN
ages                   total
year                    2010
population       5.31034e+06
state              Minnesota
area (sq. mi)          86943
Name: 1146, dtype: object
state/region              MN
ages                 under18
year                    2010
population       1.28269e+06
state              Minnesota
area (sq. mi)          86943
Name: 1147, dtype: object
state/region              MN
ages                   total
year                    2011
population       5.34711e+06
state              Minnesota
area (sq. mi)          86943
Name: 1148, dtype: object
state/region              MN
ages                 under18
year                    2011
population       1.28042e+06
state              Minnesota
area (sq. mi)          86943
Name: 1149, dtype: object
state/region              MN
ages                 under18
year                    2012
population       1.27805e+06
state              Minnesota
area (sq. mi)          86943
Name: 1150, dtype: object
state/region              MN
ages                   total
year                    2012
population       5.37965e+06
state              Minnesota
area (sq. mi)          86943
Name: 1151, dtype: object
state/region              MS
ages                   total
year                    2012
population       2.98645e+06
state            Mississippi
area (sq. mi)          48434
Name: 1152, dtype: object
state/region              MS
ages                 under18
year                    2012
population            742941
state            Mississippi
area (sq. mi)          48434
Name: 1153, dtype: object
state/region              MS
ages                 under18
year                    2011
population            747742
state            Mississippi
area (sq. mi)          48434
Name: 1154, dtype: object
state/region              MS
ages                   total
year                    2011
population       2.97789e+06
state            Mississippi
area (sq. mi)          48434
Name: 1155, dtype: object
state/region              MS
ages                 under18
year                    2010
population            754111
state            Mississippi
area (sq. mi)          48434
Name: 1156, dtype: object
state/region              MS
ages                   total
year                    2010
population       2.97005e+06
state            Mississippi
area (sq. mi)          48434
Name: 1157, dtype: object
state/region              MS
ages                   total
year                    2013
population       2.99121e+06
state            Mississippi
area (sq. mi)          48434

Name: 1158, dtype: object
state/region              MS
ages                   total
year                    2009
population       2.95877e+06
state            Mississippi
area (sq. mi)          48434
Name: 1159, dtype: object
state/region              MS
ages                 under18
year                    2009
population            758539
state            Mississippi
area (sq. mi)          48434
Name: 1160, dtype: object
state/region              MS
ages                 under18
year                    2013
population            737432
state            Mississippi
area (sq. mi)          48434
Name: 1161, dtype: object
state/region              MS
ages                   total
year                    2007
population       2.92835e+06
state            Mississippi
area (sq. mi)          48434
Name: 1162, dtype: object
state/region              MS
ages                 under18
year                    2007
population            761171
state            Mississippi
area (sq. mi)          48434
Name: 1163, dtype: object
state/region              MS
ages                   total
year                    2008
population       2.94781e+06
state            Mississippi
area (sq. mi)          48434
Name: 1164, dtype: object
state/region              MS
ages                 under18
year                    2008
population            760572
state            Mississippi
area (sq. mi)          48434
Name: 1165, dtype: object
state/region              MS
ages                   total
year                    2005
population       2.90594e+06
state            Mississippi
area (sq. mi)          48434
Name: 1166, dtype: object
state/region              MS
ages                 under18
year                    2005
population            760870
state            Mississippi
area (sq. mi)          48434
Name: 1167, dtype: object
state/region              MS
ages                   total
year                    2006
population       2.90498e+06
state            Mississippi
area (sq. mi)          48434
Name: 1168, dtype: object
state/region              MS
ages                 under18
year                    2006
population            756990
state            Mississippi
area (sq. mi)          48434
Name: 1169, dtype: object
state/region              MS
ages                   total
year                    2003
population       2.86831e+06
state            Mississippi
area (sq. mi)          48434
Name: 1170, dtype: object
state/region              MS
ages                 under18
year                    2003
population            759447
state            Mississippi
area (sq. mi)          48434
Name: 1171, dtype: object
state/region              MS
ages                   total
year                    2004
population       2.88901e+06
state            Mississippi
area (sq. mi)          48434
Name: 1172, dtype: object
state/region              MS
ages                 under18
year                    2004
population            760410
state            Mississippi
area (sq. mi)          48434
Name: 1173, dtype: object
state/region              MS
ages                   total
year                    2002
population       2.85868e+06
state            Mississippi
area (sq. mi)          48434
Name: 1174, dtype: object
state/region              MS
ages                 under18
year                    2002
population            763148
state            Mississippi
area (sq. mi)          48434
Name: 1175, dtype: object
state/region              MS
ages                   total
year                    2001
population       2.85299e+06
state            Mississippi
area (sq. mi)          48434
Name: 1176, dtype: object
state/region              MS
ages                 under18
year                    2001
population            768418
state            Mississippi
area (sq. mi)          48434
Name: 1177, dtype: object
state/region              MS
ages                   total
year                    2000
population       2.84835e+06
state            Mississippi
area (sq. mi)          48434
Name: 1178, dtype: object
state/region              MS
ages                 under18
year                    2000
population            774353
state            Mississippi
area (sq. mi)          48434
Name: 1179, dtype: object
state/region              MS
ages                   total
year                    1999
population       2.82841e+06
state            Mississippi
area (sq. mi)          48434
Name: 1180, dtype: object
state/region              MS
ages                 under18
year                    1999
population            775662
state            Mississippi
area (sq. mi)          48434
Name: 1181, dtype: object
state/region              MS
ages                   total
year                    1997
population         2.777e+06
state            Mississippi
area (sq. mi)          48434
Name: 1182, dtype: object
state/region              MS
ages                 under18
year                    1997
population            774832
state            Mississippi
area (sq. mi)          48434
Name: 1183, dtype: object
state/region              MS
ages                 under18
year                    1998
population            773721
state            Mississippi
area (sq. mi)          48434
Name: 1184, dtype: object
state/region              MS
ages                   total
year                    1998
population       2.80483e+06
state            Mississippi
area (sq. mi)          48434
Name: 1185, dtype: object
state/region              MS
ages                 under18
year                    1996
population            769680
state            Mississippi
area (sq. mi)          48434
Name: 1186, dtype: object
state/region              MS
ages                   total
year                    1996
population       2.74808e+06
state            Mississippi
area (sq. mi)          48434
Name: 1187, dtype: object
state/region              MS
ages                   total
year                    1995
population       2.72266e+06
state            Mississippi
area (sq. mi)          48434
Name: 1188, dtype: object
state/region              MS
ages                 under18
year                    1995
population            767892
state            Mississippi
area (sq. mi)          48434
Name: 1189, dtype: object
state/region              MS
ages                 under18
year                    1992
population            750224
state            Mississippi
area (sq. mi)          48434
Name: 1190, dtype: object
state/region              MS
ages                   total
year                    1992
population       2.62373e+06
state            Mississippi
area (sq. mi)          48434
Name: 1191, dtype: object
state/region              MS
ages                   total
year                    1993
population        2.6551e+06
state            Mississippi
area (sq. mi)          48434
Name: 1192, dtype: object
state/region              MS
ages                 under18
year                    1993
population            755820
state            Mississippi
area (sq. mi)          48434
Name: 1193, dtype: object
state/region              MS
ages                 under18
year                    1994
population            763795
state            Mississippi
area (sq. mi)          48434
Name: 1194, dtype: object
state/region              MS
ages                   total
year                    1994
population       2.68899e+06
state            Mississippi
area (sq. mi)          48434
Name: 1195, dtype: object
state/region              MS
ages                   total
year                    1991
population       2.59873e+06
state            Mississippi
area (sq. mi)          48434
Name: 1196, dtype: object
state/region              MS
ages                 under18
year                    1991
population            738911
state            Mississippi
area (sq. mi)          48434
Name: 1197, dtype: object
state/region              MS
ages                 under18
year                    1990
population            733660
state            Mississippi
area (sq. mi)          48434
Name: 1198, dtype: object
state/region              MS
ages                   total
year                    1990
population        2.5789e+06
state            Mississippi
area (sq. mi)          48434
Name: 1199, dtype: object
state/region              MO
ages                 under18
year                    1990
population       1.31642e+06
state               Missouri
area (sq. mi)          69709
Name: 1200, dtype: object
state/region              MO
ages                   total
year                    1990
population       5.12888e+06
state               Missouri
area (sq. mi)          69709
Name: 1201, dtype: object
state/region             MO
ages                  total
year                   1991
population       5.1708e+06
state              Missouri
area (sq. mi)         69709
Name: 1202, dtype: object
state/region              MO
ages                 under18
year                    1991
population       1.33231e+06
state               Missouri
area (sq. mi)          69709
Name: 1203, dtype: object
state/region             MO
ages                under18
year                   1994
population       1.3787e+06
state              Missouri
area (sq. mi)         69709
Name: 1204, dtype: object
state/region             MO
ages                  total
year                   1994
population       5.3245e+06
state              Missouri
area (sq. mi)         69709
Name: 1205, dtype: object
state/region              MO
ages                   total
year                    1993
population       5.27118e+06
state               Missouri
area (sq. mi)          69709
Name: 1206, dtype: object
state/region             MO
ages                under18
year                   1993
population       1.3659e+06
state              Missouri
area (sq. mi)         69709
Name: 1207, dtype: object
state/region              MO
ages                 under18
year                    1992
population       1.34973e+06
state               Missouri
area (sq. mi)          69709
Name: 1208, dtype: object
state/region             MO
ages                  total
year                   1992
population       5.2171e+06
state              Missouri
area (sq. mi)         69709
Name: 1209, dtype: object
state/region              MO
ages                 under18
year                    1996
population       1.40873e+06
state               Missouri
area (sq. mi)          69709
Name: 1210, dtype: object
state/region              MO
ages                   total
year                    1996
population       5.43155e+06
state               Missouri
area (sq. mi)          69709
Name: 1211, dtype: object
state/region              MO
ages                   total
year                    1995
population       5.37825e+06
state               Missouri
area (sq. mi)          69709
Name: 1212, dtype: object
state/region              MO
ages                 under18
year                    1995
population       1.39355e+06
state               Missouri
area (sq. mi)          69709
Name: 1213, dtype: object
state/region            MO
ages               under18
year                  1998
population       1.429e+06
state             Missouri
area (sq. mi)        69709
Name: 1214, dtype: object
state/region              MO
ages                   total
year                    1998
population       5.52176e+06
state               Missouri
area (sq. mi)          69709
Name: 1215, dtype: object
state/region              MO
ages                   total
year                    1997
population       5.48119e+06
state               Missouri
area (sq. mi)          69709
Name: 1216, dtype: object
state/region              MO
ages                 under18
year                    1997
population       1.41984e+06
state               Missouri
area (sq. mi)          69709
Name: 1217, dtype: object
state/region              MO
ages                   total
year                    1999
population       5.56195e+06
state               Missouri
area (sq. mi)          69709
Name: 1218, dtype: object
state/region              MO
ages                 under18
year                    1999
population       1.42805e+06
state               Missouri
area (sq. mi)          69709
Name: 1219, dtype: object
state/region              MO
ages                   total
year                    2000
population       5.60728e+06
state               Missouri
area (sq. mi)          69709
Name: 1220, dtype: object
state/region              MO
ages                 under18
year                    2000
population       1.42838e+06
state               Missouri
area (sq. mi)          69709
Name: 1221, dtype: object
state/region              MO
ages                   total
year                    2001
population       5.64114e+06
state               Missouri
area (sq. mi)          69709
Name: 1222, dtype: object
state/region              MO
ages                 under18
year                    2001
population       1.42658e+06
state               Missouri
area (sq. mi)          69709
Name: 1223, dtype: object
state/region              MO
ages                   total
year                    2002
population       5.67482e+06
state               Missouri
area (sq. mi)          69709
Name: 1224, dtype: object
state/region              MO
ages                 under18
year                    2002
population       1.42451e+06
state               Missouri
area (sq. mi)          69709
Name: 1225, dtype: object
state/region              MO
ages                   total
year                    2004
population       5.74774e+06
state               Missouri
area (sq. mi)          69709
Name: 1226, dtype: object
state/region              MO
ages                 under18
year                    2004
population       1.42096e+06
state               Missouri
area (sq. mi)          69709
Name: 1227, dtype: object
state/region             MO
ages                  total
year                   2003
population       5.7094e+06
state              Missouri
area (sq. mi)         69709

Name: 1228, dtype: object
state/region              MO
ages                 under18
year                    2003
population       1.42193e+06
state               Missouri
area (sq. mi)          69709
Name: 1229, dtype: object
state/region             MO
ages                  total
year                   2006
population       5.8427e+06
state              Missouri
area (sq. mi)         69709
Name: 1230, dtype: object
state/region              MO
ages                 under18
year                    2006
population       1.42832e+06
state               Missouri
area (sq. mi)          69709
Name: 1231, dtype: object
state/region             MO
ages                  total
year                   2005
population       5.7903e+06
state              Missouri
area (sq. mi)         69709
Name: 1232, dtype: object
state/region              MO
ages                 under18
year                    2005
population       1.42298e+06
state               Missouri
area (sq. mi)          69709
Name: 1233, dtype: object
state/region              MO
ages                   total
year                    2008
population       5.92392e+06
state               Missouri
area (sq. mi)          69709
Name: 1234, dtype: object
state/region              MO
ages                 under18
year                    2008
population       1.42894e+06
state               Missouri
area (sq. mi)          69709
Name: 1235, dtype: object
state/region              MO
ages                   total
year                    2007
population       5.88761e+06
state               Missouri
area (sq. mi)          69709
Name: 1236, dtype: object
state/region              MO
ages                 under18
year                    2007
population       1.43135e+06
state               Missouri
area (sq. mi)          69709
Name: 1237, dtype: object
state/region              MO
ages                 under18
year                    2013
population       1.39768e+06
state               Missouri
area (sq. mi)          69709
Name: 1238, dtype: object
state/region              MO
ages                   total
year                    2009
population       5.96109e+06
state               Missouri
area (sq. mi)          69709
Name: 1239, dtype: object
state/region             MO
ages                under18
year                   2009
population       1.4266e+06
state              Missouri
area (sq. mi)         69709
Name: 1240, dtype: object
state/region              MO
ages                   total
year                    2013
population       6.04417e+06
state               Missouri
area (sq. mi)          69709
Name: 1241, dtype: object
state/region              MO
ages                   total
year                    2010
population       5.99606e+06
state               Missouri
area (sq. mi)          69709
Name: 1242, dtype: object
state/region              MO
ages                 under18
year                    2010
population       1.42404e+06
state               Missouri
area (sq. mi)          69709
Name: 1243, dtype: object
state/region              MO
ages                   total
year                    2011
population       6.01006e+06
state               Missouri
area (sq. mi)          69709
Name: 1244, dtype: object
state/region              MO
ages                 under18
year                    2011
population       1.41444e+06
state               Missouri
area (sq. mi)          69709
Name: 1245, dtype: object
state/region              MO
ages                 under18
year                    2012
population       1.40502e+06
state               Missouri
area (sq. mi)          69709
Name: 1246, dtype: object
state/region              MO
ages                   total
year                    2012
population       6.02452e+06
state               Missouri
area (sq. mi)          69709
Name: 1247, dtype: object
state/region              MT
ages                   total
year                    2012
population       1.00549e+06
state                Montana
area (sq. mi)         147046
Name: 1248, dtype: object
state/region          MT
ages             under18
year                2012
population        222905
state            Montana
area (sq. mi)     147046
Name: 1249, dtype: object
state/region          MT
ages             under18
year                2011
population        222977
state            Montana
area (sq. mi)     147046
Name: 1250, dtype: object
state/region          MT
ages               total
year                2011
population        997600
state            Montana
area (sq. mi)     147046
Name: 1251, dtype: object
state/region          MT
ages             under18
year                2010
population        223292
state            Montana
area (sq. mi)     147046
Name: 1252, dtype: object
state/region          MT
ages               total
year                2010
population        990527
state            Montana
area (sq. mi)     147046
Name: 1253, dtype: object
state/region              MT
ages                   total
year                    2013
population       1.01516e+06
state                Montana
area (sq. mi)         147046
Name: 1254, dtype: object
state/region          MT
ages               total
year                2009
population        983982
state            Montana
area (sq. mi)     147046
Name: 1255, dtype: object
state/region          MT
ages             under18
year                2009
population        223675
state            Montana
area (sq. mi)     147046
Name: 1256, dtype: object
state/region          MT
ages             under18
year                2013
population        223981
state            Montana
area (sq. mi)     147046
Name: 1257, dtype: object
state/region          MT
ages               total
year                2007
population        964706
state            Montana
area (sq. mi)     147046
Name: 1258, dtype: object
state/region          MT
ages             under18
year                2007
population        223135
state            Montana
area (sq. mi)     147046
Name: 1259, dtype: object
state/region          MT
ages               total
year                2008
population        976415
state            Montana
area (sq. mi)     147046
Name: 1260, dtype: object
state/region          MT
ages             under18
year                2008
population        223814
state            Montana
area (sq. mi)     147046
Name: 1261, dtype: object
state/region          MT
ages               total
year                2005
population        940102
state            Montana
area (sq. mi)     147046
Name: 1262, dtype: object
state/region          MT
ages             under18
year                2005
population        221685
state            Montana
area (sq. mi)     147046
Name: 1263, dtype: object
state/region          MT
ages               total
year                2006
population        952692
state            Montana
area (sq. mi)     147046
Name: 1264, dtype: object
state/region          MT
ages             under18
year                2006
population        221930
state            Montana
area (sq. mi)     147046
Name: 1265, dtype: object
state/region          MT
ages               total
year                2003
population        919630
state            Montana
area (sq. mi)     147046
Name: 1266, dtype: object
state/region          MT
ages             under18
year                2003
population        223012
state            Montana
area (sq. mi)     147046
Name: 1267, dtype: object
state/region          MT
ages               total
year                2004
population        930009
state            Montana
area (sq. mi)     147046
Name: 1268, dtype: object
state/region          MT
ages             under18
year                2004
population        221999
state            Montana
area (sq. mi)     147046
Name: 1269, dtype: object
state/region          MT
ages               total
year                2002
population        911667
state            Montana
area (sq. mi)     147046
Name: 1270, dtype: object
state/region          MT
ages             under18
year                2002
population        224772
state            Montana
area (sq. mi)     147046
Name: 1271, dtype: object
state/region          MT
ages               total
year                2001
population        906961
state            Montana
area (sq. mi)     147046
Name: 1272, dtype: object
state/region          MT
ages             under18
year                2001
population        227118
state            Montana
area (sq. mi)     147046
Name: 1273, dtype: object
state/region          MT
ages               total
year                1999
population        897508
state            Montana
area (sq. mi)     147046
Name: 1274, dtype: object
state/region          MT
ages             under18
year                1999
population        231133
state            Montana
area (sq. mi)     147046
Name: 1275, dtype: object
state/region          MT
ages               total
year                2000
population        903773
state            Montana
area (sq. mi)     147046
Name: 1276, dtype: object
state/region          MT
ages             under18
year                2000
population        230067
state            Montana
area (sq. mi)     147046
Name: 1277, dtype: object
state/region          MT
ages               total
year                1997
population        889865
state            Montana
area (sq. mi)     147046
Name: 1278, dtype: object
state/region          MT
ages             under18
year                1997
population        232813
state            Montana
area (sq. mi)     147046
Name: 1279, dtype: object
state/region          MT
ages             under18
year                1998
population        231746
state            Montana
area (sq. mi)     147046
Name: 1280, dtype: object
state/region          MT
ages               total
year                1998
population        892431
state            Montana
area (sq. mi)     147046
Name: 1281, dtype: object
state/region          MT
ages               total
year                1995
population        876553
state            Montana
area (sq. mi)     147046
Name: 1282, dtype: object
state/region          MT
ages             under18
year                1995
population        236583
state            Montana
area (sq. mi)     147046
Name: 1283, dtype: object
state/region          MT
ages             under18
year                1996
population        235294
state            Montana
area (sq. mi)     147046
Name: 1284, dtype: object
state/region          MT
ages               total
year                1996
population        886254
state            Montana
area (sq. mi)     147046
Name: 1285, dtype: object
state/region          MT
ages             under18
year                1992
population        230868
state            Montana
area (sq. mi)     147046
Name: 1286, dtype: object
state/region          MT
ages               total
year                1992
population        825770
state            Montana
area (sq. mi)     147046
Name: 1287, dtype: object
state/region          MT
ages               total
year                1993
population        844761
state            Montana
area (sq. mi)     147046
Name: 1288, dtype: object
state/region          MT
ages             under18
year                1993
population        234987
state            Montana
area (sq. mi)     147046
Name: 1289, dtype: object
state/region          MT
ages             under18
year                1994
population        237289
state            Montana
area (sq. mi)     147046
Name: 1290, dtype: object
state/region          MT
ages               total
year                1994
population        861306
state            Montana
area (sq. mi)     147046
Name: 1291, dtype: object
state/region          MT
ages               total
year                1991
population        809680
state            Montana
area (sq. mi)     147046
Name: 1292, dtype: object
state/region          MT
ages             under18
year                1991
population        225259
state            Montana
area (sq. mi)     147046
Name: 1293, dtype: object
state/region          MT
ages             under18
year                1990
population        223677
state            Montana
area (sq. mi)     147046
Name: 1294, dtype: object
state/region          MT
ages               total
year                1990
population        800204
state            Montana
area (sq. mi)     147046
Name: 1295, dtype: object
state/region           NE
ages              under18
year                 1990
population         430068
state            Nebraska
area (sq. mi)       77358
Name: 1296, dtype: object
state/region              NE
ages                   total
year                    1990
population       1.58166e+06
state               Nebraska
area (sq. mi)          77358
Name: 1297, dtype: object
state/region              NE
ages                   total
year                    1991
population       1.59592e+06
state               Nebraska
area (sq. mi)          77358
Name: 1298, dtype: object
state/region           NE
ages              under18
year                 1991
population         434525
state            Nebraska
area (sq. mi)       77358
Name: 1299, dtype: object
state/region           NE
ages              under18
year                 1994
population         442589
state            Nebraska
area (sq. mi)       77358
Name: 1300, dtype: object
state/region              NE
ages                   total
year                    1994
population       1.63904e+06
state               Nebraska
area (sq. mi)          77358
Name: 1301, dtype: object
state/region              NE
ages                   total
year                    1993
population       1.62559e+06
state               Nebraska
area (sq. mi)          77358
Name: 1302, dtype: object
state/region           NE
ages              under18
year                 1993
population         439313
state            Nebraska
area (sq. mi)       77358
Name: 1303, dtype: object
state/region           NE
ages              under18
year                 1992
population         436378
state            Nebraska
area (sq. mi)       77358
Name: 1304, dtype: object
state/region              NE
ages                   total
year                    1992
population       1.61169e+06
state               Nebraska
area (sq. mi)          77358
Name: 1305, dtype: object
state/region           NE
ages              under18
year                 1996
population         446841
state            Nebraska
area (sq. mi)       77358
Name: 1306, dtype: object
state/region              NE
ages                   total
year                    1996
population       1.67374e+06
state               Nebraska
area (sq. mi)          77358
Name: 1307, dtype: object
state/region              NE
ages                   total
year                    1995
population       1.65699e+06
state               Nebraska
area (sq. mi)          77358

Name: 1308, dtype: object
state/region           NE
ages              under18
year                 1995
population         444418
state            Nebraska
area (sq. mi)       77358
Name: 1309, dtype: object
state/region           NE
ages              under18
year                 1998
population         451192
state            Nebraska
area (sq. mi)       77358
Name: 1310, dtype: object
state/region              NE
ages                   total
year                    1998
population       1.69582e+06
state               Nebraska
area (sq. mi)          77358
Name: 1311, dtype: object
state/region              NE
ages                   total
year                    1997
population       1.68642e+06
state               Nebraska
area (sq. mi)          77358
Name: 1312, dtype: object
state/region           NE
ages              under18
year                 1997
population         450076
state            Nebraska
area (sq. mi)       77358
Name: 1313, dtype: object
state/region              NE
ages                   total
year                    1999
population       1.70476e+06
state               Nebraska
area (sq. mi)          77358
Name: 1314, dtype: object
state/region           NE
ages              under18
year                 1999
population         451047
state            Nebraska
area (sq. mi)       77358
Name: 1315, dtype: object
state/region              NE
ages                   total
year                    2000
population       1.71382e+06
state               Nebraska
area (sq. mi)          77358
Name: 1316, dtype: object
state/region           NE
ages              under18
year                 2000
population         450380
state            Nebraska
area (sq. mi)       77358
Name: 1317, dtype: object
state/region              NE
ages                   total
year                    2001
population       1.71984e+06
state               Nebraska
area (sq. mi)          77358
Name: 1318, dtype: object
state/region           NE
ages              under18
year                 2001
population         448307
state            Nebraska
area (sq. mi)       77358
Name: 1319, dtype: object
state/region              NE
ages                   total
year                    2002
population       1.72829e+06
state               Nebraska
area (sq. mi)          77358
Name: 1320, dtype: object
state/region           NE
ages              under18
year                 2002
population         447714
state            Nebraska
area (sq. mi)       77358
Name: 1321, dtype: object
state/region              NE
ages                   total
year                    2004
population       1.74937e+06
state               Nebraska
area (sq. mi)          77358
Name: 1322, dtype: object
state/region           NE
ages              under18
year                 2004
population         448360
state            Nebraska
area (sq. mi)       77358
Name: 1323, dtype: object
state/region              NE
ages                   total
year                    2003
population       1.73864e+06
state               Nebraska
area (sq. mi)          77358
Name: 1324, dtype: object
state/region           NE
ages              under18
year                 2003
population         447444
state            Nebraska
area (sq. mi)       77358
Name: 1325, dtype: object
state/region              NE
ages                   total
year                    2006
population       1.77269e+06
state               Nebraska
area (sq. mi)          77358
Name: 1326, dtype: object
state/region           NE
ages              under18
year                 2006
population         450098
state            Nebraska
area (sq. mi)       77358
Name: 1327, dtype: object
state/region             NE
ages                  total
year                   2005
population       1.7615e+06
state              Nebraska
area (sq. mi)         77358
Name: 1328, dtype: object
state/region           NE
ages              under18
year                 2005
population         448918
state            Nebraska
area (sq. mi)       77358
Name: 1329, dtype: object
state/region              NE
ages                   total
year                    2008
population       1.79638e+06
state               Nebraska
area (sq. mi)          77358
Name: 1330, dtype: object
state/region           NE
ages              under18
year                 2008
population         453787
state            Nebraska
area (sq. mi)       77358
Name: 1331, dtype: object
state/region              NE
ages                   total
year                    2007
population       1.78344e+06
state               Nebraska
area (sq. mi)          77358
Name: 1332, dtype: object
state/region           NE
ages              under18
year                 2007
population         451946
state            Nebraska
area (sq. mi)       77358
Name: 1333, dtype: object
state/region           NE
ages              under18
year                 2013
population         464348
state            Nebraska
area (sq. mi)       77358
Name: 1334, dtype: object
state/region              NE
ages                   total
year                    2009
population       1.81268e+06
state               Nebraska
area (sq. mi)          77358
Name: 1335, dtype: object
state/region           NE
ages              under18
year                 2009
population         456543
state            Nebraska
area (sq. mi)       77358
Name: 1336, dtype: object
state/region              NE
ages                   total
year                    2013
population       1.86852e+06
state               Nebraska
area (sq. mi)          77358
Name: 1337, dtype: object
state/region              NE
ages                   total
year                    2010
population       1.82984e+06
state               Nebraska
area (sq. mi)          77358
Name: 1338, dtype: object
state/region           NE
ages              under18
year                 2010
population         459621
state            Nebraska
area (sq. mi)       77358
Name: 1339, dtype: object
state/region              NE
ages                   total
year                    2011
population       1.84175e+06
state               Nebraska
area (sq. mi)          77358
Name: 1340, dtype: object
state/region           NE
ages              under18
year                 2011
population         460872
state            Nebraska
area (sq. mi)       77358
Name: 1341, dtype: object
state/region           NE
ages              under18
year                 2012
population         462673
state            Nebraska
area (sq. mi)       77358
Name: 1342, dtype: object
state/region              NE
ages                   total
year                    2012
population       1.85535e+06
state               Nebraska
area (sq. mi)          77358
Name: 1343, dtype: object
state/region              NV
ages                   total
year                    2012
population       2.75435e+06
state                 Nevada
area (sq. mi)         110567
Name: 1344, dtype: object
state/region          NV
ages             under18
year                2012
population        659655
state             Nevada
area (sq. mi)     110567
Name: 1345, dtype: object
state/region          NV
ages             under18
year                2011
population        659236
state             Nevada
area (sq. mi)     110567
Name: 1346, dtype: object
state/region              NV
ages                   total
year                    2011
population       2.71795e+06
state                 Nevada
area (sq. mi)         110567
Name: 1347, dtype: object
state/region          NV
ages             under18
year                2010
population        663180
state             Nevada
area (sq. mi)     110567
Name: 1348, dtype: object
state/region              NV
ages                   total
year                    2010
population       2.70323e+06
state                 Nevada
area (sq. mi)         110567
Name: 1349, dtype: object
state/region              NV
ages                   total
year                    2013
population       2.79014e+06
state                 Nevada
area (sq. mi)         110567
Name: 1350, dtype: object
state/region              NV
ages                   total
year                    2009
population       2.68466e+06
state                 Nevada
area (sq. mi)         110567
Name: 1351, dtype: object
state/region          NV
ages             under18
year                2009
population        666041
state             Nevada
area (sq. mi)     110567
Name: 1352, dtype: object
state/region          NV
ages             under18
year                2013
population        661605
state             Nevada
area (sq. mi)     110567
Name: 1353, dtype: object
state/region              NV
ages                   total
year                    2007
population       2.60107e+06
state                 Nevada
area (sq. mi)         110567
Name: 1354, dtype: object
state/region          NV
ages             under18
year                2007
population        654053
state             Nevada
area (sq. mi)     110567
Name: 1355, dtype: object
state/region              NV
ages                   total
year                    2008
population       2.65363e+06
state                 Nevada
area (sq. mi)         110567
Name: 1356, dtype: object
state/region          NV
ages             under18
year                2008
population        662621
state             Nevada
area (sq. mi)     110567
Name: 1357, dtype: object
state/region              NV
ages                   total
year                    2005
population       2.43214e+06
state                 Nevada
area (sq. mi)         110567
Name: 1358, dtype: object
state/region          NV
ages             under18
year                2005
population        611595
state             Nevada
area (sq. mi)     110567
Name: 1359, dtype: object
state/region              NV
ages                   total
year                    2006
population       2.52266e+06
state                 Nevada
area (sq. mi)         110567
Name: 1360, dtype: object
state/region          NV
ages             under18
year                2006
population        634403
state             Nevada
area (sq. mi)     110567
Name: 1361, dtype: object
state/region              NV
ages                   total
year                    2003
population       2.24885e+06
state                 Nevada
area (sq. mi)         110567
Name: 1362, dtype: object
state/region          NV
ages             under18
year                2003
population        568963
state             Nevada
area (sq. mi)     110567
Name: 1363, dtype: object
state/region              NV
ages                   total
year                    2004
population       2.34622e+06
state                 Nevada
area (sq. mi)         110567
Name: 1364, dtype: object
state/region          NV
ages             under18
year                2004
population        591314
state             Nevada
area (sq. mi)     110567
Name: 1365, dtype: object
state/region              NV
ages                   total
year                    2002
population       2.17379e+06
state                 Nevada
area (sq. mi)         110567
Name: 1366, dtype: object
state/region          NV
ages             under18
year                2002
population        552816
state             Nevada
area (sq. mi)     110567
Name: 1367, dtype: object
state/region             NV
ages                  total
year                   2001
population       2.0984e+06
state                Nevada
area (sq. mi)        110567
Name: 1368, dtype: object
state/region          NV
ages             under18
year                2001
population        534708
state             Nevada
area (sq. mi)     110567
Name: 1369, dtype: object
state/region              NV
ages                   total
year                    1999
population       1.93472e+06
state                 Nevada
area (sq. mi)         110567
Name: 1370, dtype: object
state/region          NV
ages             under18
year                1999
population        493701
state             Nevada
area (sq. mi)     110567
Name: 1371, dtype: object
state/region              NV
ages                   total
year                    2000
population       2.01874e+06
state                 Nevada
area (sq. mi)         110567
Name: 1372, dtype: object
state/region          NV
ages             under18
year                2000
population        516018
state             Nevada
area (sq. mi)     110567
Name: 1373, dtype: object
state/region             NV
ages                  total
year                   1997
population       1.7641e+06
state                Nevada
area (sq. mi)        110567
Name: 1374, dtype: object
state/region          NV
ages             under18
year                1997
population        443626
state             Nevada
area (sq. mi)     110567
Name: 1375, dtype: object
state/region          NV
ages             under18
year                1998
population        469424
state             Nevada
area (sq. mi)     110567
Name: 1376, dtype: object
state/region              NV
ages                   total
year                    1998
population       1.85319e+06
state                 Nevada
area (sq. mi)         110567
Name: 1377, dtype: object
state/region              NV
ages                   total
year                    1995
population       1.58158e+06
state                 Nevada
area (sq. mi)         110567
Name: 1378, dtype: object
state/region          NV
ages             under18
year                1995
population        396223
state             Nevada
area (sq. mi)     110567
Name: 1379, dtype: object
state/region          NV
ages             under18
year                1996
population        419133
state             Nevada
area (sq. mi)     110567
Name: 1380, dtype: object
state/region              NV
ages                   total
year                    1996
population       1.66632e+06
state                 Nevada
area (sq. mi)         110567
Name: 1381, dtype: object
state/region          NV
ages             under18
year                1992
population        337396
state             Nevada
area (sq. mi)     110567
Name: 1382, dtype: object
state/region              NV
ages                   total
year                    1992
population       1.35137e+06
state                 Nevada
area (sq. mi)         110567
Name: 1383, dtype: object
state/region              NV
ages                   total
year                    1993
population       1.41122e+06
state                 Nevada
area (sq. mi)         110567
Name: 1384, dtype: object
state/region          NV
ages             under18
year                1993
population        354990
state             Nevada
area (sq. mi)     110567
Name: 1385, dtype: object
state/region          NV
ages             under18
year                1994
population        376745
state             Nevada
area (sq. mi)     110567
Name: 1386, dtype: object
state/region             NV
ages                  total
year                   1994
population       1.4993e+06
state                Nevada
area (sq. mi)        110567
Name: 1387, dtype: object
state/region              NV
ages                   total
year                    1991
population       1.29617e+06
state                 Nevada
area (sq. mi)         110567
Name: 1388, dtype: object
state/region          NV
ages             under18
year                1991
population        325033
state             Nevada
area (sq. mi)     110567
Name: 1389, dtype: object
state/region          NV
ages             under18
year                1990
population        316406
state             Nevada
area (sq. mi)     110567
Name: 1390, dtype: object
state/region             NV
ages                  total
year                   1990
population       1.2207e+06
state                Nevada
area (sq. mi)        110567
Name: 1391, dtype: object
state/region                NH
ages                   under18
year                      1990
population              277454
state            New Hampshire
area (sq. mi)             9351

Name: 1392, dtype: object
state/region                NH
ages                     total
year                      1990
population         1.11238e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1393, dtype: object
state/region                NH
ages                     total
year                      1991
population         1.10993e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1394, dtype: object
state/region                NH
ages                   under18
year                      1991
population              281127
state            New Hampshire
area (sq. mi)             9351
Name: 1395, dtype: object
state/region                NH
ages                   under18
year                      1994
population              295563
state            New Hampshire
area (sq. mi)             9351
Name: 1396, dtype: object
state/region                NH
ages                     total
year                      1994
population         1.14256e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1397, dtype: object
state/region                NH
ages                     total
year                      1993
population         1.12946e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1398, dtype: object
state/region                NH
ages                   under18
year                      1993
population              290409
state            New Hampshire
area (sq. mi)             9351
Name: 1399, dtype: object
state/region                NH
ages                   under18
year                      1992
population              286314
state            New Hampshire
area (sq. mi)             9351
Name: 1400, dtype: object
state/region                NH
ages                     total
year                      1992
population         1.11778e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1401, dtype: object
state/region                NH
ages                   under18
year                      1996
population              300161
state            New Hampshire
area (sq. mi)             9351
Name: 1402, dtype: object
state/region                NH
ages                     total
year                      1996
population         1.17472e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1403, dtype: object
state/region                NH
ages                     total
year                      1995
population         1.15756e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1404, dtype: object
state/region                NH
ages                   under18
year                      1995
population              298246
state            New Hampshire
area (sq. mi)             9351
Name: 1405, dtype: object
state/region                NH
ages                   under18
year                      1998
population              307292
state            New Hampshire
area (sq. mi)             9351
Name: 1406, dtype: object
state/region                NH
ages                     total
year                      1998
population         1.20594e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1407, dtype: object
state/region                NH
ages                     total
year                      1997
population         1.18942e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1408, dtype: object
state/region                NH
ages                   under18
year                      1997
population              302834
state            New Hampshire
area (sq. mi)             9351
Name: 1409, dtype: object
state/region                NH
ages                     total
year                      2000
population         1.23988e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1410, dtype: object
state/region                NH
ages                   under18
year                      2000
population              310352
state            New Hampshire
area (sq. mi)             9351
Name: 1411, dtype: object
state/region                NH
ages                     total
year                      1999
population         1.22202e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1412, dtype: object
state/region                NH
ages                   under18
year                      1999
population              308423
state            New Hampshire
area (sq. mi)             9351
Name: 1413, dtype: object
state/region                NH
ages                     total
year                      2001
population         1.25552e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1414, dtype: object
state/region                NH
ages                   under18
year                      2001
population              311877
state            New Hampshire
area (sq. mi)             9351
Name: 1415, dtype: object
state/region                NH
ages                     total
year                      2002
population         1.26909e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1416, dtype: object
state/region                NH
ages                   under18
year                      2002
population              312743
state            New Hampshire
area (sq. mi)             9351
Name: 1417, dtype: object
state/region                NH
ages                     total
year                      2004
population         1.29012e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1418, dtype: object
state/region                NH
ages                   under18
year                      2004
population              309243
state            New Hampshire
area (sq. mi)             9351
Name: 1419, dtype: object
state/region                NH
ages                     total
year                      2003
population         1.27984e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1420, dtype: object
state/region                NH
ages                   under18
year                      2003
population              311412
state            New Hampshire
area (sq. mi)             9351
Name: 1421, dtype: object
state/region                NH
ages                     total
year                      2005
population         1.29849e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1422, dtype: object
state/region                NH
ages                   under18
year                      2005
population              307403
state            New Hampshire
area (sq. mi)             9351
Name: 1423, dtype: object
state/region                NH
ages                     total
year                      2006
population         1.30839e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1424, dtype: object
state/region                NH
ages                   under18
year                      2006
population              305169
state            New Hampshire
area (sq. mi)             9351
Name: 1425, dtype: object
state/region                NH
ages                     total
year                      2008
population         1.31591e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1426, dtype: object
state/region                NH
ages                   under18
year                      2008
population              296029
state            New Hampshire
area (sq. mi)             9351
Name: 1427, dtype: object
state/region                NH
ages                     total
year                      2007
population         1.31254e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1428, dtype: object
state/region                NH
ages                   under18
year                      2007
population              300918
state            New Hampshire
area (sq. mi)             9351
Name: 1429, dtype: object
state/region                NH
ages                   under18
year                      2013
population              271122
state            New Hampshire
area (sq. mi)             9351
Name: 1430, dtype: object
state/region                NH
ages                     total
year                      2009
population          1.3161e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1431, dtype: object
state/region                NH
ages                   under18
year                      2009
population              290850
state            New Hampshire
area (sq. mi)             9351
Name: 1432, dtype: object
state/region                NH
ages                     total
year                      2013
population         1.32346e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1433, dtype: object
state/region                NH
ages                     total
year                      2010
population         1.31661e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1434, dtype: object
state/region                NH
ages                   under18
year                      2010
population              285702
state            New Hampshire
area (sq. mi)             9351
Name: 1435, dtype: object
state/region                NH
ages                     total
year                      2011
population         1.31808e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1436, dtype: object
state/region                NH
ages                   under18
year                      2011
population              280486
state            New Hampshire
area (sq. mi)             9351
Name: 1437, dtype: object
state/region                NH
ages                   under18
year                      2012
population              275818
state            New Hampshire
area (sq. mi)             9351
Name: 1438, dtype: object
state/region                NH
ages                     total
year                      2012
population         1.32162e+06
state            New Hampshire
area (sq. mi)             9351
Name: 1439, dtype: object
state/region              NJ
ages                   total
year                    2012
population       8.86775e+06
state             New Jersey
area (sq. mi)           8722
Name: 1440, dtype: object
state/region              NJ
ages                 under18
year                    2012
population       2.03511e+06
state             New Jersey
area (sq. mi)           8722
Name: 1441, dtype: object
state/region              NJ
ages                 under18
year                    2011
population       2.04945e+06
state             New Jersey
area (sq. mi)           8722
Name: 1442, dtype: object
state/region              NJ
ages                   total
year                    2011
population       8.83664e+06
state             New Jersey
area (sq. mi)           8722
Name: 1443, dtype: object
state/region              NJ
ages                 under18
year                    2010
population       2.06201e+06
state             New Jersey
area (sq. mi)           8722
Name: 1444, dtype: object
state/region              NJ
ages                   total
year                    2010
population       8.80271e+06
state             New Jersey
area (sq. mi)           8722
Name: 1445, dtype: object
state/region              NJ
ages                   total
year                    2013
population       8.89934e+06
state             New Jersey
area (sq. mi)           8722
Name: 1446, dtype: object
state/region             NJ
ages                  total
year                   2009
population       8.7556e+06
state            New Jersey
area (sq. mi)          8722
Name: 1447, dtype: object
state/region              NJ
ages                 under18
year                    2009
population       2.06868e+06
state             New Jersey
area (sq. mi)           8722
Name: 1448, dtype: object
state/region              NJ
ages                 under18
year                    2013
population       2.02212e+06
state             New Jersey
area (sq. mi)           8722
Name: 1449, dtype: object
state/region              NJ
ages                   total
year                    2007
population       8.67788e+06
state             New Jersey
area (sq. mi)           8722
Name: 1450, dtype: object
state/region              NJ
ages                 under18
year                    2007
population       2.09102e+06
state             New Jersey
area (sq. mi)           8722
Name: 1451, dtype: object
state/region              NJ
ages                   total
year                    2008
population       8.71109e+06
state             New Jersey
area (sq. mi)           8722
Name: 1452, dtype: object
state/region              NJ
ages                 under18
year                    2008
population       2.07637e+06
state             New Jersey
area (sq. mi)           8722
Name: 1453, dtype: object
state/region              NJ
ages                   total
year                    2006
population       8.66168e+06
state             New Jersey
area (sq. mi)           8722
Name: 1454, dtype: object
state/region             NJ
ages                under18
year                   2006
population       2.1064e+06
state            New Jersey
area (sq. mi)          8722
Name: 1455, dtype: object
state/region              NJ
ages                   total
year                    2005
population       8.65197e+06
state             New Jersey
area (sq. mi)           8722
Name: 1456, dtype: object
state/region              NJ
ages                 under18
year                    2005
population       2.12188e+06
state             New Jersey
area (sq. mi)           8722
Name: 1457, dtype: object
state/region             NJ
ages                  total
year                   2003
population       8.6014e+06
state            New Jersey
area (sq. mi)          8722
Name: 1458, dtype: object
state/region              NJ
ages                 under18
year                    2003
population       2.12601e+06
state             New Jersey
area (sq. mi)           8722
Name: 1459, dtype: object
state/region              NJ
ages                   total
year                    2004
population       8.63456e+06
state             New Jersey
area (sq. mi)           8722
Name: 1460, dtype: object
state/region              NJ
ages                 under18
year                    2004
population       2.12905e+06
state             New Jersey
area (sq. mi)           8722
Name: 1461, dtype: object
state/region              NJ
ages                   total
year                    2002
population       8.55264e+06
state             New Jersey
area (sq. mi)           8722
Name: 1462, dtype: object
state/region              NJ
ages                 under18
year                    2002
population       2.11659e+06
state             New Jersey
area (sq. mi)           8722
Name: 1463, dtype: object
state/region              NJ
ages                   total
year                    2001
population       8.49267e+06
state             New Jersey
area (sq. mi)           8722
Name: 1464, dtype: object
state/region              NJ
ages                 under18
year                    2001
population       2.10284e+06
state             New Jersey
area (sq. mi)           8722
Name: 1465, dtype: object
state/region              NJ
ages                   total
year                    1999
population       8.35959e+06
state             New Jersey
area (sq. mi)           8722
Name: 1466, dtype: object
state/region              NJ
ages                 under18
year                    1999
population       2.06668e+06
state             New Jersey
area (sq. mi)           8722
Name: 1467, dtype: object
state/region              NJ
ages                   total
year                    2000
population       8.43062e+06
state             New Jersey
area (sq. mi)           8722
Name: 1468, dtype: object
state/region              NJ
ages                 under18
year                    2000
population       2.08888e+06
state             New Jersey
area (sq. mi)           8722
Name: 1469, dtype: object
state/region              NJ
ages                   total
year                    1997
population       8.21881e+06
state             New Jersey
area (sq. mi)           8722
Name: 1470, dtype: object
state/region              NJ
ages                 under18
year                    1997
population       2.02835e+06
state             New Jersey
area (sq. mi)           8722
Name: 1471, dtype: object
state/region              NJ
ages                 under18
year                    1998
population       2.04208e+06
state             New Jersey
area (sq. mi)           8722
Name: 1472, dtype: object
state/region              NJ
ages                   total
year                    1998
population       8.28742e+06
state             New Jersey
area (sq. mi)           8722
Name: 1473, dtype: object
state/region              NJ
ages                   total
year                    1995
population       8.08324e+06
state             New Jersey
area (sq. mi)           8722
Name: 1474, dtype: object
state/region              NJ
ages                 under18
year                    1995
population       1.99719e+06
state             New Jersey
area (sq. mi)           8722
Name: 1475, dtype: object
state/region             NJ
ages                under18
year                   1996
population       2.0165e+06
state            New Jersey
area (sq. mi)          8722
Name: 1476, dtype: object
state/region             NJ
ages                  total
year                   1996
population       8.1496e+06
state            New Jersey
area (sq. mi)          8722
Name: 1477, dtype: object
state/region              NJ
ages                 under18
year                    1992
population       1.89011e+06
state             New Jersey
area (sq. mi)           8722
Name: 1478, dtype: object
state/region              NJ
ages                   total
year                    1992
population       7.88051e+06
state             New Jersey
area (sq. mi)           8722
Name: 1479, dtype: object
state/region              NJ
ages                   total
year                    1993
population       7.94892e+06
state             New Jersey
area (sq. mi)           8722
Name: 1480, dtype: object
state/region              NJ
ages                 under18
year                    1993
population       1.92862e+06
state             New Jersey
area (sq. mi)           8722
Name: 1481, dtype: object
state/region              NJ
ages                 under18
year                    1994
population       1.96823e+06
state             New Jersey
area (sq. mi)           8722
Name: 1482, dtype: object
state/region              NJ
ages                   total
year                    1994
population       8.01431e+06
state             New Jersey
area (sq. mi)           8722
Name: 1483, dtype: object
state/region              NJ
ages                   total
year                    1991
population       7.81468e+06
state             New Jersey
area (sq. mi)           8722
Name: 1484, dtype: object
state/region              NJ
ages                 under18
year                    1991
population       1.84960e+06
state             New Jersey
area (sq. mi)           8722
Name: 1485, dtype: object
state/region              NJ
ages                 under18
year                    1990
population       1.81819e+06
state             New Jersey
area (sq. mi)           8722
Name: 1486, dtype: object
state/region              NJ
ages                   total
year                    1990
population       7.76296e+06
state             New Jersey
area (sq. mi)           8722
Name: 1487, dtype: object
state/region              NM
ages                   total
year                    1990
population       1.52157e+06
state             New Mexico
area (sq. mi)         121593
Name: 1488, dtype: object
state/region             NM
ages                under18
year                   1990
population           453538
state            New Mexico
area (sq. mi)        121593
Name: 1489, dtype: object
state/region             NM

Name: 1501, dtype: object
state/region             NM
ages                under18
year                   1998
population           512801
state            New Mexico
area (sq. mi)        121593
Name: 1502, dtype: object
state/region              NM
ages                   total
year                    1998
population       1.79348e+06
state             New Mexico
area (sq. mi)         121593
Name: 1503, dtype: object
state/region              NM
ages                   total
year                    1997
population       1.77484e+06
state             New Mexico
area (sq. mi)         121593
Name: 1504, dtype: object
state/region             NM
ages                under18
year                   1997
population           514500
state            New Mexico
area (sq. mi)        121593
Name: 1505, dtype: object
state/region             NM
ages                under18
year                   1999
population           511135
state            New Mexico
area (sq. mi)        121593
Name: 1506, dtype: object
state/region              NM
ages                   total
year                    1999
population       1.80808e+06
state             New Mexico
area (sq. mi)         121593
Name: 1507, dtype: object
state/region             NM
ages                  total
year                   2000
population       1.8212e+06
state            New Mexico
area (sq. mi)        121593
Name: 1508, dtype: object
state/region             NM
ages                under18
year                   2000
population           508132
state            New Mexico
area (sq. mi)        121593
Name: 1509, dtype: object
state/region              NM
ages                   total
year                    2001
population       1.83169e+06
state             New Mexico
area (sq. mi)         121593
Name: 1510, dtype: object
state/region             NM
ages                under18
year                   2001
population           503404
state            New Mexico
area (sq. mi)        121593
Name: 1511, dtype: object
state/region              NM
ages                   total
year                    2002
population       1.85531e+06
state             New Mexico
area (sq. mi)         121593
Name: 1512, dtype: object
state/region             NM
ages                under18
year                   2002
population           502779
state            New Mexico
area (sq. mi)        121593
Name: 1513, dtype: object
state/region              NM
ages                   total
year                    2004
population       1.90381e+06
state             New Mexico
area (sq. mi)         121593
Name: 1514, dtype: object
state/region             NM
ages                under18
year                   2004
population           501184
state            New Mexico
area (sq. mi)        121593
Name: 1515, dtype: object
state/region              NM
ages                   total
year                    2003
population       1.87757e+06
state             New Mexico
area (sq. mi)         121593
Name: 1516, dtype: object
state/region             NM
ages                under18
year                   2003
population           500777
state            New Mexico
area (sq. mi)        121593
Name: 1517, dtype: object
state/region              NM
ages                   total
year                    2005
population       1.93227e+06
state             New Mexico
area (sq. mi)         121593
Name: 1518, dtype: object
state/region             NM
ages                under18
year                   2005
population           502612
state            New Mexico
area (sq. mi)        121593
Name: 1519, dtype: object
state/region              NM
ages                   total
year                    2006
population       1.96214e+06
state             New Mexico
area (sq. mi)         121593
Name: 1520, dtype: object
state/region             NM
ages                under18
year                   2006
population           505125
state            New Mexico
area (sq. mi)        121593
Name: 1521, dtype: object
state/region              NM
ages                   total
year                    2008
population       2.01066e+06
state             New Mexico
area (sq. mi)         121593
Name: 1522, dtype: object
state/region             NM
ages                under18
year                   2008
population           511214
state            New Mexico
area (sq. mi)        121593
Name: 1523, dtype: object
state/region              NM
ages                   total
year                    2007
population       1.99007e+06
state             New Mexico
area (sq. mi)         121593
Name: 1524, dtype: object
state/region             NM
ages                under18
year                   2007
population           508725
state            New Mexico
area (sq. mi)        121593
Name: 1525, dtype: object
state/region             NM
ages                under18
year                   2013
population           507540
state            New Mexico
area (sq. mi)        121593
Name: 1526, dtype: object
state/region              NM
ages                   total
year                    2013
population       2.08529e+06
state             New Mexico
area (sq. mi)         121593
Name: 1527, dtype: object
state/region             NM
ages                  total
year                   2009
population       2.0368e+06
state            New Mexico
area (sq. mi)        121593
Name: 1528, dtype: object
state/region             NM
ages                under18
year                   2009
population           515470
state            New Mexico
area (sq. mi)        121593
Name: 1529, dtype: object
state/region              NM
ages                   total
year                    2010
population       2.06498e+06
state             New Mexico
area (sq. mi)         121593
Name: 1530, dtype: object
state/region             NM
ages                under18
year                   2010
population           518763
state            New Mexico
area (sq. mi)        121593
Name: 1531, dtype: object
state/region             NM
ages                under18
year                   2011
population           516513
state            New Mexico
area (sq. mi)        121593
Name: 1532, dtype: object
state/region              NM
ages                   total
year                    2011
population       2.07792e+06
state             New Mexico
area (sq. mi)         121593
Name: 1533, dtype: object
state/region             NM
ages                under18
year                   2012
population           512314
state            New Mexico
area (sq. mi)        121593
Name: 1534, dtype: object
state/region              NM
ages                   total
year                    2012
population       2.08354e+06
state             New Mexico
area (sq. mi)         121593
Name: 1535, dtype: object
state/region              NY
ages                   total
year                    2012
population       1.95761e+07
state               New York
area (sq. mi)          54475
Name: 1536, dtype: object
state/region              NY
ages                 under18
year                    2012
population       4.26469e+06
state               New York
area (sq. mi)          54475
Name: 1537, dtype: object
state/region              NY
ages                   total
year                    2011
population       1.95027e+07
state               New York
area (sq. mi)          54475
Name: 1538, dtype: object
state/region              NY
ages                 under18
year                    2011
population       4.29456e+06
state               New York
area (sq. mi)          54475
Name: 1539, dtype: object
state/region              NY
ages                 under18
year                    2010
population       4.31803e+06
state               New York
area (sq. mi)          54475
Name: 1540, dtype: object
state/region              NY
ages                   total
year                    2010
population       1.93982e+07
state               New York
area (sq. mi)          54475
Name: 1541, dtype: object
state/region              NY
ages                   total
year                    2009
population       1.93071e+07
state               New York
area (sq. mi)          54475
Name: 1542, dtype: object
state/region              NY
ages                 under18
year                    2009
population       4.34293e+06
state               New York
area (sq. mi)          54475
Name: 1543, dtype: object
state/region              NY
ages                   total
year                    2013
population       1.96511e+07
state               New York
area (sq. mi)          54475
Name: 1544, dtype: object
state/region              NY
ages                 under18
year                    2013
population       4.23998e+06
state               New York
area (sq. mi)          54475
Name: 1545, dtype: object
state/region              NY
ages                   total
year                    2007
population       1.91323e+07
state               New York
area (sq. mi)          54475
Name: 1546, dtype: object
state/region              NY
ages                 under18
year                    2007
population       4.41095e+06
state               New York
area (sq. mi)          54475
Name: 1547, dtype: object
state/region              NY
ages                   total
year                    2008
population       1.92124e+07
state               New York
area (sq. mi)          54475
Name: 1548, dtype: object
state/region              NY
ages                 under18
year                    2008
population       4.37217e+06
state               New York
area (sq. mi)          54475
Name: 1549, dtype: object
state/region              NY
ages                   total
year                    2006
population       1.91046e+07
state               New York
area (sq. mi)          54475
Name: 1550, dtype: object
state/region              NY
ages                 under18
year                    2006
population       4.45778e+06
state               New York
area (sq. mi)          54475
Name: 1551, dtype: object
state/region              NY
ages                   total
year                    2005
population       1.91326e+07
state               New York
area (sq. mi)          54475
Name: 1552, dtype: object
state/region              NY
ages                 under18
year                    2005
population       4.51446e+06
state               New York
area (sq. mi)          54475
Name: 1553, dtype: object
state/region              NY
ages                   total
year                    2003
population       1.91759e+07
state               New York
area (sq. mi)          54475
Name: 1554, dtype: object
state/region              NY
ages                 under18
year                    2003
population       4.61951e+06
state               New York
area (sq. mi)          54475
Name: 1555, dtype: object
state/region              NY
ages                   total
year                    2004
population       1.91716e+07
state               New York
area (sq. mi)          54475
Name: 1556, dtype: object
state/region              NY
ages                 under18
year                    2004
population       4.57406e+06
state               New York
area (sq. mi)          54475
Name: 1557, dtype: object
state/region              NY
ages                   total
year                    2002
population       1.91378e+07
state               New York
area (sq. mi)          54475
Name: 1558, dtype: object
state/region              NY
ages                 under18
year                    2002
population       4.65223e+06
state               New York
area (sq. mi)          54475
Name: 1559, dtype: object
state/region              NY
ages                   total
year                    2001
population       1.90828e+07
state               New York
area (sq. mi)          54475
Name: 1560, dtype: object
state/region              NY
ages                 under18
year                    2001
population       4.67242e+06
state               New York
area (sq. mi)          54475
Name: 1561, dtype: object
state/region              NY
ages                 under18
year                    1999
population       4.67259e+06
state               New York
area (sq. mi)          54475
Name: 1562, dtype: object
state/region              NY
ages                   total
year                    1999
population       1.88827e+07
state               New York
area (sq. mi)          54475
Name: 1563, dtype: object
state/region              NY
ages                   total
year                    2000
population       1.90018e+07
state               New York
area (sq. mi)          54475
Name: 1564, dtype: object
state/region              NY
ages                 under18
year                    2000
population       4.68737e+06
state               New York
area (sq. mi)          54475
Name: 1565, dtype: object
state/region              NY
ages                 under18
year                    1997
population       4.67079e+06
state               New York
area (sq. mi)          54475
Name: 1566, dtype: object
state/region              NY
ages                   total
year                    1997
population       1.86565e+07
state               New York
area (sq. mi)          54475
Name: 1567, dtype: object
state/region              NY
ages                   total
year                    1998
population       1.87559e+07
state               New York
area (sq. mi)          54475
Name: 1568, dtype: object
state/region              NY
ages                 under18
year                    1998
population       4.65214e+06
state               New York
area (sq. mi)          54475
Name: 1569, dtype: object
state/region              NY
ages                   total
year                    1996
population       1.85885e+07
state               New York
area (sq. mi)          54475
Name: 1570, dtype: object
state/region              NY
ages                 under18
year                    1995
population       4.64842e+06
state               New York
area (sq. mi)          54475
Name: 1571, dtype: object
state/region              NY
ages                   total
year                    1995
population       1.85241e+07
state               New York
area (sq. mi)          54475
Name: 1572, dtype: object
state/region              NY
ages                 under18
year                    1996
population       4.66765e+06
state               New York
area (sq. mi)          54475
Name: 1573, dtype: object
state/region              NY
ages                   total
year                    1994
population       1.84595e+07
state               New York
area (sq. mi)          54475
Name: 1574, dtype: object
state/region              NY
ages                 under18
year                    1992
population       4.46554e+06
state               New York
area (sq. mi)          54475
Name: 1575, dtype: object
state/region              NY
ages                   total
year                    1992
population       1.82467e+07
state               New York
area (sq. mi)          54475
Name: 1576, dtype: object
state/region             NY
ages                  total
year                   1993
population       1.8375e+07
state              New York
area (sq. mi)         54475
Name: 1577, dtype: object
state/region              NY
ages                 under18
year                    1993
population       4.53817e+06
state               New York
area (sq. mi)          54475
Name: 1578, dtype: object
state/region              NY
ages                 under18
year                    1994
population       4.60528e+06
state               New York
area (sq. mi)          54475
Name: 1579, dtype: object
state/region              NY
ages                   total
year                    1991
population       1.81225e+07
state               New York
area (sq. mi)          54475
Name: 1580, dtype: object
state/region              NY
ages                 under18
year                    1991
population       4.37273e+06
state               New York
area (sq. mi)          54475
Name: 1581, dtype: object
state/region              NY
ages                 under18
year                    1990
population       4.28164e+06
state               New York
area (sq. mi)          54475
Name: 1582, dtype: object
state/region              NY
ages                   total
year                    1990
population       1.80208e+07
state               New York
area (sq. mi)          54475
Name: 1583, dtype: object
state/region                 NC
ages                    under18
year                       1990
population           1.6258e+06
state            North Carolina
area (sq. mi)             53821
Name: 1584, dtype: object
state/region                 NC
ages                      total
year                       1990
population          6.66402e+06
state            North Carolina
area (sq. mi)             53821
Name: 1585, dtype: object
state/region                 NC
ages                      total
year                       1991
population          6.78428e+06
state            North Carolina
area (sq. mi)             53821
Name: 1586, dtype: object
state/region                 NC
ages                    under18
year                       1991
population          1.64039e+06
state            North Carolina
area (sq. mi)             53821
Name: 1587, dtype: object
state/region                 NC
ages                      total
year                       1993
population          7.04282e+06
state            North Carolina
area (sq. mi)             53821
Name: 1588, dtype: object
state/region                 NC
ages                    under18
year                       1993
population          1.71027e+06
state            North Carolina
area (sq. mi)             53821
Name: 1589, dtype: object
state/region                 NC
ages                    under18
year                       1992
population          1.67414e+06
state            North Carolina
area (sq. mi)             53821
Name: 1590, dtype: object
state/region                 NC
ages                      total
year                       1992
population          6.89721e+06
state            North Carolina
area (sq. mi)             53821
Name: 1591, dtype: object
state/region                 NC
ages                    under18
year                       1994
population          1.75075e+06
state            North Carolina
area (sq. mi)             53821
Name: 1592, dtype: object
state/region                 NC
ages                      total
year                       1994
population           7.1874e+06
state            North Carolina
area (sq. mi)             53821
Name: 1593, dtype: object
state/region                 NC
ages                      total
year                       1995
population          7.34467e+06
state            North Carolina
area (sq. mi)             53821
Name: 1594, dtype: object
state/region                 NC
ages                    under18
year                       1995
population          1.78515e+06
state            North Carolina
area (sq. mi)             53821
Name: 1595, dtype: object
state/region                 NC
ages                    under18
year                       1996
population          1.82151e+06
state            North Carolina
area (sq. mi)             53821
Name: 1596, dtype: object
state/region                 NC
ages                      total
year                       1996
population          7.50067e+06
state            North Carolina
area (sq. mi)             53821
Name: 1597, dtype: object
state/region                 NC
ages                    under18
year                       1998
population          1.89475e+06
state            North Carolina
area (sq. mi)             53821
Name: 1598, dtype: object
state/region                 NC
ages                      total
year                       1998
population          7.80912e+06
state            North Carolina
area (sq. mi)             53821
Name: 1599, dtype: object
state/region                 NC
ages                      total
year                       1997
population          7.65682e+06
state            North Carolina
area (sq. mi)             53821

state/region                 NC
ages                      total
year                       2000
population          8.08161e+06
state            North Carolina
area (sq. mi)             53821
Name: 1602, dtype: object
state/region                 NC
ages                    under18
year                       2000
population          1.96763e+06
state            North Carolina
area (sq. mi)             53821
Name: 1603, dtype: object
state/region                 NC
ages                      total
year                       1999
population          7.94936e+06
state            North Carolina
area (sq. mi)             53821
Name: 1604, dtype: object
state/region                 NC
ages                    under18
year                       1999
population          1.93214e+06
state            North Carolina
area (sq. mi)             53821
Name: 1605, dtype: object
state/region                 NC
ages                      total
year                       2001
population          8.21012e+06
state            North Carolina
area (sq. mi)             53821
Name: 1606, dtype: object
state/region                 NC
ages                    under18
year                       2001
population          2.00378e+06
state            North Carolina
area (sq. mi)             53821
Name: 1607, dtype: object
state/region                 NC
ages                      total
year                       2002
population           8.3262e+06
state            North Carolina
area (sq. mi)             53821
Name: 1608, dtype: object
state/region                 NC
ages                    under18
year                       2002
population          2.03445e+06
state            North Carolina
area (sq. mi)             53821
Name: 1609, dtype: object
state/region                 NC
ages                      total
year                       2004
population          8.55315e+06
state            North Carolina
area (sq. mi)             53821
Name: 1610, dtype: object
state/region                 NC
ages                    under18
year                       2004
population          2.08516e+06
state            North Carolina
area (sq. mi)             53821
Name: 1611, dtype: object
state/region                 NC
ages                      total
year                       2003
population           8.4225e+06
state            North Carolina
area (sq. mi)             53821
Name: 1612, dtype: object
state/region                 NC
ages                    under18
year                       2003
population          2.06084e+06
state            North Carolina
area (sq. mi)             53821
Name: 1613, dtype: object
state/region                 NC
ages                      total
year                       2005
population          8.70541e+06
state            North Carolina
area (sq. mi)             53821
Name: 1614, dtype: object
state/region                 NC
ages                    under18
year                       2005
population          2.12248e+06
state            North Carolina
area (sq. mi)             53821
Name: 1615, dtype: object
state/region                 NC
ages                      total
year                       2006
population          8.91727e+06
state            North Carolina
area (sq. mi)             53821
Name: 1616, dtype: object
state/region                 NC
ages                    under18
year                       2006
population          2.16639e+06
state            North Carolina
area (sq. mi)             53821
Name: 1617, dtype: object
state/region                 NC
ages                      total
year                       2008
population          9.30945e+06
state            North Carolina
area (sq. mi)             53821
Name: 1618, dtype: object
state/region                 NC
ages                    under18
year                       2008
population           2.2521e+06
state            North Carolina
area (sq. mi)             53821
Name: 1619, dtype: object
state/region                 NC
ages                      total
year                       2007
population          9.11804e+06
state            North Carolina
area (sq. mi)             53821
Name: 1620, dtype: object
state/region                 NC
ages                    under18
year                       2007
population          2.21917e+06
state            North Carolina
area (sq. mi)             53821
Name: 1621, dtype: object
state/region                 NC
ages                    under18
year                       2013
population          2.28560e+06
state            North Carolina
area (sq. mi)             53821
Name: 1622, dtype: object
state/region                 NC
ages                      total
year                       2013
population          9.84806e+06
state            North Carolina
area (sq. mi)             53821
Name: 1623, dtype: object
state/region                 NC
ages                      total
year                       2009
population          9.44957e+06
state            North Carolina
area (sq. mi)             53821
Name: 1624, dtype: object
state/region                 NC
ages                    under18
year                       2009
population          2.27296e+06
state            North Carolina
area (sq. mi)             53821
Name: 1625, dtype: object
state/region                 NC
ages                      total
year                       2010
population          9.55953e+06
state            North Carolina
area (sq. mi)             53821
Name: 1626, dtype: object
state/region                 NC
ages                    under18
year                       2010
population          2.28229e+06
state            North Carolina
area (sq. mi)             53821
Name: 1627, dtype: object
state/region                 NC
ages                    under18
year                       2011
population          2.28424e+06
state            North Carolina
area (sq. mi)             53821
Name: 1628, dtype: object
state/region                 NC
ages                      total
year                       2011
population          9.65138e+06
state            North Carolina
area (sq. mi)             53821
Name: 1629, dtype: object
state/region                 NC
ages                    under18
year                       2012
population          2.28412e+06
state            North Carolina
area (sq. mi)             53821
Name: 1630, dtype: object
state/region                 NC
ages                      total
year                       2012
population          9.74836e+06
state            North Carolina
area (sq. mi)             53821
Name: 1631, dtype: object
state/region               ND
ages                    total
year                     2012
population             701345
state            North Dakota
area (sq. mi)           70704
Name: 1632, dtype: object
state/region               ND
ages                  under18
year                     2012
population             156765
state            North Dakota
area (sq. mi)           70704
Name: 1633, dtype: object
state/region               ND
ages                    total
year                     2011
population             684867
state            North Dakota
area (sq. mi)           70704
Name: 1634, dtype: object
state/region               ND
ages                  under18
year                     2011
population             152357
state            North Dakota
area (sq. mi)           70704
Name: 1635, dtype: object
state/region               ND
ages                  under18
year                     2010
population             150179
state            North Dakota
area (sq. mi)           70704
Name: 1636, dtype: object
state/region               ND
ages                    total
year                     2010
population             674344
state            North Dakota
area (sq. mi)           70704
Name: 1637, dtype: object
state/region               ND
ages                    total
year                     2009
population             664968
state            North Dakota
area (sq. mi)           70704
Name: 1638, dtype: object
state/region               ND
ages                  under18
year                     2009
population             148674
state            North Dakota
area (sq. mi)           70704
Name: 1639, dtype: object
state/region               ND
ages                    total
year                     2013
population             723393
state            North Dakota
area (sq. mi)           70704
Name: 1640, dtype: object
state/region               ND
ages                  under18
year                     2013
population             162688
state            North Dakota
area (sq. mi)           70704
Name: 1641, dtype: object
state/region               ND
ages                    total
year                     2007
population             652822
state            North Dakota
area (sq. mi)           70704
Name: 1642, dtype: object
state/region               ND
ages                  under18
year                     2007
population             147263
state            North Dakota
area (sq. mi)           70704
Name: 1643, dtype: object
state/region               ND
ages                    total
year                     2008
population             657569
state            North Dakota
area (sq. mi)           70704
Name: 1644, dtype: object
state/region               ND
ages                  under18
year                     2008
population             147462
state            North Dakota
area (sq. mi)           70704
Name: 1645, dtype: object
state/region               ND
ages                    total
year                     2006
population             649422
state            North Dakota
area (sq. mi)           70704

Name: 1646, dtype: object
state/region               ND
ages                  under18
year                     2006
population             147331
state            North Dakota
area (sq. mi)           70704
Name: 1647, dtype: object
state/region               ND
ages                    total
year                     2005
population             646089
state            North Dakota
area (sq. mi)           70704
Name: 1648, dtype: object
state/region               ND
ages                  under18
year                     2005
population             148119
state            North Dakota
area (sq. mi)           70704
Name: 1649, dtype: object
state/region               ND
ages                    total
year                     2003
population             638817
state            North Dakota
area (sq. mi)           70704
Name: 1650, dtype: object
state/region               ND
ages                  under18
year                     2003
population             150406
state            North Dakota
area (sq. mi)           70704
Name: 1651, dtype: object
state/region               ND
ages                    total
year                     2004
population             644705
state            North Dakota
area (sq. mi)           70704
Name: 1652, dtype: object
state/region               ND
ages                  under18
year                     2004
population             149128
state            North Dakota
area (sq. mi)           70704
Name: 1653, dtype: object
state/region               ND
ages                    total
year                     2002
population             638168
state            North Dakota
area (sq. mi)           70704
Name: 1654, dtype: object
state/region               ND
ages                  under18
year                     2002
population             153097
state            North Dakota
area (sq. mi)           70704
Name: 1655, dtype: object
state/region               ND
ages                    total
year                     2001
population             639062
state            North Dakota
area (sq. mi)           70704
Name: 1656, dtype: object
state/region               ND
ages                  under18
year                     2001
population             156113
state            North Dakota
area (sq. mi)           70704
Name: 1657, dtype: object
state/region               ND
ages                    total
year                     1999
population             644259
state            North Dakota
area (sq. mi)           70704
Name: 1658, dtype: object
state/region               ND
ages                  under18
year                     1999
population             163056
state            North Dakota
area (sq. mi)           70704
Name: 1659, dtype: object
state/region               ND
ages                    total
year                     2000
population             642023
state            North Dakota
area (sq. mi)           70704
Name: 1660, dtype: object
state/region               ND
ages                  under18
year                     2000
population             160477
state            North Dakota
area (sq. mi)           70704
Name: 1661, dtype: object
state/region               ND
ages                    total
year                     1997
population             649716
state            North Dakota
area (sq. mi)           70704
Name: 1662, dtype: object
state/region               ND
ages                  under18
year                     1997
population             167475
state            North Dakota
area (sq. mi)           70704
Name: 1663, dtype: object
state/region               ND
ages                  under18
year                     1998
population             165448
state            North Dakota
area (sq. mi)           70704
Name: 1664, dtype: object
state/region               ND
ages                    total
year                     1998
population             647532
state            North Dakota
area (sq. mi)           70704
Name: 1665, dtype: object
state/region               ND
ages                  under18
year                     1996
population             169257
state            North Dakota
area (sq. mi)           70704
Name: 1666, dtype: object
state/region               ND
ages                    total
year                     1996
population             650382
state            North Dakota
area (sq. mi)           70704
Name: 1667, dtype: object
state/region               ND
ages                    total
year                     1995
population             647832
state            North Dakota
area (sq. mi)           70704
Name: 1668, dtype: object
state/region               ND
ages                  under18
year                     1995
population             171146
state            North Dakota
area (sq. mi)           70704
Name: 1669, dtype: object
state/region               ND
ages                  under18
year                     1994
population             172160
state            North Dakota
area (sq. mi)           70704
Name: 1670, dtype: object
state/region               ND
ages                    total
year                     1994
population             644806
state            North Dakota
area (sq. mi)           70704
Name: 1671, dtype: object
state/region               ND
ages                  under18
year                     1992
population             172052
state            North Dakota
area (sq. mi)           70704
Name: 1672, dtype: object
state/region               ND
ages                    total
year                     1992
population             638223
state            North Dakota
area (sq. mi)           70704
Name: 1673, dtype: object
state/region               ND
ages                    total
year                     1993
population             641216
state            North Dakota
area (sq. mi)           70704
Name: 1674, dtype: object
state/region               ND
ages                  under18
year                     1993
population             172168
state            North Dakota
area (sq. mi)           70704
Name: 1675, dtype: object
state/region               ND
ages                    total
year                     1991
population             635753
state            North Dakota
area (sq. mi)           70704
Name: 1676, dtype: object
state/region               ND
ages                  under18
year                     1991
population             171730
state            North Dakota
area (sq. mi)           70704
Name: 1677, dtype: object
state/region               ND
ages                  under18
year                     1990
population             170920
state            North Dakota
area (sq. mi)           70704
Name: 1678, dtype: object
state/region               ND
ages                    total
year                     1990
population             637685
state            North Dakota
area (sq. mi)           70704
Name: 1679, dtype: object
state/region              OH
ages                 under18
year                    1990
population       2.77849e+06
state                   Ohio
area (sq. mi)          44828
Name: 1680, dtype: object
state/region              OH
ages                   total
year                    1990
population       1.08642e+07
state                   Ohio
area (sq. mi)          44828
Name: 1681, dtype: object
state/region              OH
ages                   total
year                    1991
population       1.09458e+07
state                   Ohio
area (sq. mi)          44828
Name: 1682, dtype: object
state/region              OH
ages                 under18
year                    1991
population       2.80696e+06
state                   Ohio
area (sq. mi)          44828
Name: 1683, dtype: object
state/region              OH
ages                   total
year                    1993
population       1.11011e+07
state                   Ohio
area (sq. mi)          44828
Name: 1684, dtype: object
state/region              OH
ages                 under18
year                    1993
population       2.85578e+06
state                   Ohio
area (sq. mi)          44828
Name: 1685, dtype: object
state/region              OH
ages                 under18
year                    1992
population       2.83936e+06
state                   Ohio
area (sq. mi)          44828
Name: 1686, dtype: object
state/region              OH
ages                   total
year                    1992
population       1.10294e+07
state                   Ohio
area (sq. mi)          44828
Name: 1687, dtype: object
state/region             OH
ages                under18
year                   1994
population       2.8754e+06
state                  Ohio
area (sq. mi)         44828
Name: 1688, dtype: object
state/region              OH
ages                   total
year                    1994
population       1.11525e+07
state                   Ohio
area (sq. mi)          44828
Name: 1689, dtype: object
state/region              OH
ages                   total
year                    1995
population       1.12028e+07
state                   Ohio
area (sq. mi)          44828
Name: 1690, dtype: object
state/region              OH
ages                 under18
year                    1995
population       2.87993e+06
state                   Ohio
area (sq. mi)          44828
Name: 1691, dtype: object
state/region              OH
ages                 under18
year                    1996
population       2.88344e+06
state                   Ohio
area (sq. mi)          44828
Name: 1692, dtype: object
state/region              OH
ages                   total
year                    1996
population       1.12428e+07
state                   Ohio
area (sq. mi)          44828
Name: 1693, dtype: object
state/region              OH
ages                 under18
year                    1998
population       2.89626e+06
state                   Ohio
area (sq. mi)          44828
Name: 1694, dtype: object
state/region              OH
ages                   total
year                    1998
population       1.13115e+07
state                   Ohio
area (sq. mi)          44828
Name: 1695, dtype: object
state/region              OH
ages                   total
year                    1997
population       1.12774e+07
state                   Ohio
area (sq. mi)          44828
Name: 1696, dtype: object
state/region              OH
ages                 under18
year                    1997
population       2.89738e+06
state                   Ohio
area (sq. mi)          44828
Name: 1697, dtype: object
state/region              OH
ages                   total
year                    2000
population       1.13635e+07
state                   Ohio
area (sq. mi)          44828
Name: 1698, dtype: object
state/region              OH
ages                 under18
year                    2000
population       2.88658e+06
state                   Ohio
area (sq. mi)          44828
Name: 1699, dtype: object
state/region              OH
ages                   total
year                    1999
population       1.13355e+07
state                   Ohio
area (sq. mi)          44828
Name: 1700, dtype: object
state/region              OH
ages                 under18
year                    1999
population       2.89327e+06
state                   Ohio
area (sq. mi)          44828
Name: 1701, dtype: object
state/region              OH
ages                   total
year                    2001
population       1.13874e+07
state                   Ohio
area (sq. mi)          44828
Name: 1702, dtype: object
state/region              OH
ages                 under18
year                    2001
population       2.87812e+06
state                   Ohio
area (sq. mi)          44828
Name: 1703, dtype: object
state/region              OH
ages                   total
year                    2002
population       1.14079e+07
state                   Ohio
area (sq. mi)          44828
Name: 1704, dtype: object
state/region              OH
ages                 under18
year                    2002
population       2.86567e+06
state                   Ohio
area (sq. mi)          44828
Name: 1705, dtype: object
state/region              OH
ages                   total
year                    2004
population       1.14523e+07
state                   Ohio
area (sq. mi)          44828

Name: 1706, dtype: object
state/region              OH
ages                 under18
year                    2004
population       2.83607e+06
state                   Ohio
area (sq. mi)          44828
Name: 1707, dtype: object
state/region              OH
ages                   total
year                    2003
population       1.14348e+07
state                   Ohio
area (sq. mi)          44828
Name: 1708, dtype: object
state/region              OH
ages                 under18
year                    2003
population       2.84957e+06
state                   Ohio
area (sq. mi)          44828
Name: 1709, dtype: object
state/region              OH
ages                   total
year                    2005
population       1.14633e+07
state                   Ohio
area (sq. mi)          44828
Name: 1710, dtype: object
state/region              OH
ages                 under18
year                    2005
population       2.81979e+06
state                   Ohio
area (sq. mi)          44828
Name: 1711, dtype: object
state/region              OH
ages                   total
year                    2006
population       1.14812e+07
state                   Ohio
area (sq. mi)          44828
Name: 1712, dtype: object
state/region              OH
ages                 under18
year                    2006
population       2.80483e+06
state                   Ohio
area (sq. mi)          44828
Name: 1713, dtype: object
state/region              OH
ages                   total
year                    2008
population       1.15154e+07
state                   Ohio
area (sq. mi)          44828
Name: 1714, dtype: object
state/region              OH
ages                 under18
year                    2008
population       2.76897e+06
state                   Ohio
area (sq. mi)          44828
Name: 1715, dtype: object
state/region              OH
ages                   total
year                    2007
population       1.15005e+07
state                   Ohio
area (sq. mi)          44828
Name: 1716, dtype: object
state/region              OH
ages                 under18
year                    2007
population       2.79035e+06
state                   Ohio
area (sq. mi)          44828
Name: 1717, dtype: object
state/region              OH
ages                 under18
year                    2013
population       2.64983e+06
state                   Ohio
area (sq. mi)          44828
Name: 1718, dtype: object
state/region              OH
ages                   total
year                    2013
population       1.15708e+07
state                   Ohio
area (sq. mi)          44828
Name: 1719, dtype: object
state/region              OH
ages                   total
year                    2009
population       1.15289e+07
state                   Ohio
area (sq. mi)          44828
Name: 1720, dtype: object
state/region              OH
ages                 under18
year                    2009
population       2.74805e+06
state                   Ohio
area (sq. mi)          44828
Name: 1721, dtype: object
state/region              OH
ages                   total
year                    2010
population       1.15454e+07
state                   Ohio
area (sq. mi)          44828
Name: 1722, dtype: object
state/region              OH
ages                 under18
year                    2010
population       2.72259e+06
state                   Ohio
area (sq. mi)          44828
Name: 1723, dtype: object
state/region              OH
ages                 under18
year                    2011
population       2.69347e+06
state                   Ohio
area (sq. mi)          44828
Name: 1724, dtype: object
state/region              OH
ages                   total
year                    2011
population       1.15498e+07
state                   Ohio
area (sq. mi)          44828
Name: 1725, dtype: object
state/region              OH
ages                 under18
year                    2012
population       2.66812e+06
state                   Ohio
area (sq. mi)          44828
Name: 1726, dtype: object
state/region             OH
ages                  total
year                   2012
population       1.1553e+07
state                  Ohio
area (sq. mi)         44828
Name: 1727, dtype: object
state/region              OK
ages                   total
year                    2012
population       3.81578e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1728, dtype: object
state/region           OK
ages              under18
year                 2012
population         939911
state            Oklahoma
area (sq. mi)       69903
Name: 1729, dtype: object
state/region              OK
ages                   total
year                    2011
population       3.78553e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1730, dtype: object
state/region           OK
ages              under18
year                 2011
population         935714
state            Oklahoma
area (sq. mi)       69903
Name: 1731, dtype: object
state/region           OK
ages              under18
year                 2010
population         931483
state            Oklahoma
area (sq. mi)       69903
Name: 1732, dtype: object
state/region              OK
ages                   total
year                    2010
population       3.75926e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1733, dtype: object
state/region              OK
ages                   total
year                    2009
population       3.71757e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1734, dtype: object
state/region           OK
ages              under18
year                 2009
population         922711
state            Oklahoma
area (sq. mi)       69903
Name: 1735, dtype: object
state/region              OK
ages                   total
year                    2013
population       3.85057e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1736, dtype: object
state/region           OK
ages              under18
year                 2013
population         947027
state            Oklahoma
area (sq. mi)       69903
Name: 1737, dtype: object
state/region              OK
ages                   total
year                    2007
population       3.63435e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1738, dtype: object
state/region           OK
ages              under18
year                 2007
population         904328
state            Oklahoma
area (sq. mi)       69903
Name: 1739, dtype: object
state/region              OK
ages                   total
year                    2008
population       3.66898e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1740, dtype: object
state/region           OK
ages              under18
year                 2008
population         910617
state            Oklahoma
area (sq. mi)       69903
Name: 1741, dtype: object
state/region              OK
ages                   total
year                    2006
population       3.59409e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1742, dtype: object
state/region           OK
ages              under18
year                 2006
population         894761
state            Oklahoma
area (sq. mi)       69903
Name: 1743, dtype: object
state/region             OK
ages                  total
year                   2005
population       3.5486e+06
state              Oklahoma
area (sq. mi)         69903
Name: 1744, dtype: object
state/region           OK
ages              under18
year                 2005
population         885316
state            Oklahoma
area (sq. mi)       69903
Name: 1745, dtype: object
state/region              OK
ages                   total
year                    2003
population       3.50489e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1746, dtype: object
state/region           OK
ages              under18
year                 2003
population         883959
state            Oklahoma
area (sq. mi)       69903
Name: 1747, dtype: object
state/region              OK
ages                   total
year                    2004
population       3.52523e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1748, dtype: object
state/region           OK
ages              under18
year                 2004
population         881606
state            Oklahoma
area (sq. mi)       69903
Name: 1749, dtype: object
state/region              OK
ages                   total
year                    2002
population       3.48908e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1750, dtype: object
state/region           OK
ages              under18
year                 2002
population         884961
state            Oklahoma
area (sq. mi)       69903
Name: 1751, dtype: object
state/region             OK
ages                  total
year                   2001
population       3.4671e+06
state              Oklahoma
area (sq. mi)         69903
Name: 1752, dtype: object
state/region           OK
ages              under18
year                 2001
population         885218
state            Oklahoma
area (sq. mi)       69903
Name: 1753, dtype: object
state/region              OK
ages                   total
year                    1999
population       3.43715e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1754, dtype: object
state/region           OK
ages              under18
year                 1999
population         895678
state            Oklahoma
area (sq. mi)       69903
Name: 1755, dtype: object
state/region              OK
ages                   total
year                    2000
population       3.45436e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1756, dtype: object
state/region           OK
ages              under18
year                 2000
population         891847
state            Oklahoma
area (sq. mi)       69903
Name: 1757, dtype: object
state/region              OK
ages                   total
year                    1997
population       3.37292e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1758, dtype: object
state/region           OK
ages              under18
year                 1997
population         893835
state            Oklahoma
area (sq. mi)       69903
Name: 1759, dtype: object
state/region           OK
ages              under18
year                 1998
population         898501
state            Oklahoma
area (sq. mi)       69903
Name: 1760, dtype: object
state/region              OK
ages                   total
year                    1998
population       3.40519e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1761, dtype: object
state/region           OK
ages              under18
year                 1996
population         887093
state            Oklahoma
area (sq. mi)       69903
Name: 1762, dtype: object
state/region              OK
ages                   total
year                    1996
population       3.34013e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1763, dtype: object
state/region              OK
ages                   total
year                    1995
population       3.30821e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1764, dtype: object
state/region           OK
ages              under18
year                 1995
population         883667
state            Oklahoma
area (sq. mi)       69903
Name: 1765, dtype: object
state/region           OK
ages              under18
year                 1994
population         877803
state            Oklahoma
area (sq. mi)       69903
Name: 1766, dtype: object
state/region              OK
ages                   total
year                    1994
population       3.28094e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1767, dtype: object
state/region           OK
ages              under18
year                 1992
population         862548
state            Oklahoma
area (sq. mi)       69903
Name: 1768, dtype: object
state/region              OK
ages                   total
year                    1992
population       3.22052e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1769, dtype: object
state/region              OK
ages                   total
year                    1993
population       3.25228e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1770, dtype: object
state/region           OK
ages              under18
year                 1993
population         870137
state            Oklahoma
area (sq. mi)       69903
Name: 1771, dtype: object
state/region              OK
ages                   total
year                    1991
population       3.17544e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1772, dtype: object
state/region           OK
ages              under18
year                 1991
population         849639
state            Oklahoma
area (sq. mi)       69903
Name: 1773, dtype: object
state/region           OK
ages              under18
year                 1990
population         841715
state            Oklahoma
area (sq. mi)       69903
Name: 1774, dtype: object
state/region              OK
ages                   total
year                    1990
population       3.14882e+06
state               Oklahoma
area (sq. mi)          69903
Name: 1775, dtype: object
state/region          OR
ages             under18
year                1990
population        742436
state             Oregon
area (sq. mi)      98386
Name: 1776, dtype: object
state/region              OR
ages                   total
year                    1990
population       2.86038e+06
state                 Oregon
area (sq. mi)          98386
Name: 1777, dtype: object
state/region              OR
ages                   total
year                    1991
population       2.92851e+06
state                 Oregon
area (sq. mi)          98386
Name: 1778, dtype: object
state/region          OR
ages             under18
year                1991
population        752442
state             Oregon
area (sq. mi)      98386
Name: 1779, dtype: object
state/region              OR
ages                   total
year                    1993
population       3.06037e+06
state                 Oregon
area (sq. mi)          98386
Name: 1780, dtype: object
state/region          OR
ages             under18
year                1993
population        778973
state             Oregon
area (sq. mi)      98386
Name: 1781, dtype: object
state/region          OR
ages             under18
year                1992
population        770191
state             Oregon
area (sq. mi)      98386
Name: 1782, dtype: object
state/region              OR
ages                   total
year                    1992
population       2.99176e+06
state                 Oregon
area (sq. mi)          98386
Name: 1783, dtype: object
state/region          OR
ages             under18
year                1994
population        793435
state             Oregon
area (sq. mi)      98386
Name: 1784, dtype: object
state/region              OR
ages                   total
year                    1994
population       3.12126e+06
state                 Oregon
area (sq. mi)          98386
Name: 1785, dtype: object
state/region              OR
ages                   total
year                    1995
population       3.18437e+06
state                 Oregon
area (sq. mi)          98386
Name: 1786, dtype: object
state/region          OR
ages             under18
year                1995
population        806512
state             Oregon
area (sq. mi)      98386
Name: 1787, dtype: object
state/region          OR
ages             under18
year                1996
population        816102
state             Oregon
area (sq. mi)      98386
Name: 1788, dtype: object
state/region              OR
ages                   total
year                    1996
population       3.24711e+06
state                 Oregon
area (sq. mi)          98386
Name: 1789, dtype: object
state/region          OR
ages             under18
year                1998
population        837928
state             Oregon
area (sq. mi)      98386
Name: 1790, dtype: object
state/region              OR
ages                   total
year                    1998
population       3.35245e+06
state                 Oregon
area (sq. mi)          98386
Name: 1791, dtype: object
state/region              OR
ages                   total
year                    1997
population       3.30431e+06
state                 Oregon
area (sq. mi)          98386
Name: 1792, dtype: object
state/region          OR
ages             under18
year                1997
population        830002
state             Oregon
area (sq. mi)      98386
Name: 1793, dtype: object
state/region              OR
ages                   total
year                    2000
population       3.42971e+06
state                 Oregon
area (sq. mi)          98386
Name: 1794, dtype: object
state/region          OR
ages             under18
year                2000
population        847511
state             Oregon
area (sq. mi)      98386
Name: 1795, dtype: object
state/region              OR
ages                   total
year                    1999
population       3.39394e+06
state                 Oregon
area (sq. mi)          98386
Name: 1796, dtype: object
state/region          OR
ages             under18
year                1999
population        843484
state             Oregon
area (sq. mi)      98386
Name: 1797, dtype: object
state/region              OR
ages                   total
year                    2001
population       3.46794e+06
state                 Oregon
area (sq. mi)          98386
Name: 1798, dtype: object
state/region          OR
ages             under18
year                2001
population        848663
state             Oregon
area (sq. mi)      98386
Name: 1799, dtype: object
state/region              OR
ages                   total
year                    2002
population       3.51342e+06
state                 Oregon
area (sq. mi)          98386
Name: 1800, dtype: object
state/region          OR
ages             under18
year                2002
population        850733
state             Oregon
area (sq. mi)      98386
Name: 1801, dtype: object
state/region              OR
ages                   total
year                    2004
population       3.56946e+06
state                 Oregon
area (sq. mi)          98386
Name: 1802, dtype: object
state/region          OR
ages             under18
year                2004
population        846786
state             Oregon
area (sq. mi)      98386
Name: 1803, dtype: object
state/region              OR
ages                   total
year                    2003
population       3.54738e+06
state                 Oregon
area (sq. mi)          98386
Name: 1804, dtype: object
state/region          OR
ages             under18
year                2003
population        850251
state             Oregon
area (sq. mi)      98386
Name: 1805, dtype: object
state/region             OR
ages                  total
year                   2005
population       3.6132e+06
state                Oregon
area (sq. mi)         98386
Name: 1806, dtype: object
state/region          OR
ages             under18
year                2005
population        849323
state             Oregon
area (sq. mi)      98386
Name: 1807, dtype: object
state/region              OR
ages                   total
year                    2006
population       3.67088e+06
state                 Oregon
area (sq. mi)          98386
Name: 1808, dtype: object
state/region          OR
ages             under18
year                2006
population        857003
state             Oregon
area (sq. mi)      98386
Name: 1809, dtype: object
state/region              OR
ages                   total
year                    2008
population       3.76875e+06
state                 Oregon
area (sq. mi)          98386
Name: 1810, dtype: object
state/region          OR

state/region              OR
ages                   total
year                    2010
population       3.83721e+06
state                 Oregon
area (sq. mi)          98386
Name: 1818, dtype: object
state/region          OR
ages             under18
year                2010
population        865129
state             Oregon
area (sq. mi)      98386
Name: 1819, dtype: object
state/region          OR
ages             under18
year                2011
population        862518
state             Oregon
area (sq. mi)      98386
Name: 1820, dtype: object
state/region              OR
ages                   total
year                    2011
population       3.86794e+06
state                 Oregon
area (sq. mi)          98386
Name: 1821, dtype: object
state/region          OR
ages             under18
year                2012
population        859910
state             Oregon
area (sq. mi)      98386
Name: 1822, dtype: object
state/region             OR
ages                  total
year                   2012
population       3.8998e+06
state                Oregon
area (sq. mi)         98386
Name: 1823, dtype: object
state/region               PA
ages                    total
year                     2012
population        1.27645e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1824, dtype: object
state/region               PA
ages                  under18
year                     2012
population        2.73790e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1825, dtype: object
state/region               PA
ages                    total
year                     2011
population        1.27413e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1826, dtype: object
state/region               PA
ages                  under18
year                     2011
population        2.76134e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1827, dtype: object
state/region               PA
ages                  under18
year                     2010
population        2.78532e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1828, dtype: object
state/region               PA
ages                    total
year                     2010
population        1.27105e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1829, dtype: object
state/region               PA
ages                    total
year                     2009
population        1.26669e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1830, dtype: object
state/region               PA
ages                  under18
year                     2009
population        2.80493e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1831, dtype: object
state/region               PA
ages                    total
year                     2013
population        1.27738e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1832, dtype: object
state/region               PA
ages                  under18
year                     2013
population        2.71564e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1833, dtype: object
state/region               PA
ages                    total
year                     2007
population        1.25639e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1834, dtype: object
state/region               PA
ages                  under18
year                     2007
population        2.83957e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1835, dtype: object
state/region               PA
ages                    total
year                     2008
population        1.26123e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1836, dtype: object
state/region               PA
ages                  under18
year                     2008
population          2.821e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1837, dtype: object
state/region               PA
ages                    total
year                     2006
population        1.25108e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1838, dtype: object
state/region               PA
ages                  under18
year                     2006
population        2.85078e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1839, dtype: object
state/region               PA
ages                    total
year                     2005
population          1.245e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1840, dtype: object
state/region               PA
ages                  under18
year                     2005
population        2.85979e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1841, dtype: object
state/region               PA
ages                    total
year                     2003
population        1.23747e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1842, dtype: object
state/region               PA
ages                  under18
year                     2003
population        2.88327e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1843, dtype: object
state/region               PA
ages                    total
year                     2004
population        1.24107e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1844, dtype: object
state/region               PA
ages                  under18
year                     2004
population        2.87312e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1845, dtype: object
state/region               PA
ages                    total
year                     2002
population         1.2331e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1846, dtype: object
state/region               PA
ages                  under18
year                     2002
population        2.89494e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1847, dtype: object
state/region               PA
ages                    total
year                     2001
population         1.2299e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1848, dtype: object
state/region               PA
ages                  under18
year                     2001
population        2.90584e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1849, dtype: object
state/region               PA
ages                    total
year                     1999
population        1.22638e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1850, dtype: object
state/region               PA
ages                  under18
year                     1999
population        2.93019e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1851, dtype: object
state/region               PA
ages                    total
year                     2000
population        1.22842e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1852, dtype: object
state/region               PA
ages                  under18
year                     2000
population        2.91885e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1853, dtype: object
state/region               PA
ages                    total
year                     1997
population        1.22278e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1854, dtype: object
state/region               PA
ages                  under18
year                     1997
population        2.94224e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1855, dtype: object
state/region               PA
ages                  under18
year                     1998
population        2.94028e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1856, dtype: object
state/region               PA
ages                    total
year                     1998
population        1.22457e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1857, dtype: object
state/region               PA
ages                  under18
year                     1996
population        2.93741e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1858, dtype: object
state/region               PA
ages                    total
year                     1996
population        1.22205e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1859, dtype: object
state/region               PA
ages                    total
year                     1995
population        1.21984e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1860, dtype: object
state/region               PA
ages                  under18
year                     1995
population        2.94153e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1861, dtype: object
state/region               PA
ages                  under18
year                     1994
population        2.93285e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1862, dtype: object
state/region               PA
ages                    total
year                     1994
population        1.21660e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1863, dtype: object
state/region               PA
ages                  under18
year                     1992
population        2.87301e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1864, dtype: object
state/region               PA
ages                    total
year                     1992
population        1.20494e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1865, dtype: object
state/region               PA
ages                    total
year                     1993
population        1.21197e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1866, dtype: object
state/region               PA
ages                  under18
year                     1993
population        2.90735e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1867, dtype: object
state/region               PA
ages                    total
year                     1991
population        1.19822e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1868, dtype: object
state/region               PA
ages                  under18
year                     1991
population        2.83006e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1869, dtype: object
state/region               PA
ages                  under18
year                     1990
population        2.79917e+06
state            Pennsylvania
area (sq. mi)           46058
Name: 1870, dtype: object
state/region               PA
ages                    total
year                     1990
population        1.19033e+07
state            Pennsylvania
area (sq. mi)           46058
Name: 1871, dtype: object
state/region               RI
ages                  under18
year                     1990
population             225923
state            Rhode Island
area (sq. mi)            1545
Name: 1872, dtype: object
state/region               RI
ages                    total
year                     1990
population          1.006e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1873, dtype: object
state/region               RI
ages                    total
year                     1991
population        1.01065e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1874, dtype: object
state/region               RI
ages                  under18
year                     1991
population             229448
state            Rhode Island
area (sq. mi)            1545
Name: 1875, dtype: object
state/region               RI
ages                    total
year                     1993
population        1.01511e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1876, dtype: object
state/region               RI
ages                  under18
year                     1993
population             237218
state            Rhode Island
area (sq. mi)            1545
Name: 1877, dtype: object
state/region               RI
ages                  under18
year                     1992
population             232630
state            Rhode Island
area (sq. mi)            1545
Name: 1878, dtype: object
state/region               RI
ages                    total
year                     1992
population        1.01258e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1879, dtype: object
state/region               RI
ages                  under18
year                     1994
population             239100
state            Rhode Island
area (sq. mi)            1545
Name: 1880, dtype: object
state/region               RI
ages                    total
year                     1994
population        1.01596e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1881, dtype: object
state/region               RI
ages                    total
year                     1995
population          1.017e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1882, dtype: object
state/region               RI
ages                  under18
year                     1995
population             240553
state            Rhode Island
area (sq. mi)            1545
Name: 1883, dtype: object
state/region               RI
ages                  under18
year                     1996
population             240569
state            Rhode Island
area (sq. mi)            1545
Name: 1884, dtype: object
state/region               RI
ages                    total
year                     1996
population        1.02089e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1885, dtype: object
state/region               RI
ages                  under18
year                     1998
population             241760
state            Rhode Island
area (sq. mi)            1545
Name: 1886, dtype: object
state/region               RI
ages                    total
year                     1998
population        1.03116e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1887, dtype: object
state/region               RI
ages                    total
year                     1997
population        1.02535e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1888, dtype: object
state/region               RI
ages                  under18
year                     1997
population             242079
state            Rhode Island
area (sq. mi)            1545
Name: 1889, dtype: object
state/region               RI
ages                    total
year                     2000
population        1.05027e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1890, dtype: object
state/region               RI
ages                  under18
year                     2000
population             248065
state            Rhode Island
area (sq. mi)            1545
Name: 1891, dtype: object
state/region               RI
ages                    total
year                     1999
population         1.0404e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1892, dtype: object
state/region               RI
ages                  under18
year                     1999
population             247014
state            Rhode Island
area (sq. mi)            1545
Name: 1893, dtype: object
state/region               RI
ages                    total
year                     2001
population        1.05714e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1894, dtype: object
state/region               RI
ages                  under18
year                     2001
population             248296
state            Rhode Island
area (sq. mi)            1545
Name: 1895, dtype: object
state/region               RI
ages                    total
year                     2002
population          1.066e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1896, dtype: object
state/region               RI
ages                  under18
year                     2002
population             248690
state            Rhode Island
area (sq. mi)            1545
Name: 1897, dtype: object
state/region               RI
ages                    total
year                     2004
population        1.07458e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1898, dtype: object
state/region               RI
ages                  under18
year                     2004
population             246228
state            Rhode Island
area (sq. mi)            1545
Name: 1899, dtype: object
state/region               RI
ages                    total
year                     2003
population        1.07134e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1900, dtype: object
state/region               RI
ages                  under18
year                     2003
population             248075
state            Rhode Island
area (sq. mi)            1545
Name: 1901, dtype: object
state/region               RI
ages                    total
year                     2005
population        1.06792e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1902, dtype: object
state/region               RI
ages                  under18
year                     2005
population             241932
state            Rhode Island
area (sq. mi)            1545
Name: 1903, dtype: object
state/region               RI
ages                    total
year                     2006
population         1.0631e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1904, dtype: object
state/region               RI
ages                  under18
year                     2006
population             237348
state            Rhode Island
area (sq. mi)            1545
Name: 1905, dtype: object
state/region               RI
ages                    total
year                     2008
population          1.055e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1906, dtype: object
state/region               RI
ages                  under18
year                     2008
population             229798
state            Rhode Island
area (sq. mi)            1545
Name: 1907, dtype: object
state/region               RI
ages                    total
year                     2007
population        1.05732e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1908, dtype: object
state/region               RI
ages                  under18
year                     2007
population             233655
state            Rhode Island
area (sq. mi)            1545
Name: 1909, dtype: object
state/region               RI
ages                  under18
year                     2013
population             213987
state            Rhode Island
area (sq. mi)            1545
Name: 1910, dtype: object
state/region               RI
ages                    total
year                     2013
population        1.05151e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1911, dtype: object
state/region               RI
ages                    total
year                     2009
population        1.05365e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1912, dtype: object
state/region               RI
ages                  under18
year                     2009
population             225902
state            Rhode Island
area (sq. mi)            1545
Name: 1913, dtype: object
state/region               RI
ages                    total
year                     2010
population        1.05267e+06
state            Rhode Island
area (sq. mi)            1545
Name: 1914, dtype: object
state/region               RI
ages                  under18
year                     2010
population             223088

Name: 1940, dtype: object
state/region                 SC
ages                    under18
year                       2004
population          1.02911e+06
state            South Carolina
area (sq. mi)             32007
Name: 1941, dtype: object
state/region                 SC
ages                      total
year                       2002
population           4.1078e+06
state            South Carolina
area (sq. mi)             32007
Name: 1942, dtype: object
state/region                 SC
ages                    under18
year                       2002
population          1.02053e+06
state            South Carolina
area (sq. mi)             32007
Name: 1943, dtype: object
state/region                 SC
ages                      total
year                       2001
population            4.065e+06
state            South Carolina
area (sq. mi)             32007
Name: 1944, dtype: object
state/region                 SC
ages                    under18
year                       2001
population          1.01613e+06
state            South Carolina
area (sq. mi)             32007
Name: 1945, dtype: object
state/region                 SC
ages                      total
year                       1999
population          3.97468e+06
state            South Carolina
area (sq. mi)             32007
Name: 1946, dtype: object
state/region                 SC
ages                    under18
year                       1999
population          1.00705e+06
state            South Carolina
area (sq. mi)             32007
Name: 1947, dtype: object
state/region                 SC
ages                      total
year                       2000
population          4.02422e+06
state            South Carolina
area (sq. mi)             32007
Name: 1948, dtype: object
state/region                 SC
ages                    under18
year                       2000
population          1.01064e+06
state            South Carolina
area (sq. mi)             32007
Name: 1949, dtype: object
state/region                 SC
ages                      total
year                       1997
population           3.8597e+06
state            South Carolina
area (sq. mi)             32007
Name: 1950, dtype: object
state/region                 SC
ages                    under18
year                       1997
population          1.00168e+06
state            South Carolina
area (sq. mi)             32007
Name: 1951, dtype: object
state/region                 SC
ages                    under18
year                       1998
population          1.00637e+06
state            South Carolina
area (sq. mi)             32007
Name: 1952, dtype: object
state/region                 SC
ages                      total
year                       1998
population          3.91924e+06
state            South Carolina
area (sq. mi)             32007
Name: 1953, dtype: object
state/region                 SC
ages                    under18
year                       1996
population               987576
state            South Carolina
area (sq. mi)             32007
Name: 1954, dtype: object
state/region                 SC
ages                      total
year                       1996
population           3.7962e+06
state            South Carolina
area (sq. mi)             32007
Name: 1955, dtype: object
state/region                 SC
ages                      total
year                       1995
population          3.74858e+06
state            South Carolina
area (sq. mi)             32007
Name: 1956, dtype: object
state/region                 SC
ages                    under18
year                       1995
population               975884
state            South Carolina
area (sq. mi)             32007
Name: 1957, dtype: object
state/region                 SC
ages                    under18
year                       1994
population               969766
state            South Carolina
area (sq. mi)             32007
Name: 1958, dtype: object

In [ ]:
data2010 = final.query("(year == 2010) and (ages == 'total')")
print(data2010)

In [ ]:
data2010.set_index('state',inplace = True)
density = data2010['population'] / data2010['area (sq. mi)']
density.sort_values(ascending = False, inplace = True)
print(density.tail())
print(data2010)